plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.remember.wechatopensdk'
version = '1.0.0'

android {
  namespace "com.remember.wechatopensdk"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
  }
}

dependencies {
  implementation 'com.tencent.mm.opensdk:wechat-sdk-android:6.8.34'
}
