"""Mnemonics and inflection notes for 闽教版 Grade 5 English, Volume 1 (上册).

谐音规则：仅真实谐音，不硬凑；优先语义/形象/拆词联想。
"""

from __future__ import annotations

SOUND_MNEMONICS: dict[str, str] = {
    'beside': 'beside 音近「比赛的」，比赛的选手 beside 在旁边。',
    'cinema': 'cinema 音近「西呢嘛」，西呢嘛去 cinema 看电影。',
    'flower': 'flower 音近「弗劳尔」，弗劳尔送 flower 花。',
    'hair': 'hair 音近「海尔」，海尔的 hair 头发。',
    'hospital': 'hospital 音近「好斯皮头」，好斯皮头去医院 hospital。',
    'minute': 'minute 音近「米尼特」，米尼特等 minute 分钟。',
    'museum': 'museum 音近「缪兹恩」，缪兹恩参观 museum 博物馆。',
    'near': 'near 音近「尼尔」，尼尔住 near 附近。',
    'panda': 'panda 音近「潘达」，潘达就是 panda 熊猫。',
    'paper': 'paper 音近「佩珀」，佩珀拿 paper 纸。',
    'photo': 'photo 音近「佛头」，佛头拍 photo 照片。',
    'pupil': 'pupil 音近「皮优尔」，皮优尔是 pupil 小学生。',
    'sorry': 'sorry 音近「扫瑞」，扫瑞说 sorry 对不起。',
    'tall': 'tall 音近「套」，套着 tall 高个子的衣服。',
    'taxi': 'taxi 音近「泰克西」，泰克西坐 taxi 的士。',
    'tell': 'tell 音近「泰尔」，泰尔 tell 告诉你。',
    'tomorrow': 'tomorrow 音近「特毛柔」，特毛柔说明天 tomorrow。',
    'turn': 'turn 音近「特恩」，特恩 turn 转弯。',
    'where': 'where 音近「威尔」，威尔问 where 哪里。',
    'write': 'write 音近「瑞特」，瑞特 write 写字。',
}

ROOT_MNEMONICS: dict[str, str] = {
    'bus stop': 'bus 公共汽车 + stop 停，bus stop 是公交车站。',
    'classmate': 'class 班 + mate 伙伴，classmate 是同班同学。',
    'far away': 'far 远 + away 离开，far away 是很远。',
    'get to': 'get 到达 + to 到，get to 是到达。',
    'go straight': 'go 走 + straight 直，go straight 是一直往前走。',
    'holiday': 'holi 神圣 + day 日，holiday 是假日。',
    'internet': 'inter 之间 + net 网，internet 是因特网。',
    'national day': 'national 国家的 + day 日，National Day 是国庆节。',
    "teachers' day": "teacher 老师 + day 日，Teachers' Day 是教师节。",
    'on my way': 'on 在 + my 我的 + way 路，on my way 是在我去……的路上。',
    'play chess': 'play 下 + chess 象棋，play chess 是下国际象棋。',
    'put on': 'put 放 + on 上，put on 是戴上、穿上。',
    'sit down': 'sit 坐 + down 下，sit down 是坐下。',
    'sitting room': 'sitting 坐 + room 房间，sitting room 是客厅。',
    'the usa': 'the 这个 + USA 美国，the USA 是美国。',
    'turn on': 'turn 转 + on 开，turn on 是打开。',
    "won't = will not": "will 将 + not 不，won't 就是「将不」。",
    "you're welcome.": "you're 你是 + welcome 欢迎，You're welcome. 是「不用谢」。",
}

IMAGE_MNEMONICS: dict[str, str] = {
    'afraid': '想象看 scary film 时 afraid 害怕。',
    'australia': '想象 Australia 澳大利亚有袋鼠和考拉。',
    'chess': '想象黑白棋子在 chess 棋盘上。',
    'cinema': '想象 go to the cinema 看电影。',
    'flower': "想象 Teachers' Day 送 flower 花给老师。",
    'glasses': '想象 put on glasses 戴眼镜看电影。',
    'hospital': '想象 hospital 医院红十字标志。',
    'mount': '想象 mount 山在 far away 远方。',
    'museum': '想象 museum 博物馆里有很多 old things。',
    'panda': '想象 lovely panda 可爱的熊猫。',
    'photo': '想象 take a photo of the panda 给熊猫拍照。',
    'picture': '想象 picture 图画挂在 sitting room 客厅。',
    'taxi': '想象 take a taxi 到 station 车站。',
}

SEMANTIC_MNEMONICS: dict[str, str] = {
    'about': 'Tell me about National Day. about 是关于。',
    'afraid': "Don't be afraid. afraid 是害怕。",
    'april': 'April is a spring month. April 是四月。',
    'august': 'August is hot. August 是八月。',
    'behind': 'The cat is behind the door. behind 是在……后面。',
    'call': 'Call me on my mobile. call 是打电话。',
    'city': 'I live in a big city. city 是城市。',
    'come on': 'Come on! Let us go. come on 是来吧。',
    'cook': 'My mother can cook. cook 是烹调。',
    'december': 'December is cold. December 是十二月。',
    'easy': 'This game is easy. easy 是容易的。',
    'excuse me.': 'Excuse me. Where is the station? Excuse me. 是请问、劳驾。',
    'february': 'February is short. February 是二月。',
    'film': 'We watch a film at the cinema. film 是电影。',
    'find': 'Find your book. find 是找到、发现。',
    'glasses': 'Put on your glasses. glasses 是眼镜。',
    'hair': 'She has long hair. hair 是头发。',
    'january': 'January is the first month. January 是一月。',
    'july': 'We visit my uncle in July. July 是七月。',
    'june': 'June is a summer month. June 是六月。',
    'kind': 'Our teacher is kind. kind 是亲切的、和蔼的。',
    'know': 'I know the way. know 是知道。',
    'left': 'Turn left, please. left 是左边的。',
    'long': 'She has long hair. long 是长的。',
    'lovely': 'The panda is lovely. lovely 是可爱的。',
    'man': 'The young man is tall. man 是男人。',
    'march': 'March comes before April. March 是三月。',
    'may': 'May is warm. May 是五月。',
    'mobile': 'This is my mobile. mobile 是手机。',
    'month': 'Which month is it? month 是月份。',
    'nearby': 'The hospital is nearby. nearby 是附近。',
    'november': 'November is cool. November 是十一月。',
    'october': 'National Day is in October. October 是十月。',
    'or': 'March or April? or 是或者。',
    'page': 'Open your book at page ten. page 是页。',
    'player': 'He is a good player. player 是球员。',
    'remember': 'Remember the months. remember 是记住。',
    'right': 'Turn right at the corner. right 是右边的。',
    'see': 'I see. Thank you. see 是明白、看见。',
    'september': "Teachers' Day is in September. September 是九月。",
    'short': 'He is short. short 是短的、矮的。',
    'smile': 'She has a lovely smile. smile 是微笑。',
    'speak': 'Can I speak to Lily? speak 是说话。',
    'station': 'Where is the station? station 是车站。',
    'tall': 'The boy is tall. tall 是高的。',
    'there': 'There is a mount over there. there 是那里。',
    'thing': 'Put your things in the bag. thing 是东西。',
    'time': 'What time is it? time 是时间、次数。',
    'uncle': 'My uncle lives in Australia. uncle 是叔叔、伯伯。',
    'understand': 'I understand you. understand 是理解、明白。',
    'wait': 'Wait a minute, please. wait 是等候、等待。',
    'way': 'Which way is the hospital? way 是路、方向。',
    'welcome': 'Welcome to our school! welcome 是欢迎。',
    'word': 'Read this word, please. word 是词。',
    'young': 'The young man is a player. young 是年轻的。',
}

INFLECTION_NOTES: dict[str, str] = {
    'cook': '第三人称单数 cooks',
    'find': '第三人称单数 finds；过去式 found',
    'flower': '复数 flowers',
    'glasses': '形式不变（通常用复数）',
    'man': '复数 men（不规则变化）',
    'month': '复数 months',
    'player': '复数 players',
    'remember': '第三人称单数 remembers',
    'smile': '第三人称单数 smiles',
    'speak': '第三人称单数 speaks；过去式 spoke',
    'tell': '第三人称单数 tells；过去式 told',
    'turn': '第三人称单数 turns',
    'uncle': '复数 uncles',
    'wait': '第三人称单数 waits',
    'write': '第三人称单数 writes；过去式 wrote',
    'know': '第三人称单数 knows；过去式 knew',
    'see': '第三人称单数 sees；过去式 saw',
    'call': '第三人称单数 calls',
    'understand': '第三人称单数 understands；过去式 understood',
}

DEFINITION_OVERRIDES: dict[str, str] = {
    'tall': '高的',
    'beside': '在……的旁边',
    'pupil': '小学生',
    'Australia': '澳大利亚',
    'behind': '在……的后面',
    'short': '短的；矮的',
    'long': '长的',
    'hair': '头发',
    'where': '哪里',
    'sitting room': '客厅',
    'lovely': '可爱的',
    'panda': '熊猫',
    'September': '九月',
    'tomorrow': '明天',
    "Teachers' Day": '教师节',
    'kind': '亲切的；和蔼的',
    'near': '在附近',
    'flower': '花；花朵',
    'paper': '纸',
    'picture': '照片；图画',
    'photo': '照片',
    'smile': '微笑',
    'National Day': '国庆节',
    'holiday': '假日',
    'uncle': '叔叔；伯伯',
    "won't = will not": '将不',
    'mount': '山',
    'tell': '告诉',
    'about': '关于',
    'July': '七月',
    'August': '八月',
    'October': '十月',
    'there': '那里',
    'turn on': '打开',
    'find': '找到；发现',
    'thing': '东西',
    'Internet': '因特网',
    'cinema': '电影院',
    'sit down': '坐下',
    'put on': '戴上；穿上',
    'glasses': '眼镜',
    'film': '电影',
    'afraid': '害怕',
    'welcome': '欢迎',
    'museum': '博物馆',
    'cook': '烹调',
    'player': '球员',
    'chess': '国际象棋',
    'play chess': '下国际象棋',
    'come on': '来吧',
    'April': '四月',
    'March': '三月',
    'June': '六月',
    'May': '五月',
    'month': '月份',
    'December': '十二月',
    'January': '一月',
    'easy': '容易的',
    'remember': '记住',
    'November': '十一月',
    'February': '二月',
    'or': '或者',
    'Excuse me.': '请问；劳驾',
    'get to': '到达',
    'station': '车站',
    'far away': '很远',
    'taxi': '的士',
    'young': '年轻的',
    'man': '男人',
    "You're welcome.": '不用谢',
    'hospital': '医院',
    'nearby': '附近',
    'go straight': '一直往前走',
    'turn': '转向；转弯',
    'right': '右边的',
    'left': '左边的',
    'bus stop': '公交车站',
    'speak': '说话；讲话',
    'wait': '等候；等待',
    'minute': '分钟',
    'page': '页',
    'write': '写字',
    'word': '词',
    'sorry': '对不起',
    'time': '时间；次数',
    'call': '呼叫；打电话',
    'mobile': '手机',
    'way': '路；方向',
    'on my way': '在我去……的路上',
    'city': '城市',
    'the USA': '美国',
    'classmate': '同班同学',
    'understand': '理解；明白',
    'know': '知道',
    'see': '看见；明白',
}

POS_OVERRIDES: dict[str, str] = {
    'tall': 'adj.',
    'beside': 'prep.',
    'pupil': 'n.',
    'Australia': 'n.',
    'behind': 'prep./adv.',
    'short': 'adj.',
    'long': 'adj.',
    'hair': 'n.',
    'where': 'adv.',
    'sitting room': 'n.',
    'lovely': 'adj.',
    'panda': 'n.',
    'September': 'n.',
    'tomorrow': 'adv./n.',
    "Teachers' Day": 'n.',
    'kind': 'adj.',
    'near': 'adv./prep./adj.',
    'flower': 'n.',
    'paper': 'n.',
    'picture': 'n.',
    'photo': 'n.',
    'smile': 'v./n.',
    'National Day': 'n.',
    'holiday': 'n.',
    'uncle': 'n.',
    "won't = will not": 'v.',
    'mount': 'n.',
    'tell': 'v.',
    'about': 'prep./adv.',
    'July': 'n.',
    'August': 'n.',
    'October': 'n.',
    'there': 'adv.',
    'turn on': 'v. phr.',
    'find': 'v.',
    'thing': 'n.',
    'Internet': 'n.',
    'cinema': 'n.',
    'sit down': 'v. phr.',
    'put on': 'v. phr.',
    'glasses': 'n.',
    'film': 'n.',
    'afraid': 'adj.',
    'welcome': 'v./adj./interj.',
    'museum': 'n.',
    'cook': 'v.',
    'player': 'n.',
    'chess': 'n.',
    'play chess': 'v. phr.',
    'come on': 'v. phr.',
    'April': 'n.',
    'March': 'n.',
    'June': 'n.',
    'May': 'n.',
    'month': 'n.',
    'December': 'n.',
    'January': 'n.',
    'easy': 'adj.',
    'remember': 'v.',
    'November': 'n.',
    'February': 'n.',
    'or': 'conj.',
    'Excuse me.': 'phrase',
    'get to': 'v. phr.',
    'station': 'n.',
    'far away': 'adv. phr.',
    'taxi': 'n.',
    'young': 'adj.',
    'man': 'n.',
    "You're welcome.": 'phrase',
    'hospital': 'n.',
    'nearby': 'adv./adj.',
    'go straight': 'v. phr.',
    'turn': 'v./n.',
    'right': 'adj./adv./n.',
    'left': 'adj./adv./n.',
    'bus stop': 'n.',
    'speak': 'v.',
    'wait': 'v.',
    'minute': 'n.',
    'page': 'n.',
    'write': 'v.',
    'word': 'n.',
    'sorry': 'adj./interj.',
    'time': 'n.',
    'call': 'v./n.',
    'mobile': 'n./adj.',
    'way': 'n.',
    'on my way': 'phrase',
    'city': 'n.',
    'the USA': 'n.',
    'classmate': 'n.',
    'understand': 'v.',
    'know': 'v.',
    'see': 'v.',
}

IPA_OVERRIDES: dict[str, str] = {
    'tall': '/tɔːl/',
    'beside': '/bɪˈsaɪd/',
    'pupil': '/ˈpjuːpl/',
    'Australia': '/ɒˈstreɪliə, ɔːˈstreɪliə/',
    'behind': '/bɪˈhaɪnd/',
    'short': '/ʃɔːt/',
    'long': '/lɒŋ/',
    'hair': '/heə(r)/',
    'where': '/weə(r)/',
    'sitting room': '/ˈsɪtɪŋ ruːm/',
    'lovely': '/ˈlʌvli/',
    'panda': '/ˈpændə/',
    'September': '/sepˈtembə(r)/',
    'tomorrow': '/təˈmɒrəʊ/',
    "Teachers' Day": '/ˈtiːtʃəz deɪ/',
    'kind': '/kaɪnd/',
    'near': '/nɪə(r)/',
    'flower': '/ˈflaʊə(r)/',
    'paper': '/ˈpeɪpə(r)/',
    'picture': '/ˈpɪktʃə(r)/',
    'photo': '/ˈfəʊtəʊ/',
    'smile': '/smaɪl/',
    'National Day': '/ˈnæʃnəl deɪ/',
    'holiday': '/ˈhɒlədeɪ, ˈhɒlədi/',
    'uncle': '/ˈʌŋkl/',
    "won't = will not": '/wəʊnt/',
    'mount': '/maʊnt/',
    'tell': '/tel/',
    'about': '/əˈbaʊt/',
    'July': '/dʒuˈlaɪ/',
    'August': '/ˈɔːɡəst/',
    'October': '/ɒkˈtəʊbə(r)/',
    'there': '/ðeə(r)/',
    'turn on': '/tɜːn ɒn/',
    'find': '/faɪnd/',
    'thing': '/θɪŋ/',
    'Internet': '/ˈɪntənet/',
    'cinema': '/ˈsɪnəmə/',
    'sit down': '/sɪt daʊn/',
    'put on': '/pʊt ɒn/',
    'glasses': '/ˈɡlɑːsɪz/',
    'film': '/fɪlm/',
    'afraid': '/əˈfreɪd/',
    'welcome': '/ˈwelkəm/',
    'museum': '/mjuːˈziːəm/',
    'cook': '/kʊk/',
    'player': '/ˈpleɪə(r)/',
    'chess': '/tʃes/',
    'play chess': '/pleɪ tʃes/',
    'come on': '/kʌm ɒn/',
    'April': '/ˈeɪprəl/',
    'March': '/mɑːtʃ/',
    'June': '/dʒuːn/',
    'May': '/meɪ/',
    'month': '/mʌnθ/',
    'December': '/dɪˈsembə(r)/',
    'January': '/ˈdʒænjuəri, ˈdʒænjueri/',
    'easy': '/ˈiːzi/',
    'remember': '/rɪˈmembə(r)/',
    'November': '/nəʊˈvembə(r)/',
    'February': '/ˈfebruəri, ˈfebrueri/',
    'or': '/ɔː(r)/',
    'Excuse me.': '/ɪkˈskjuːs miː/',
    'get to': '/ɡet tuː, ɡet tə/',
    'station': '/ˈsteɪʃn/',
    'far away': '/fɑː(r) əˈweɪ/',
    'taxi': '/ˈtæksi/',
    'young': '/jʌŋ/',
    'man': '/mæn/',
    "You're welcome.": '/jɔː(r) ˈwelkəm/',
    'hospital': '/ˈhɒspɪtl/',
    'nearby': '/ˌnɪəˈbaɪ/',
    'go straight': '/ɡəʊ streɪt/',
    'turn': '/tɜːn/',
    'right': '/raɪt/',
    'left': '/left/',
    'bus stop': '/bʌs stɒp/',
    'speak': '/spiːk/',
    'wait': '/weɪt/',
    'minute': '/ˈmɪnɪt/',
    'page': '/peɪdʒ/',
    'write': '/raɪt/',
    'word': '/wɜːd/',
    'sorry': '/ˈsɒri/',
    'time': '/taɪm/',
    'call': '/kɔːl/',
    'mobile': '/ˈməʊbaɪl/',
    'way': '/weɪ/',
    'on my way': '/ɒn maɪ weɪ/',
    'city': '/ˈsɪti/',
    'the USA': '/ðə ˌjuː es ˈeɪ/',
    'classmate': '/ˈklɑːsmeɪt/',
    'understand': '/ˌʌndəˈstænd/',
    'know': '/nəʊ/',
    'see': '/siː/',
}


def _secondary_mnemonic(key: str, headword: str, definition_zh: str, *, kind: str) -> str | None:
    if key in ROOT_MNEMONICS:
        return f'拆词联想：{ROOT_MNEMONICS[key]}'
    if key in IMAGE_MNEMONICS:
        return f'形象联想：{IMAGE_MNEMONICS[key]}'
    if key in SEMANTIC_MNEMONICS:
        return f'语义联想：{SEMANTIC_MNEMONICS[key]}'

    short = definition_zh.split('；')[0].split('，')[0].strip()
    if kind == 'phrase':
        return f'语义联想：把「{short}」和短语 {headword} 配对记忆。'

    months = {
        'january', 'february', 'march', 'april', 'may', 'june',
        'july', 'august', 'september', 'october', 'november', 'december',
    }
    adjectives = {
        'tall', 'short', 'long', 'lovely', 'kind', 'afraid', 'easy', 'young',
        'right', 'left', 'nearby', 'sorry',
    }
    if key in months:
        return f'形象联想：想象日历上的 {headword} {short}，边指边记住它。'
    if key in adjectives:
        return f'语义联想：看到「{short}」的事物时，就想到 {headword}。'
    return f'语义联想：把「{short}」和英文 {headword} 配对记忆。'


def mnemonic_for(headword: str, definition_zh: str, *, kind: str) -> str:
    key = headword.lower()
    parts: list[str] = []

    if key in SOUND_MNEMONICS:
        parts.append(f'谐音联想：{SOUND_MNEMONICS[key]}')

    secondary = _secondary_mnemonic(key, headword, definition_zh, kind=kind)
    if secondary:
        if parts:
            if secondary not in parts[0]:
                parts.append(secondary)
        else:
            parts.append(secondary)

    return parts[0] if len(parts) == 1 else '\n'.join(parts)
