"""Mnemonics and inflection notes for 闽教版 Grade 5 English, Volume 2 (下册).

谐音规则：仅真实谐音，不硬凑；优先语义/形象/拆词联想。
"""

from __future__ import annotations

SOUND_MNEMONICS: dict[str, str] = {
    'ate': 'ate 音近「埃特」，埃特 ate 吃了饭。',
    'camera': 'camera 音近「凯姆拉」，凯姆拉用 camera 拍照。',
    'china': 'China 音近「chai 呐」，chai 呐代表中国 China。',
    'cloud': 'cloud 音近「克劳德」，克劳德看 cloud 云。',
    'doctor': 'doctor 音近「道克特」，道克特是 doctor 医生。',
    'elephant': 'elephant 音近「艾里芳特」，艾里芳特是 elephant 大象。',
    'fast': 'fast 音近「法斯特」，法斯特 run fast 跑得很快。',
    'gate': 'gate 音近「盖特」，盖特从 gate 大门进。',
    'guess': 'guess 音近「盖斯」，盖斯 guess 猜一猜。',
    'hill': 'hill 音近「希欧」，希欧爬 hill 小山。',
    'hometown': 'hometown 音近「厚姆汤」，厚姆汤回 hometown 故乡。',
    'hungry': 'hungry 音近「汉格瑞」，汉格瑞 feel hungry 饿了。',
    'lake': 'lake 音近「雷克」，雷克在 lake 湖边。',
    'love': 'love 音近「拉夫」，拉夫 love 爱。',
    'map': 'map 音近「麦普」，麦普看 map 地图。',
    'meal': 'meal 音近「米尔」，米尔吃 meal 一顿饭。',
    'meter': 'meter 音近「米特」，米特量 meter 米。',
    'mountain': 'mountain 音近「毛恩腾」，毛恩腾爬 mountain 山。',
    'parent': 'parent 音近「佩润特」，佩润特是 parent 家长。',
    'pick': 'pick 音近「皮克」，皮克 pick 摘苹果。',
    'proud': 'proud 音近「普劳德」，普劳德 feel proud 自豪。',
    'race': 'race 音近「瑞斯」，瑞斯 run a race 赛跑。',
    'ran': 'ran 音近「润」，润 ran 跑过终点。',
    'sad': 'sad 音近「赛的」，赛的 feel sad 感到难过。',
    'serve': 'serve 音近「瑟夫」，瑟夫 serve 服务。',
    'shout': 'shout 音近「绍特」，绍特 shout 喊叫。',
    'sky': 'sky 音近「斯凯」，斯凯看 sky 天空。',
    'swam': 'swam 音近「斯旺姆」，斯旺姆 swam 游泳。',
    'team': 'team 音近「提姆」，提姆在 team 队里。',
    'tired': 'tired 音近「泰尔德」，泰尔德 feel tired 疲倦。',
    'tour': 'tour 音近「图尔」，图尔去 tour 旅行。',
    'try': 'try 音近「揣」，揣一 try 试一试。',
    'village': 'village 音近「维里奇」，维里奇 visit village 村庄。',
    'water': 'water 音近「沃特」，沃特喝 water 水。',
    'well': 'well 音近「威尔」，威尔 do well 做得好。',
    'wife': 'wife 音近「外夫」，外夫和 wife 妻子。',
}

ROOT_MNEMONICS: dict[str, str] = {
    'cheer up': 'cheer 欢呼 + up 起来，cheer up 是振作起来。',
    'covid-19': 'COVID 冠状病毒 + 19 年，Covid-19 是新冠病毒。',
    'fall down': 'fall 跌倒 + down 向下，fall down 是跌倒。',
    'get on': 'get 上 + on 到……上，get on 是上车。',
    'grow up': 'grow 生长 + up 向上，grow up 是长大。',
    'hard-working': 'hard 努力 + working 工作，hard-working 是努力工作的。',
    'high jump': 'high 高 + jump 跳，high jump 是跳高。',
    'living room': 'living 生活 + room 房间，living room 是客厅。',
    'long jump': 'long 远 + jump 跳，long jump 是跳远。',
    'medal of the republic': 'Medal 勋章 + Republic 共和国，Medal of the Republic 是共和国勋章。',
    'next to': 'next 下一个 + to 到，next to 是紧挨着。',
    'over there': 'over 越过 + there 那里，over there 是在那边。',
    'search for': 'search 搜索 + for 为了，search for 是搜索。',
    'sports day': 'sports 运动 + day 日，Sports Day 是运动会。',
    'spring outing': 'spring 春 + outing 外出，spring outing 是春游。',
    'sun moon lake': 'Sun 日 + Moon 月 + Lake 湖，Sun Moon Lake 是日月潭。',
    'young pioneer': 'Young 少年 + Pioneer 先锋，Young Pioneer 是少先队员。',
}

IMAGE_MNEMONICS: dict[str, str] = {
    'animal': '想象 zoo 里各种 animal 动物。',
    'bridge': '想象 bridge 桥横跨 river 河。',
    'building': '想象 tall building 有很多 floor 楼层。',
    'calendar': '想象 calendar 日历上圈出 date 日期。',
    'camera': '想象 spring outing 用 camera 拍照。',
    'china': '想象 China 中国地图上的 Sun Moon Lake。',
    'cloud': '想象 white cloud 云在 sky 天空。',
    'elephant': '想象 elephant 大象在 zoo over there。',
    'farmhouse': '想象 village 村里有 farmhouse 农舍。',
    'grass': '想象 Sports Day 在 green grass 上跑步。',
    'hero': '想象 doctor 医生是 fight Covid-19 的 hero。',
    'lake': '想象 Sun Moon Lake 日月潭的 lake 湖。',
    'map': '想象 map 地图上标着 elephant 和 hill。',
    'medal of the republic': '想象 hero 获得 Medal of the Republic 共和国勋章。',
    'mountain': '想象 spring outing 爬 mountain 山到 top 顶部。',
    'race': '想象 Sports Day 上 run a race 赛跑。',
    'river': '想象 river 河上有 bridge 桥。',
    'spring outing': '想象 spring outing 春游 climb mountain 爬山。',
    'sun moon lake': '想象 Sun Moon Lake 日月潭的 beautiful lake。',
}

SEMANTIC_MNEMONICS: dict[str, str] = {
    'also': 'My grandfather also lives here. also 是也。',
    'angry': 'Do not be angry. angry 是生气的。',
    'any': 'Do you have any food? any 是任何的。',
    'award': 'They award the hero a medal. award 是授予、奖励。',
    'before': 'Wash hands before dinner. before 是在……之前。',
    'bridge': 'There is a bridge over the river. bridge 是桥。',
    'busy': 'Sports Day is busy. busy 是忙的。',
    'calendar': 'Look at the calendar. calendar 是日历。',
    'climb': 'We climb the mountain. climb 是攀爬。',
    'date': 'What is the date today? date 是日期。',
    'did': 'What did you do? did 是 do 的过去式，做了。',
    'difficult': 'This is difficult. difficult 是困难的。',
    'dr.': 'Dr. Li is a hero. Dr. 是医生、博士。',
    'drink': 'Drink some water. drink 是喝。',
    'fast': 'Run fast! fast 是快地、快的。',
    'fight': 'Doctors fight Covid-19. fight 是战斗、斗争。',
    'first': 'She came first. first 是第一。',
    'floor': 'Which floor? floor 是楼层。',
    'fourth': 'He came fourth. fourth 是第四。',
    'grandfather': 'My grandfather lives here. grandfather 是祖父、外公。',
    'grandmother': 'My grandmother sits here. grandmother 是祖母、外婆。',
    'hard': 'Work hard. hard 是努力地、努力的。',
    'honor': 'It is a great honor. honor 是荣誉。',
    'information': 'We need information. information 是信息。',
    'learn': 'Learn from heroes. learn 是学习。',
    'lucky': 'You are lucky! lucky 是幸运的。',
    'member': 'She is a member of the team. member 是成员。',
    'mrs.': 'Good morning, Mrs. Wang! Mrs. 是夫人、太太。',
    'neighbor': 'Our neighbor is kind. neighbor 是邻居。',
    'only': 'I only came fourth. only 是仅仅。',
    'people': 'Doctors serve people. people 是人、人们。',
    'program': 'Watch a program. program 是节目。',
    'really': 'It was really fun. really 是确实地、的确。',
    'saw': 'We saw an elephant. saw 是 see 的过去式，看见了。',
    'second': 'He came second. second 是第二。',
    'still': 'She is still at work. still 是还是、仍然。',
    'third': 'Our team came third. third 是第三。',
    'top': 'We climbed to the top of the mountain. top 是顶部。',
    'thirsty': 'I am thirsty. thirsty 是渴的。',
    'took': 'We took a tour. took 是 take 的过去式，带了、拿了。',
    'twelfth': 'The twelfth floor. twelfth 是第十二。',
    'under': 'The cat is under the tree. under 是在……下面。',
    'was': 'I was in China. was 是 am/is 的过去式，曾经是。',
    'went': 'We went to the lake. went 是 go 的过去式，去了。',
    'were': 'We were at the lake. were 是 are 的过去式，曾是。',
    'women': 'Many women are heroes. women 是成年女子、妇女。',
    'would': 'I would like to visit. would 是会、愿意。',
}

INFLECTION_NOTES: dict[str, str] = {
    'angry': '比较级 angrier；最高级 angriest',
    'ate': 'eat 的过去式',
    'award': '第三人称单数 awards；过去式 awarded',
    'busy': '比较级 busier；最高级 busiest',
    'climb': '第三人称单数 climbs；过去式 climbed',
    'did': 'do 的过去式',
    'difficult': '比较级 more difficult；最高级 most difficult',
    'drink': '第三人称单数 drinks；过去式 drank',
    'fast': '比较级 faster；最高级 fastest',
    'fight': '第三人称单数 fights；过去式 fought',
    'hard': '比较级 harder；最高级 hardest',
    'hero': '复数 heroes',
    'honor': '复数 honors（英式 honour）',
    'hungry': '比较级 hungrier；最高级 hungriest',
    'learn': '第三人称单数 learns；过去式 learned/learnt',
    'lucky': '比较级 luckier；最高级 luckiest',
    'member': '复数 members',
    'parent': '复数 parents',
    'people': '复数仍为 people；表「民族」时为 peoples',
    'pick': '第三人称单数 picks；过去式 picked',
    'proud': '比较级 prouder；最高级 proudest',
    'race': '第三人称单数 races；过去式 raced',
    'ran': 'run 的过去式',
    'sad': '比较级 sadder；最高级 saddest',
    'saw': 'see 的过去式',
    'serve': '第三人称单数 serves；过去式 served',
    'shout': '第三人称单数 shouts；过去式 shouted',
    'swam': 'swim 的过去式',
    'team': '复数 teams',
    'thirsty': '比较级 thirstier；最高级 thirstiest',
    'tired': '比较级 more tired',
    'took': 'take 的过去式',
    'try': '第三人称单数 tries；过去式 tried',
    'was': 'am/is 的过去式；复数过去式 were',
    'went': 'go 的过去式',
    'were': 'are 的过去式',
    'wife': '复数 wives（不规则变化）',
    'women': 'woman 的复数形式',
}

DEFINITION_OVERRIDES: dict[str, str] = {
    'was': '是（过去式）',
    'were': '是（过去式）',
    'China': '中国',
    'went': '去（过去式）',
    'parent': '父，母；家长',
    'hometown': '故乡',
    'took': '拿；带（过去式）',
    'tour': '旅行；旅游',
    'Sun Moon Lake': '日月潭',
    'lake': '湖',
    'did': '做（过去式）',
    'swam': '游泳（过去式）',
    'elephant': '大象',
    'map': '地图',
    'over there': '在那边',
    'hill': '小山',
    'under': '在……下面',
    'next to': '紧挨着',
    'animal': '动物',
    'saw': '看见（过去式）',
    'hungry': '饿的',
    'ate': '吃（过去式）',
    'any': '任何的；若干',
    'doctor': '医生',
    'search for': '搜索；查找',
    'information': '信息',
    'tired': '疲倦的',
    'fight': '战斗；与……作斗争',
    'Covid-19': '新型冠状病毒感染',
    'love': '爱',
    'people': '人；人们',
    'hero': '英雄',
    'award': '授予；奖励',
    'Medal of the Republic': '共和国勋章',
    'honor': '荣誉',
    'Young Pioneer': '少先队员',
    'learn': '学习',
    'hard': '努力',
    'serve': '服务',
    'grow up': '长大',
    'Dr.': '医生；博士',
    'still': '还是；仍然',
    'wife': '妻子',
    'member': '成员',
    'women': '成年女子；妇女',
    'team': '（体育的）队',
    'spring outing': '春游',
    'climb': '攀爬',
    'mountain': '山',
    'water': '水',
    'thirsty': '渴的',
    'camera': '照相机',
    'sky': '天空',
    'cloud': '云',
    'get on': '上车',
    'gate': '大门',
    'pick': '采；摘',
    'village': '乡村；村庄',
    'hard-working': '努力工作的',
    'top': '顶部',
    'farmhouse': '农舍',
    'really': '确实地；的确',
    'meal': '一顿饭',
    'Sports Day': '运动会',
    'meter': '米',
    'fast': '快',
    'long jump': '跳远',
    'try': '尝试',
    'high jump': '跳高',
    'shout': '喊叫',
    'proud': '自豪的；骄傲的',
    'fall down': '跌倒；跌下',
    'well': '好',
    'busy': '忙的',
    'ran': '跑（过去式）',
    'grass': '草',
    'race': '赛跑',
    'first': '第一',
    'second': '第二',
    'third': '第三',
    'drink': '喝',
    'sad': '难过的',
    'cheer up': '振作起来',
    'only': '仅仅',
    'fourth': '第四',
    'angry': '生气的',
    'program': '节目',
    'building': '建筑物',
    'floor': '楼层',
    'twelfth': '第十二',
    'would': '会；愿意（表较合意愿）',
    'living room': '客厅；起居室',
    'bridge': '桥',
    'also': '也',
    'fifteenth': '第十五',
    'neighbor': '邻居',
    'river': '河',
    'grandmother': '祖母；外婆',
    'grandfather': '祖父；外公',
    'date': '日期',
    'lucky': '幸运的',
    'guess': '猜',
    'difficult': '困难的',
    'calendar': '日历',
    'before': '在……之前',
    'Mrs.': '夫人；太太',
}

POS_OVERRIDES: dict[str, str] = {
    'was': 'v.',
    'were': 'v.',
    'China': 'n.',
    'went': 'v.',
    'parent': 'n.',
    'hometown': 'n.',
    'took': 'v.',
    'tour': 'n./v.',
    'Sun Moon Lake': 'n.',
    'lake': 'n.',
    'did': 'v.',
    'swam': 'v.',
    'elephant': 'n.',
    'map': 'n.',
    'over there': 'adv. phr.',
    'hill': 'n.',
    'under': 'prep./adv.',
    'next to': 'prep. phr.',
    'animal': 'n.',
    'saw': 'v.',
    'hungry': 'adj.',
    'ate': 'v.',
    'any': 'det./pron.',
    'doctor': 'n.',
    'search for': 'v. phr.',
    'information': 'n.',
    'tired': 'adj.',
    'fight': 'v./n.',
    'Covid-19': 'n.',
    'love': 'v./n.',
    'people': 'n.',
    'hero': 'n.',
    'award': 'v./n.',
    'Medal of the Republic': 'n.',
    'honor': 'n.',
    'Young Pioneer': 'n.',
    'learn': 'v.',
    'hard': 'adv./adj.',
    'serve': 'v.',
    'grow up': 'v. phr.',
    'Dr.': 'n.',
    'still': 'adv.',
    'wife': 'n.',
    'member': 'n.',
    'women': 'n.',
    'team': 'n.',
    'spring outing': 'n.',
    'climb': 'v.',
    'mountain': 'n.',
    'water': 'n.',
    'thirsty': 'adj.',
    'camera': 'n.',
    'sky': 'n.',
    'cloud': 'n.',
    'get on': 'v. phr.',
    'gate': 'n.',
    'pick': 'v.',
    'village': 'n.',
    'hard-working': 'adj.',
    'top': 'n.',
    'farmhouse': 'n.',
    'really': 'adv.',
    'meal': 'n.',
    'Sports Day': 'n.',
    'meter': 'n.',
    'fast': 'adj./adv.',
    'long jump': 'n.',
    'try': 'v./n.',
    'high jump': 'n.',
    'shout': 'v./n.',
    'proud': 'adj.',
    'fall down': 'v. phr.',
    'well': 'adv./adj.',
    'busy': 'adj.',
    'ran': 'v.',
    'grass': 'n.',
    'race': 'n./v.',
    'first': 'num./adv.',
    'second': 'num./adv.',
    'third': 'num./adv.',
    'drink': 'v./n.',
    'sad': 'adj.',
    'cheer up': 'v. phr.',
    'only': 'adv./adj.',
    'fourth': 'num./adv.',
    'angry': 'adj.',
    'program': 'n.',
    'building': 'n.',
    'floor': 'n.',
    'twelfth': 'num.',
    'would': 'v. modal',
    'living room': 'n.',
    'bridge': 'n.',
    'also': 'adv.',
    'fifteenth': 'num.',
    'neighbor': 'n.',
    'river': 'n.',
    'grandmother': 'n.',
    'grandfather': 'n.',
    'date': 'n.',
    'lucky': 'adj.',
    'guess': 'v./n.',
    'difficult': 'adj.',
    'calendar': 'n.',
    'before': 'prep./adv.',
    'Mrs.': 'n.',
}

IPA_OVERRIDES: dict[str, str] = {
    'was': '/wɒz, wəz/',
    'were': '/wə(r), wɜː(r)/',
    'China': '/ˈtʃaɪnə/',
    'went': '/went/',
    'parent': '/ˈpeərənt, ˈpærənt/',
    'hometown': '/ˈhəʊmtaʊn/',
    'took': '/tʊk/',
    'tour': '/tʊə(r), tɔː(r)/',
    'Sun Moon Lake': '/ˌsʌn muːn ˈleɪk/',
    'lake': '/leɪk/',
    'did': '/dɪd, dəd/',
    'swam': '/swæm/',
    'elephant': '/ˈelɪfənt/',
    'map': '/mæp/',
    'over there': '/ˌəʊvə ˈðeə(r)/',
    'hill': '/hɪl/',
    'under': '/ˈʌndə(r)/',
    'next to': '/ˌnekst tuː, ˌnekst tə/',
    'animal': '/ˈænɪml/',
    'saw': '/sɔː/',
    'hungry': '/ˈhʌŋɡri/',
    'ate': '/et, eɪt/',
    'any': '/ˈeni/',
    'doctor': '/ˈdɒktə(r)/',
    'search for': '/sɜːtʃ fɔː(r), sɜːtʃ fə(r)/',
    'information': '/ˌɪnfəˈmeɪʃn/',
    'tired': '/ˈtaɪəd/',
    'fight': '/faɪt/',
    'Covid-19': '/ˌkəʊvɪd ˌnaɪnˈtiːn/',
    'love': '/lʌv/',
    'people': '/ˈpiːpl/',
    'hero': '/ˈhɪərəʊ/',
    'award': '/əˈwɔːd/',
    'Medal of the Republic': '/ˌmedl əv ðə rɪˈpʌblɪk/',
    'honor': '/ˈɒnə(r)/',
    'Young Pioneer': '/ˌjʌŋ ˌpaɪəˈnɪə(r)/',
    'learn': '/lɜːn/',
    'hard': '/hɑːd/',
    'serve': '/sɜːv/',
    'grow up': '/ɡrəʊ ʌp/',
    'Dr.': '/ˈdɒktə(r)/',
    'still': '/stɪl/',
    'wife': '/waɪf/',
    'member': '/ˈmembə(r)/',
    'women': '/ˈwɪmɪn/',
    'team': '/tiːm/',
    'spring outing': '/ˌsprɪŋ ˈaʊtɪŋ/',
    'climb': '/klaɪm/',
    'mountain': '/ˈmaʊntən/',
    'water': '/ˈwɔːtə(r)/',
    'thirsty': '/ˈθɜːsti/',
    'camera': '/ˈkæmərə/',
    'sky': '/skaɪ/',
    'cloud': '/klaʊd/',
    'get on': '/ɡet ɒn/',
    'gate': '/ɡeɪt/',
    'pick': '/pɪk/',
    'village': '/ˈvɪlɪdʒ/',
    'hard-working': '/ˌhɑːd ˈwɜːkɪŋ/',
    'top': '/tɒp/',
    'farmhouse': '/ˈfɑːmhaʊs/',
    'really': '/ˈriːəli, ˈrɪəli/',
    'meal': '/miːl/',
    'Sports Day': '/ˈspɔːts deɪ/',
    'meter': '/ˈmiːtə(r)/',
    'fast': '/fɑːst/',
    'long jump': '/ˌlɒŋ ˈdʒʌmp/',
    'try': '/traɪ/',
    'high jump': '/ˌhaɪ ˈdʒʌmp/',
    'shout': '/ʃaʊt/',
    'proud': '/praʊd/',
    'fall down': '/fɔːl daʊn/',
    'well': '/wel/',
    'busy': '/ˈbɪzi/',
    'ran': '/ræn/',
    'grass': '/ɡrɑːs/',
    'race': '/reɪs/',
    'first': '/fɜːst/',
    'second': '/ˈsekənd/',
    'third': '/θɜːd/',
    'drink': '/drɪŋk/',
    'sad': '/sæd/',
    'cheer up': '/tʃɪə ʌp/',
    'only': '/ˈəʊnli/',
    'fourth': '/fɔːθ/',
    'angry': '/ˈæŋɡri/',
    'program': '/ˈprəʊɡræm/',
    'building': '/ˈbɪldɪŋ/',
    'floor': '/flɔː(r)/',
    'twelfth': '/twelfθ/',
    'would': '/wʊd, wəd/',
    'living room': '/ˈlɪvɪŋ ruːm/',
    'bridge': '/brɪdʒ/',
    'also': '/ˈɔːlsəʊ/',
    'fifteenth': '/ˌfɪfˈtiːnθ/',
    'neighbor': '/ˈneɪbə(r)/',
    'river': '/ˈrɪvə(r)/',
    'grandmother': '/ˈɡrænmʌðə(r)/',
    'grandfather': '/ˈɡrænfɑːðə(r)/',
    'date': '/deɪt/',
    'lucky': '/ˈlʌki/',
    'guess': '/ɡes/',
    'difficult': '/ˈdɪfɪkəlt/',
    'calendar': '/ˈkælɪndə(r)/',
    'before': '/bɪˈfɔː(r)/',
    'Mrs.': '/ˈmɪsɪz/',
}

def _secondary_mnemonic(key: str, headword: str, definition_zh: str, *, kind: str) -> str | None:
    if key in ROOT_MNEMONICS:
        return f'拆词联想：{ROOT_MNEMONICS[key]}'
    if key in IMAGE_MNEMONICS:
        return f'形象联想：{IMAGE_MNEMONICS[key]}'
    if key in SEMANTIC_MNEMONICS:
        return f'语义联想：{SEMANTIC_MNEMONICS[key]}'

    short = definition_zh.split('；')[0].split('，')[0].strip()
    if kind == 'phrase':
        return f'语义联想：把「{short}」和短语 {headword} 配对记忆。'

    ordinals = {
        'first', 'second', 'third', 'fourth', 'twelfth', 'fifteenth',
    }
    adjectives = {
        'angry', 'any', 'busy', 'difficult', 'fast', 'hard', 'hard-working',
        'hungry', 'lucky', 'proud', 'sad', 'still', 'thirsty', 'tired',
    }
    if key in ordinals:
        return f'形象联想：想象 {headword} {short} 的名次牌，边指边记住它。'
    if key in adjectives:
        return f'语义联想：看到「{short}」的事物时，就想到 {headword}。'
    return f'语义联想：把「{short}」和英文 {headword} 配对记忆。'


def mnemonic_for(headword: str, definition_zh: str, *, kind: str) -> str:
    key = headword.lower()
    parts: list[str] = []

    if key in SOUND_MNEMONICS:
        parts.append(f'谐音联想：{SOUND_MNEMONICS[key]}')

    secondary = _secondary_mnemonic(key, headword, definition_zh, kind=kind)
    if secondary:
        if parts:
            if secondary not in parts[0]:
                parts.append(secondary)
        else:
            parts.append(secondary)

    return parts[0] if len(parts) == 1 else '\n'.join(parts)
