"""Mnemonics and inflection notes for 闽教版 Grade 6 English, Volume 1 (上册).

谐音规则：仅真实谐音，不硬凑；优先语义/形象/拆词联想。
"""

from __future__ import annotations

SOUND_MNEMONICS: dict[str, str] = {
    'answer': 'answer 音近「安瑟」，安瑟 answer 回答问题。',
    'continent': 'continent 音近「康提嫩特」，康提嫩特说 continent 大陆。',
    'strong': 'strong 音近「斯壮」，斯壮 feel strong 强壮。',
    'together': 'together 音近「图盖泽」，图盖泽 work together 一起。',
    'world': 'world 音近「沃尔德」，沃尔德说 world 世界。',
    'between': 'between 音近「比图因」，比图因 stand between 站在中间。',
    'catch': 'catch 音近「凯奇」，凯奇 catch 接住球。',
    'cheer': 'cheer 音近「起儿」，起儿 cheer 欢呼加油。',
    'exercise': 'exercise 音近「艾克赛赛兹」，艾克赛赛兹 exercise 锻炼。',
    'healthy': 'healthy 音近「海尔西」，海尔西 keep healthy 保持健康。',
    'pass': 'pass 音近「帕斯」，帕斯 pass 传球。',
    'team': 'team 音近「提姆」，提姆在 team 队里。',
    'basket': 'basket 音近「巴斯克特」，巴斯克特提 basket 篮子。',
    'delicious': 'delicious 音近「地里舍斯」，地里舍斯说 delicious 美味。',
    'glass': 'glass 音近「格拉斯」，格拉斯拿 glass 玻璃杯。',
    'menu': 'menu 音近「麦纽」，麦纽看 menu 菜单。',
    'problem': 'problem 音近「普罗布勒姆」，普罗布勒姆说 problem 问题。',
    'salad': 'salad 音近「萨拉德」，萨拉德吃 salad 色拉。',
    'boring': 'boring 音近「波灵」，波灵觉得 boring 很无聊。',
    'cap': 'cap 音近「凯普」，凯普戴 cap 帽子。',
    'daughter': 'daughter 音近「道特」，道特是 daughter 女儿。',
    'dress': 'dress 音近「德瑞斯」，德瑞斯穿 dress 连衣裙。',
    'pair': 'pair 音近「佩尔」，佩尔买 pair 一双。',
    'shorts': 'shorts 音近「绍茨」，绍茨穿 shorts 短裤。',
    'trousers': 'trousers 音近「特劳泽斯」，特劳泽斯穿 trousers 裤子。',
    'bedroom': 'bedroom 音近「贝德鲁姆」，贝德鲁姆在 bedroom 卧室。',
    'box': 'box 音近「博克斯」，博克斯放 box 盒子。',
    'floor': 'floor 音近「弗洛尔」，弗洛尔扫 floor 地板。',
    'plant': 'plant 音近「普兰特」，普兰特浇 plant 植物。',
    'sock': 'sock 音近「索克」，索克穿 sock 短袜。',
    'think': 'think 音近「辛克」，辛克 think 想一想。',
    'water': 'water 音近「沃特」，沃特 water 浇水。',
    'hour': 'hour 音近「阿儿」，阿儿等 hour 一小时。',
    'walk': 'walk 音近「沃克」，沃克 walk 步行。',
    'corn': 'corn 音近「考恩」，考恩吃 corn 玉米。',
    'hope': 'hope 音近「厚普」，厚普 hope 希望。',
    'invite': 'invite 音近「因外特」，因外特 invite 邀请。',
    'join': 'join 音近「卓因」，卓因 join 加入。',
    'luck': 'luck 音近「拉克」，拉克 wish luck 祝好运。',
    'soup': 'soup 音近「苏普」，苏普喝 soup 汤。',
    'because': 'because 音近「比考斯」，比考斯说 because 因为。',
    'earth': 'earth 音近「厄斯」，厄斯 live on earth 住在地球。',
    'evening': 'evening 音近「伊文宁」，伊文宁在 evening 晚上。',
    'moon': 'moon 音近「穆恩」，穆恩看 moon 月亮。',
    'shine': 'shine 音近「晒恩」，晒恩看 shine 发光。',
    'sun': 'sun 音近「桑」，桑看 sun 太阳。',
}

ROOT_MNEMONICS: dict[str, str] = {
    'olympic games': 'Olympic 奥林匹克的 + Games 运动会，Olympic Games 是奥林匹克运动会。',
    'summer olympics': 'Summer 夏季 + Olympics 奥运会，Summer Olympics 是夏季奥运会。',
    'take place': 'take 进行 + place 地方，take place 是举行。',
    'winter olympics': 'Winter 冬季 + Olympics 奥运会，Winter Olympics 是冬季奥运会。',
    'go shopping': 'go 去 + shopping 购物，go shopping 是购物。',
    'try it on': 'try 试 + it on 穿上，try it on 是试穿。',
    'a piece of cake': 'a piece 一块 + cake 蛋糕，a piece of cake 是小菜一碟。',
    'washing machine': 'washing 洗 + machine 机器，washing machine 是洗衣机。',
    'get to school': 'get 到达 + to school 到学校，get to school 是到达学校。',
    'last night': 'last 上一个 + night 夜晚，last night 是昨晚。',
    'help yourselves': 'help 帮助 + yourselves 你们自己，help yourselves 是请自便。',
    'go around': 'go 走 + around 环绕，go around 是绕着……转。',
    'mid-autumn festival': 'Mid 中间 + Autumn 秋 + Festival 节，Mid-Autumn Festival 是中秋节。',
}

IMAGE_MNEMONICS: dict[str, str] = {
    'continent': '想象 world map 上各大 continent 大陆。',
    'dream': '想象 dream 加入 Olympic team 奥运队。',
    'olympic games': '想象 Olympic Games 五环 ring 和 slogan 口号。',
    'ring': '想象 Olympic 五环 five rings。',
    'ball': '想象 catch the ball 双手接球。',
    'candy': '想象 candy 糖果 bad for teeth 对牙不好。',
    'food': '想象 menu 上的 healthy food 健康食物。',
    'teeth': '想象 brush teeth 刷牙 keep 牙齿 clean。',
    'bedroom': '想象 tidy bedroom 整理卧室。',
    'dirty': '想象 dirty socks 脏袜子放进 washing machine。',
    'housework': '想象 do housework 扫地、洗衣、浇 plant。',
    'plant': '想象 water the plant 给植物浇水。',
    'toilet': '想象 clean toilet 打扫卫生间。',
    'washing machine': '想象 dirty clothes 放进 washing machine。',
    'fan': '想象 fan 球迷 cheer 为 team 加油。',
    'seat': '想象 take a seat 在 classroom 里坐下。',
    'thanksgiving': '想象 Thanksgiving 晚餐吃 corn 玉米和 soup 汤。',
    'mid-autumn festival': '想象 Mid-Autumn Festival 晚上看 moon 月亮。',
    'moon': '想象 moon 在 evening 夜空中 shine 发光。',
    'sun': '想象 sun 照耀，earth 绕 sun 转。',
}

SEMANTIC_MNEMONICS: dict[str, str] = {
    'began': 'The games began yesterday. began 是 begin 的过去式，开始了。',
    'game': 'Our team won the game. game 是比赛、游戏。',
    'hold': 'China will hold the games. hold 是举办。',
    'slogan': 'Read the slogan on the poster. slogan 是口号。',
    'something': 'I want something to drink. something 是某事物。',
    'strong': 'He is strong and healthy. strong 是强壮的。',
    'together': 'We cheer together. together 是一起。',
    'always': 'I always exercise. always 是总是。',
    'cry': 'Don\'t cry. cry 是哭、喊叫。',
    'often': 'I often exercise. often 是经常。',
    'sometimes': 'Sometimes we play ball. sometimes 是有时。',
    'their': 'Their team is strong. their 是他们的。',
    'woman': 'The woman is our PE teacher. woman 是妇女。',
    'any': 'Do you have any candy? any 是任何的。',
    'bad': 'Candy is bad for teeth. bad 是坏的。',
    'body': 'Exercise is good for your body. body 是身体。',
    'bring': 'Bring some food. bring 是带来。',
    'keep': 'Brush your teeth to keep them clean. keep 是保持。',
    'usually': 'I usually eat salad. usually 是通常。',
    'clothes': 'Put on clean clothes. clothes 是衣服。',
    'son': 'My son likes this cap. son 是儿子。',
    'those': 'Those socks are dirty. those 是那些。',
    'fan': 'I am a fan of basketball. fan 是迷、爱好者。',
    'half': 'It is half past seven. half 是一半。',
    'last': 'Last week we had a game. last 是上一个。',
    'little': 'The little boy walks to school. little 是小的。',
    'past': 'It is ten past eight. past 是经过、过去。',
    'american': 'Thanksgiving is an American holiday. American 是美国的。',
    'better': 'I hope you feel better. better 是更好的。',
    'yourselves': 'Help yourselves to the food. yourselves 是你们自己。',
    'its': 'The moon has its light. its 是它的。',
    'real': 'Is the story real? real 是真实的。',
}

INFLECTION_NOTES: dict[str, str] = {
    'answer': '第三人称单数 answers；过去式 answered',
    'began': 'begin 的过去式',
    'dream': '第三人称单数 dreams；过去式 dreamed/dreamt',
    'hold': '第三人称单数 holds；过去式 held',
    'strong': '比较级 stronger；最高级 strongest',
    'catch': '第三人称单数 catches；过去式 caught',
    'cheer': '第三人称单数 cheers；过去式 cheered',
    'cry': '第三人称单数 cries；过去式 cried',
    'exercise': '第三人称单数 exercises；过去式 exercised',
    'healthy': '比较级 healthier；最高级 healthiest',
    'pass': '第三人称单数 passes；过去式 passed',
    'woman': '复数 women（不规则变化）',
    'bad': '比较级 worse；最高级 worst',
    'bring': '第三人称单数 brings；过去式 brought',
    'delicious': '比较级 more delicious',
    'keep': '第三人称单数 keeps；过去式 kept',
    'teeth': 'tooth 的复数形式',
    'dress': '第三人称单数 dresses；过去式 dressed',
    'dirty': '比较级 dirtier；最高级 dirtiest',
    'think': '第三人称单数 thinks；过去式 thought',
    'water': '第三人称单数 waters；过去式 watered（作「浇水」讲）',
    'last': '比较级不存在；last night 固定搭配',
    'little': '比较级 less；最高级 least',
    'walk': '第三人称单数 walks；过去式 walked',
    'better': 'good/well 的比较级',
    'hope': '第三人称单数 hopes；过去式 hoped',
    'invite': '第三人称单数 invites；过去式 invited',
    'join': '第三人称单数 joins；过去式 joined',
    'real': '比较级 realer/more real；最高级 realest/most real',
    'shine': '第三人称单数 shines；过去式 shone',
    'go': '第三人称单数 goes；过去式 went（短语 go shopping / go around 同理）',
    'take': '第三人称单数 takes；过去式 took（take place 同理）',
    'try': '第三人称单数 tries；过去式 tried（try it on 同理）',
}

DEFINITION_OVERRIDES: dict[str, str] = {
    'answer': '回答',
    'began': '开始（过去式）',
    'continent': '大陆；洲',
    'dream': '梦想',
    'game': '游戏；比赛',
    'hold': '举办',
    'Olympic Games': '奥林匹克运动会',
    'ring': '环',
    'slogan': '口号',
    'something': '某事物',
    'strong': '强壮的',
    'Summer Olympics': '夏季奥运会',
    'take place': '举行',
    'together': '一起',
    'Winter Olympics': '冬季奥运会',
    'world': '世界',
    'always': '总是',
    'ball': '球',
    'between': '在……（两者）之间',
    'catch': '接住',
    'cheer': '欢呼',
    'cry': '喊叫',
    'exercise': '锻炼',
    'healthy': '健康的',
    'often': '经常',
    'pass': '传递',
    'sometimes': '有时',
    'team': '（体育的）队',
    'their': '他们的',
    'woman': '妇女',
    'any': '任何的；任何一个',
    'bad': '坏的',
    'basket': '篮；筐',
    'body': '身体',
    'bring': '带来',
    'candy': '糖果',
    'delicious': '美味的',
    'food': '食物',
    'glass': '玻璃杯',
    'keep': '保持',
    'menu': '菜单',
    'problem': '问题',
    'salad': '色拉',
    'teeth': '牙齿（复数）',
    'usually': '通常；常常',
    'boring': '乏味的；令人厌烦的',
    'cap': '帽子',
    'clothes': '衣服',
    'daughter': '女儿',
    'dress': '女式连衣裙',
    'go shopping': '购物',
    'pair': '一双；一对',
    'shorts': '短裤',
    'son': '儿子',
    'trousers': '裤子',
    'try it on': '试穿',
    'a piece of cake': '小菜一碟；容易的事',
    'bedroom': '卧室',
    'box': '盒子',
    'dirty': '脏的',
    'floor': '地板',
    'housework': '家务',
    'plant': '植物',
    'sock': '短袜',
    'think': '想',
    'those': '那些',
    'toilet': '卫生间',
    'washing machine': '洗衣机',
    'water': '浇水',
    'fan': '迷；爱好者',
    'get to school': '到达学校',
    'half': '半；一半',
    'hour': '小时',
    'last': '上一个；刚过去的',
    'last night': '昨晚',
    'little': '小的',
    'past': '经过；过去',
    'seat': '座位',
    'walk': '步行',
    'American': '美国的；美国人',
    'better': '更好的',
    'corn': '玉米',
    'help yourselves': '请自便',
    'hope': '希望',
    'invite': '邀请',
    'join': '参加；加入',
    'luck': '运气',
    'soup': '汤',
    'Thanksgiving': '感恩节',
    'yourselves': '你们自己',
    'because': '因为',
    'earth': '地球',
    'evening': '晚上',
    'go around': '绕着……转',
    'its': '它的',
    'Mid-Autumn Festival': '中秋节',
    'moon': '月亮',
    'real': '真实的',
    'shine': '发光；照耀',
    'sun': '太阳',
}

POS_OVERRIDES: dict[str, str] = {
    'answer': 'v./n.',
    'began': 'v.',
    'continent': 'n.',
    'dream': 'n./v.',
    'game': 'n.',
    'hold': 'v.',
    'Olympic Games': 'n.',
    'ring': 'n.',
    'slogan': 'n.',
    'something': 'pron.',
    'strong': 'adj.',
    'Summer Olympics': 'n.',
    'take place': 'v. phr.',
    'together': 'adv.',
    'Winter Olympics': 'n.',
    'world': 'n.',
    'always': 'adv.',
    'ball': 'n.',
    'between': 'prep.',
    'catch': 'v.',
    'cheer': 'v./n.',
    'cry': 'v.',
    'exercise': 'n./v.',
    'healthy': 'adj.',
    'often': 'adv.',
    'pass': 'v.',
    'sometimes': 'adv.',
    'team': 'n.',
    'their': 'det.',
    'woman': 'n.',
    'any': 'det./pron.',
    'bad': 'adj.',
    'basket': 'n.',
    'body': 'n.',
    'bring': 'v.',
    'candy': 'n.',
    'delicious': 'adj.',
    'food': 'n.',
    'glass': 'n.',
    'keep': 'v.',
    'menu': 'n.',
    'problem': 'n.',
    'salad': 'n.',
    'teeth': 'n.',
    'usually': 'adv.',
    'boring': 'adj.',
    'cap': 'n.',
    'clothes': 'n.',
    'daughter': 'n.',
    'dress': 'n.',
    'go shopping': 'v. phr.',
    'pair': 'n.',
    'shorts': 'n.',
    'son': 'n.',
    'trousers': 'n.',
    'try it on': 'v. phr.',
    'a piece of cake': 'n. phr.',
    'bedroom': 'n.',
    'box': 'n.',
    'dirty': 'adj.',
    'floor': 'n.',
    'housework': 'n.',
    'plant': 'n./v.',
    'sock': 'n.',
    'think': 'v.',
    'those': 'det./pron.',
    'toilet': 'n.',
    'washing machine': 'n.',
    'water': 'v./n.',
    'fan': 'n.',
    'get to school': 'v. phr.',
    'half': 'n./det.',
    'hour': 'n.',
    'last': 'adj./adv.',
    'last night': 'n.',
    'little': 'adj./det.',
    'past': 'prep./n.',
    'seat': 'n.',
    'walk': 'v./n.',
    'American': 'adj./n.',
    'better': 'adj./adv.',
    'corn': 'n.',
    'help yourselves': 'v. phr.',
    'hope': 'v./n.',
    'invite': 'v.',
    'join': 'v.',
    'luck': 'n.',
    'soup': 'n.',
    'Thanksgiving': 'n.',
    'yourselves': 'pron.',
    'because': 'conj.',
    'earth': 'n.',
    'evening': 'n.',
    'go around': 'v. phr.',
    'its': 'det.',
    'Mid-Autumn Festival': 'n.',
    'moon': 'n.',
    'real': 'adj.',
    'shine': 'v.',
    'sun': 'n.',
}

IPA_OVERRIDES: dict[str, str] = {
    'answer': '/ˈɑːnsə(r)/',
    'began': '/bɪˈɡæn/',
    'continent': '/ˈkɒntɪnənt/',
    'dream': '/driːm/',
    'game': '/ɡeɪm/',
    'hold': '/həʊld/',
    'Olympic Games': '/əˌlɪmpɪk ˈɡeɪmz/',
    'ring': '/rɪŋ/',
    'slogan': '/ˈsləʊɡən/',
    'something': '/ˈsʌmθɪŋ/',
    'strong': '/strɒŋ/',
    'Summer Olympics': '/ˌsʌmə əˈlɪmpɪks/',
    'take place': '/teɪk pleɪs/',
    'together': '/təˈɡeðə(r)/',
    'Winter Olympics': '/ˌwɪntə əˈlɪmpɪks/',
    'world': '/wɜːld/',
    'always': '/ˈɔːlweɪz, ˈɔːlwəz/',
    'ball': '/bɔːl/',
    'between': '/bɪˈtwiːn/',
    'catch': '/kætʃ/',
    'cheer': '/tʃɪə(r)/',
    'cry': '/kraɪ/',
    'exercise': '/ˈeksəsaɪz/',
    'healthy': '/ˈhelθi/',
    'often': '/ˈɒfn, ˈɒftən/',
    'pass': '/pɑːs/',
    'sometimes': '/ˈsʌmtaɪmz/',
    'team': '/tiːm/',
    'their': '/ðeə(r), ðeə(r)/',
    'woman': '/ˈwʊmən/',
    'any': '/ˈeni/',
    'bad': '/bæd/',
    'basket': '/ˈbɑːskɪt/',
    'body': '/ˈbɒdi/',
    'bring': '/brɪŋ/',
    'candy': '/ˈkændi/',
    'delicious': '/dɪˈlɪʃəs/',
    'food': '/fuːd/',
    'glass': '/ɡlɑːs/',
    'keep': '/kiːp/',
    'menu': '/ˈmenjuː/',
    'problem': '/ˈprɒbləm/',
    'salad': '/ˈsæləd/',
    'teeth': '/tiːθ/',
    'usually': '/ˈjuːʒuəli, ˈjuːʒəli/',
    'boring': '/ˈbɔːrɪŋ/',
    'cap': '/kæp/',
    'clothes': '/kləʊðz, kləʊz/',
    'daughter': '/ˈdɔːtə(r)/',
    'dress': '/dres/',
    'go shopping': '/ɡəʊ ˈʃɒpɪŋ/',
    'pair': '/peə(r)/',
    'shorts': '/ʃɔːts/',
    'son': '/sʌn/',
    'trousers': '/ˈtraʊzəz/',
    'try it on': '/traɪ ɪt ɒn/',
    'a piece of cake': '/ə piːs əv keɪk/',
    'bedroom': '/ˈbedruːm/',
    'box': '/bɒks/',
    'dirty': '/ˈdɜːti/',
    'floor': '/flɔː(r)/',
    'housework': '/ˈhaʊswɜːk/',
    'plant': '/plɑːnt/',
    'sock': '/sɒk/',
    'think': '/θɪŋk/',
    'those': '/ðəʊz/',
    'toilet': '/ˈtɔɪlət/',
    'washing machine': '/ˈwɒʃɪŋ məˈʃiːn/',
    'water': '/ˈwɔːtə(r)/',
    'fan': '/fæn/',
    'get to school': '/ɡet tuː skuːl, ɡet tə skuːl/',
    'half': '/hɑːf, hæf/',
    'hour': '/ˈaʊə(r)/',
    'last': '/lɑːst, læst/',
    'last night': '/lɑːst naɪt, læst naɪt/',
    'little': '/ˈlɪtl/',
    'past': '/pɑːst/',
    'seat': '/siːt/',
    'walk': '/wɔːk/',
    'American': '/əˈmerɪkən/',
    'better': '/ˈbetə(r)/',
    'corn': '/kɔːn/',
    'help yourselves': '/help jɔːˈselvz/',
    'hope': '/həʊp/',
    'invite': '/ɪnˈvaɪt/',
    'join': '/dʒɔɪn/',
    'luck': '/lʌk/',
    'soup': '/suːp/',
    'Thanksgiving': '/ˌθæŋksˈɡɪvɪŋ/',
    'yourselves': '/jɔːˈselvz/',
    'because': '/bɪˈkɒz, bɪˈkəz/',
    'earth': '/ɜːθ/',
    'evening': '/ˈiːvnɪŋ/',
    'go around': '/ɡəʊ əˈraʊnd/',
    'its': '/ɪts/',
    'Mid-Autumn Festival': '/ˌmɪd ˈɔːtəm ˈfestɪvl/',
    'moon': '/muːn/',
    'real': '/rɪəl, rɪəl/',
    'shine': '/ʃaɪn/',
    'sun': '/sʌn/',
}


def _secondary_mnemonic(key: str, headword: str, definition_zh: str, *, kind: str) -> str | None:
    if key in ROOT_MNEMONICS:
        return f'拆词联想：{ROOT_MNEMONICS[key]}'
    if key in IMAGE_MNEMONICS:
        return f'形象联想：{IMAGE_MNEMONICS[key]}'
    if key in SEMANTIC_MNEMONICS:
        return f'语义联想：{SEMANTIC_MNEMONICS[key]}'

    short = definition_zh.split('；')[0].split('，')[0].strip()
    if kind == 'phrase':
        return f'语义联想：把「{short}」和短语 {headword} 配对记忆。'

    adjectives = {
        'bad', 'better', 'boring', 'delicious', 'dirty', 'healthy', 'little',
        'real', 'strong',
    }
    if key in adjectives:
        return f'语义联想：看到「{short}」的事物时，就想到 {headword}。'
    return f'语义联想：把「{short}」和英文 {headword} 配对记忆。'


def mnemonic_for(headword: str, definition_zh: str, *, kind: str) -> str:
    key = headword.lower()
    parts: list[str] = []

    if key in SOUND_MNEMONICS:
        parts.append(f'谐音联想：{SOUND_MNEMONICS[key]}')

    secondary = _secondary_mnemonic(key, headword, definition_zh, kind=kind)
    if secondary:
        if parts:
            if secondary not in parts[0]:
                parts.append(secondary)
        else:
            parts.append(secondary)

    return parts[0] if len(parts) == 1 else '\n'.join(parts)
