"""V1-style mnemonics for grade 3 vol 2 — strict homophone rules."""

from __future__ import annotations

# 谐音联想：仅保留 headword 本身与中文读音确有相似之处的项；宁可空缺也不硬凑。
SOUND_MNEMONICS: dict[str, str] = {
    'see': 'see 读起来接近「西/si」，I see birds 我看见鸟。',
    'he': 'he 读起来接近「嘿/hi」，He is from Canada 他来自加拿大。',
    'she': 'she 读起来接近「嘘/she」，She is very nice 她非常友好。',
    'who': 'who 读起来接近「胡/hu」，Who is that girl 那个女孩是谁。',
}

ROOT_MNEMONICS: dict[str, str] = {
    'classmate': 'class 班级 + mate 伙伴，classmate 就是同班同学。',
    'breakfast': 'break 打破 + fast 禁食，打破一夜禁食就是 breakfast 早餐。',
    'piggy bank': 'piggy 小猪 + bank 银行/储蓄，piggy bank 是猪形储钱罐。',
    'in class': 'in 在 + class 课堂，in class 就是在课堂上。',
    'colourful': 'colour 颜色 + ful，colourful 就是五彩缤纷的。',
    'classroom': 'class 课 + room 房间，classroom 是教室。',
}

IMAGE_MNEMONICS: dict[str, str] = {
    'bag': '想象背着 school bag 去上学，bag 就是包。',
    'book': '想象翻开 book 读书，book 就是书。',
    'bread': '想象早餐盘里的 bread 面包。',
    'egg': '想象 bread and eggs 里的 egg 鸡蛋。',
    'ball': '想象 under the ball 下面的 ball 球。',
    'doll': '想象 shelf 上的 doll 玩偶。',
    'box': '想象 It is in the box，东西在盒子里。',
    'map': '想象 Where is my map? 找地图。',
    'nose': '想象 I smell with my nose，用鼻子闻。',
    'tongue': '想象 I taste with my tongue，用舌头尝。',
}

SEMANTIC_MNEMONICS: dict[str, str] = {
    'where': 'Where are you from? 问来自哪里，where 就是在哪里。',
    'from': 'I am from the UK. 我来自英国，from 表示来自。',
    'about': 'about 可以表示大约，也可以表示关于某事。',
    'today': 'We have two new friends today. today 就是今天。',
    'teacher': 'Miss White is my English teacher. teacher 是教师。',
    'student': 'I am a student. 在学校学习的人是 student。',
    'after': 'After you! 您先请，after 表示在……后面。',
    'who': 'Who is that girl? 问「谁」，who 就是谁。',
    'girl': 'The girl is my neighbour. girl 是女孩。',
    'neighbour': 'That is our new neighbour, Amy. neighbour 是邻居。',
    'boy': 'The boy is my neighbour. boy 是男孩。',
    'woman': 'The woman is my neighbour. woman 是成年女子。',
    'man': 'The man is my neighbour. man 是成年男子。',
    'mr': 'Mr 放在男士姓氏前，表示先生。',
    'classmate': 'Mike is my classmate. 同班同学一起上课。',
    'he': 'He is from Canada. he 指男孩或男士，意思是「他」。',
    'english': 'English teacher 英语老师，English 表示英语。',
    'she': 'She is very nice. she 指女孩或女士，意思是「她」。',
    'very': 'She is very nice. very 表示很、非常。',
    'uk': 'I am from the UK. UK 是英国。',
    'china': 'I am from Shandong, China. China 是中国。',
    'canada': 'He is from Canada. Canada 是加拿大。',
    'usa': 'Students from the USA. USA 是美国。',
    'has': 'It has a long body. has 表示具有某种特征。',
    'long': 'a long body 长长的身体，long 是长的。',
    'short': 'short legs 短短的腿，short 是短的。',
    'body': 'It has a long body and short legs. body 是身体。',
    'leg': 'short legs 短短的腿，leg 是腿。',
    'fat': 'fat 表示胖的，和 thin 是一对反义词。',
    'thin': 'The dog is thin. thin 表示瘦的。',
    'slow': 'slow 表示慢的，想象乌龟走得很 slow。',
    'love': 'I love my dog. love 是喜爱。',
    'tail': 'tail 是尾巴，狗摇 tail。',
    'her': 'I often make her gifts. her 表示她、她的。',
    'gift': 'I often make her gifts. gift 是礼物。',
    'picture': 'Draw a picture. picture 是图画。',
    'card': 'Make a card. card 是卡片。',
    'sing': 'Sing a song. sing 是唱歌。',
    'dance': 'Dance together. dance 是跳舞。',
    'face': 'Our face can talk. face 是脸。',
    'all': 'We express ourselves in many ways. all 表示全部。',
    'so': 'A smile can say so much! so 表示这么、那么。',
    'talk': 'We talk to express ourselves. talk 是说话。',
    'song': 'Sing a song. song 是歌曲。',
    'or': 'A or B 二选一，or 是或者。',
    'much': 'so much 这么多，much 是许多。',
    'eraser': 'Can I use your eraser? eraser 是橡皮。',
    'pen': 'Can you find my pen? pen 是钢笔。',
    'find': 'find 是找到、找回。',
    'ruler': 'Can I use your ruler? ruler 是直尺。',
    'pencil': 'I can use pencils to learn. pencil 是铅笔。',
    'paper': 'I can use paper to learn. paper 是纸。',
    'these': 'What are these? these 是这些。',
    'see': 'I see birds. see 是看见。',
    'smell': 'I smell flowers. smell 是用鼻子闻。',
    'taste': 'I taste an apple. taste 是用舌头尝。',
    'hear': 'I hear birds. hear 是听见。',
    'touch': 'I touch the grass. touch 是触摸。',
    'learn': 'We learn in class. learn 是学习。',
    'class': 'in class 在课堂上，class 也是班级。',
    'computer': 'books and computers help me learn. computer 是电脑。',
    'breakfast': 'It is time for breakfast. breakfast 是早餐。',
    'time': 'It is time for breakfast. time 是时间。',
    'milk': 'Have some milk too. milk 是牛奶。',
    'rice': 'rice and meat 米饭和肉，rice 是大米。',
    'meat': 'Would you like some rice and meat? meat 是肉。',
    'noodle': 'Would you like some noodles? noodle 是面条。',
    'juice': 'Have some juice. juice 是果汁。',
    'vegetable': 'Eat some vegetables every day. vegetable 是蔬菜。',
    'healthy': 'This is my healthy plate. healthy 是健康的。',
    'plate': 'This is my healthy plate. plate 是盘子。',
    'soup': 'Water, soup, milk and juice. soup 是汤。',
    'fruit': 'Fruit and vegetables are healthy. fruit 是水果。',
    'candy': 'Candy is yummy. candy 是糖果。',
    'yummy': 'Candy and cake are yummy. yummy 是很好吃的。',
    'at': 'at home 在家，at 表示在（某处）。',
    'boat': 'This boat is cool. boat 是小船。',
    'cool': 'This boat is cool. cool 表示酷、很棒。',
    'keep': 'You can keep it. keep 是留着。',
    'home': 'Do you have old things at home? home 是家。',
    'car': 'I have some old cars. car 是小汽车。',
    'on': 'on the shelf 在架子上，on 表示在……上。',
    'shelf': 'Is it on the shelf? shelf 是架子。',
    'in': 'It is in the box. in 表示在……里面。',
    'under': 'It is under the box. under 是在……下面。',
    'still': 'They are still good. still 表示仍然。',
    'put': 'Put your books on the shelf. put 是放。',
    'cap': 'Where is my cap? cap 是帽子。',
    'pay': 'How much is this bag? pay 是付费。',
    'back': 'Come back! back 是回来。',
    'right': 'That is right. right 在这里表示对的、正确的。',
    'after': 'After you! 您先请。',
    'eleven': 'eleven 是十一，特殊拼写要记。',
    'twelve': 'twelve 是十二，特殊拼写要记。',
    'thirteen': 'thirteen 是十三，thir + teen。',
    'fourteen': 'fourteen 是十四，four + teen。',
    'fifteen': 'fifteen 是十五，We have fifteen books.',
    'sixteen': 'sixteen 是十六，six + teen。',
    'seventeen': 'seventeen 是十七，seven + teen。',
    'eighteen': 'eighteen 是十八，eight + teen。',
    'nineteen': 'nineteen 是十九，nine + teen。',
    'twenty': 'twenty 是二十，two + ty。',
}


DEFINITION_OVERRIDES: dict[str, str] = {
    'where': '在哪里；到哪里',
    'from': '（表示来源）来自，从……来',
    'about': '大约；左右',
    'today': '今天',
    'teacher': '教师',
    'student': '学生',
    'after': '在……后面',
    'who': '谁；什么人',
    'girl': '女孩',
    'neighbour': '邻居',
    'boy': '男孩',
    'woman': '成年女子；妇女',
    'man': '成年男子；男人',
    'Mr': '（用于男子的姓氏或姓名前）先生',
    'classmate': '同班同学',
    'he': '他',
    'English': '英语的；英语',
    'she': '她',
    'very': '很；非常；十分',
    'UK': '英国',
    'China': '中国',
    'Canada': '加拿大',
    'USA': '美国',
    'has': '（have的第三人称单数形式）具有（某种外表、特性或特征）',
    'long': '（长度或距离）长的',
    'body': '身体',
    'short': '短的；个子矮的',
    'leg': '腿',
    'right': '（意见或判断）准确，确切，恰当',
    'fat': '肥的；肥胖的',
    'thin': '瘦的',
    'slow': '缓慢的；慢的',
    'love': '喜爱；爱',
    'tail': '尾；尾巴',
    'her': '她；她的',
    'gift': '礼物',
    'picture': '图画；绘画',
    'card': '贺卡；慰问卡；卡片',
    'sing': '唱（歌）；演唱',
    'dance': '跳舞',
    'face': '脸；面孔',
    'all': '所有；全部',
    'so': '（表示大小或数量）这么，那么',
    'talk': '（用某种语言）讲，说；说话',
    'song': '歌；歌曲',
    'or': '或；或者；还是',
    'much': '许多；大量',
    'eraser': '橡皮',
    'find': '找到；找回',
    'ruler': '直尺',
    'pen': '钢笔',
    'pencil': '铅笔',
    'book': '书；书籍',
    'bag': '包；袋',
    'paper': '纸',
    'these': '这些',
    'see': '看见',
    'smell': '闻（气味）',
    'taste': '尝（味道）',
    'hear': '听见；听到',
    'touch': '触摸；碰',
    'learn': '学；学习',
    'nose': '鼻；鼻子',
    'tongue': '舌；舌头',
    'class': '课；班级',
    'in class': '在课堂上',
    'computer': '计算机；电脑',
    'breakfast': '早餐；早饭',
    'time': '时间',
    'bread': '面包',
    'egg': '（作食物用的）蛋；鸡蛋',
    'milk': '（牛或羊等的）奶',
    'noodle': '（常用复数）面条',
    'juice': '果汁',
    'rice': '大米',
    'meat': '肉',
    'vegetable': '蔬菜',
    'healthy': '健康的',
    'plate': '盘子',
    'soup': '汤',
    'fruit': '水果',
    'colourful': '五彩缤纷的',
    'candy': '糖果',
    'yummy': '很好吃的',
    'at': '在（某处）',
    'boat': '小船；舟',
    'cool': '（因时髦、漂亮且与众不同而）酷的，绝妙的',
    'keep': '保有；留着',
    'home': '家；住所',
    'ball': '球',
    'doll': '玩偶；玩具娃娃',
    'car': '小汽车；轿车',
    'on': '（覆盖、附着）在……上',
    'shelf': '（复数shelves/ʃelvz/）架子',
    'in': '在……内；在……中',
    'box': '盒子',
    'cap': '帽子',
    'map': '地图',
    'under': '在（或到、通过）……下面',
    'still': '还是；仍然',
    'put': '放；安置',
    'fifteen': '十五',
    'twelve': '十二',
    'fourteen': '十四',
    'thirteen': '十三',
    'eleven': '十一',
    'twenty': '二十',
    'seventeen': '十七',
    'sixteen': '十六',
    'eighteen': '十八',
    'nineteen': '十九',
    'piggy bank': '猪形储钱罐',
    'pay': '付费',
    'back': '回到原处',
}

IPA_OVERRIDES: dict[str, str] = {
    'where': '/weə(r)/',
    'from': '/frɒm/',
    'about': '/əˈbaʊt/',
    'today': '/təˈdeɪ/',
    'teacher': '/ˈtiːtʃə(r)/',
    'student': '/ˈstjuːdnt/',
    'after': '/ˈɑːftə(r)/',
    'who': '/huː/',
    'girl': '/ɡɜːl/',
    'neighbour': '/ˈneɪbə(r)/',
    'boy': '/bɔɪ/',
    'woman': '/ˈwʊmən/',
    'man': '/mæn/',
    'mr': '/ˈmɪstə(r)/',
    'classmate': '/ˈklɑːsmeɪt/',
    'he': '/hiː/',
    'english': '/ˈɪŋɡlɪʃ/',
    'she': '/ʃiː/',
    'very': '/ˈveri/',
    'uk': '/ˌjuː ˈkeɪ/',
    'china': '/ˈtʃaɪnə/',
    'canada': '/ˈkænədə/',
    'usa': '/ˌjuː es ˈeɪ/',
    'has': '/hæz/',
    'long': '/lɒŋ/',
    'body': '/ˈbɒdi/',
    'short': '/ʃɔːt/',
    'leg': '/leɡ/',
    'right': '/raɪt/',
    'fat': '/fæt/',
    'thin': '/θɪn/',
    'slow': '/sləʊ/',
    'love': '/lʌv/',
    'tail': '/teɪl/',
    'her': '/hɜː(r)/',
    'gift': '/ɡɪft/',
    'picture': '/ˈpɪktʃə(r)/',
    'card': '/kɑːd/',
    'sing': '/sɪŋ/',
    'dance': '/dɑːns/',
    'face': '/feɪs/',
    'all': '/ɔːl/',
    'so': '/səʊ/',
    'talk': '/tɔːk/',
    'song': '/sɒŋ/',
    'or': '/ɔː(r)/',
    'much': '/mʌtʃ/',
    'eraser': '/ɪˈreɪzə(r)/',
    'find': '/faɪnd/',
    'ruler': '/ˈruːlə(r)/',
    'pen': '/pen/',
    'pencil': '/ˈpensl/',
    'book': '/bʊk/',
    'bag': '/bæɡ/',
    'paper': '/ˈpeɪpə(r)/',
    'these': '/ðiːz/',
    'see': '/siː/',
    'smell': '/smel/',
    'taste': '/teɪst/',
    'hear': '/hɪə(r)/',
    'touch': '/tʌtʃ/',
    'learn': '/lɜːn/',
    'nose': '/nəʊz/',
    'tongue': '/tʌŋ/',
    'class': '/klɑːs/',
    'in class': '/ɪn klɑːs/',
    'computer': '/kəmˈpjuːtə(r)/',
    'breakfast': '/ˈbrekfəst/',
    'time': '/taɪm/',
    'bread': '/bred/',
    'egg': '/eɡ/',
    'milk': '/mɪlk/',
    'noodle': '/ˈnuːdl/',
    'juice': '/dʒuːs/',
    'rice': '/raɪs/',
    'meat': '/miːt/',
    'vegetable': '/ˈvedʒtəbl/',
    'healthy': '/ˈhelθi/',
    'plate': '/pleɪt/',
    'soup': '/suːp/',
    'fruit': '/fruːt/',
    'colourful': '/ˈkʌləfl/',
    'candy': '/ˈkændi/',
    'yummy': '/ˈjʌmi/',
    'at': '/æt/',
    'boat': '/bəʊt/',
    'cool': '/kuːl/',
    'keep': '/kiːp/',
    'home': '/həʊm/',
    'ball': '/bɔːl/',
    'doll': '/dɒl/',
    'car': '/kɑː(r)/',
    'on': '/ɒn/',
    'shelf': '/ʃelf/',
    'in': '/ɪn/',
    'box': '/bɒks/',
    'cap': '/kæp/',
    'map': '/mæp/',
    'under': '/ˈʌndə(r)/',
    'still': '/stɪl/',
    'put': '/pʊt/',
    'fifteen': '/ˌfɪfˈtiːn/',
    'twelve': '/twelv/',
    'fourteen': '/ˌfɔːˈtiːn/',
    'thirteen': '/ˌθɜːˈtiːn/',
    'eleven': '/ɪˈlevn/',
    'twenty': '/ˈtwenti/',
    'seventeen': '/ˌsevnˈtiːn/',
    'sixteen': '/ˌsɪksˈtiːn/',
    'eighteen': '/ˌeɪˈtiːn/',
    'nineteen': '/ˌnaɪnˈtiːn/',
    'piggy bank': '/ˈpɪɡi bæŋk/',
    'pay': '/peɪ/',
    'back': '/bæk/',
}

POS_OVERRIDES: dict[str, str] = {
    'mr': 'n.',
    'uk': 'n.',
    'china': 'n.',
    'canada': 'n.',
    'usa': 'n.',
    'english': 'adj.',
    'in class': 'prep. phrase',
    'piggy bank': 'n.',
}

INFLECTION_NOTES: dict[str, str] = {
    # 名词复数
    'teacher': '复数 teachers',
    'student': '复数 students',
    'girl': '复数 girls',
    'neighbour': '复数 neighbours',
    'boy': '复数 boys',
    'woman': '复数 women',
    'man': '复数 men',
    'classmate': '复数 classmates',
    'body': '复数 bodies',
    'leg': '复数 legs',
    'tail': '复数 tails',
    'gift': '复数 gifts',
    'picture': '复数 pictures',
    'card': '复数 cards',
    'song': '复数 songs',
    'face': '复数 faces',
    'eraser': '复数 erasers',
    'ruler': '复数 rulers',
    'pen': '复数 pens',
    'pencil': '复数 pencils',
    'book': '复数 books',
    'bag': '复数 bags',
    'nose': '复数 noses',
    'class': '复数 classes',
    'computer': '复数 computers',
    'plate': '复数 plates',
    'vegetable': '复数 vegetables',
    'boat': '复数 boats',
    'ball': '复数 balls',
    'doll': '复数 dolls',
    'car': '复数 cars',
    'box': '复数 boxes',
    'cap': '复数 caps',
    'map': '复数 maps',
    'shelf': '复数 shelves',
    'piggy bank': '复数 piggy banks',
    'noodle': '常用复数 noodles',
    # 动词
    'has': '第三人称单数 have',
    'love': '第三人称单数 loves',
    'sing': '过去式 sang；第三人称单数 sings',
    'dance': '第三人称单数 dances',
    'talk': '第三人称单数 talks',
    'find': '过去式 found；第三人称单数 finds',
    'see': '第三人称单数 sees',
    'smell': '第三人称单数 smells',
    'taste': '第三人称单数 tastes',
    'hear': '第三人称单数 hears',
    'touch': '第三人称单数 touches',
    'learn': '第三人称单数 learns',
    'keep': '第三人称单数 keeps',
    'put': '过去式 put（拼写不变）；第三人称单数 puts',
    'pay': '过去式 paid；第三人称单数 pays',
}


def _secondary_mnemonic(key: str, headword: str, definition_zh: str, *, kind: str) -> str | None:
    if key in ROOT_MNEMONICS:
        return f'拆词联想：{ROOT_MNEMONICS[key]}'
    if key in IMAGE_MNEMONICS:
        return f'形象联想：{IMAGE_MNEMONICS[key]}'
    if key in SEMANTIC_MNEMONICS:
        return f'语义联想：{SEMANTIC_MNEMONICS[key]}'

    short = definition_zh.split('；')[0].split('，')[0]
    if kind == 'phrase':
        return f'语义联想：把「{short}」和短语 {headword} 配对记忆。'

    number_words = {
        'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen',
        'seventeen', 'eighteen', 'nineteen', 'twenty',
    }
    adjectives = {
        'long', 'short', 'fat', 'thin', 'slow', 'healthy', 'yummy', 'colourful', 'cool', 'right',
    }
    if key in number_words:
        return f'形象联想：想象 {short} 个数字 {headword}，边数边记住它。'
    if key in adjectives:
        return f'语义联想：看到「{short}」的事物时，就想到 {headword}。'
    return f'语义联想：把「{short}」和英文 {headword} 配对记忆。'


def mnemonic_for(headword: str, definition_zh: str, *, kind: str) -> str:
    key = headword.lower()
    parts: list[str] = []

    if key in SOUND_MNEMONICS:
        parts.append(f'谐音联想：{SOUND_MNEMONICS[key]}')

    secondary = _secondary_mnemonic(key, headword, definition_zh, kind=kind)
    if secondary:
        # 已有谐音时，第二条用其他类型；没有谐音时，第二条省略（只保留一条）
        if parts:
            # 避免重复类型前缀
            if secondary not in parts[0]:
                parts.append(secondary)
        else:
            parts.append(secondary)

    return parts[0] if len(parts) == 1 else '\n'.join(parts)
