"""Mnemonics and inflection notes for 闽教版 Grade 4 English, Volume 2 (下册).

谐音规则：仅真实谐音，不硬凑；优先语义/形象/拆词联想。
"""

from __future__ import annotations

SOUND_MNEMONICS: dict[str, str] = {
    'chess': 'chess 音近「切斯」，切斯下 chess 国际象棋。',
    'door': 'door 音近「多」，多问一句 door 门在哪。',
    'film': 'film 音近「菲尔姆」，菲尔姆看 film 电影。',
    'foot': 'foot 音近「福特」，福特的 foot 脚走路。',
    'fox': 'fox 音近「福克斯」，福克斯是 fox 狐狸。',
    'hooray': 'hooray 音近「呼瑞」，呼瑞喊 hooray 好哇。',
    'math': 'math 音近「马斯」，马斯学 math 数学。',
    'must': 'must 音近「马斯特」，马斯特 must 必须做。',
    'near': 'near 音近「尼尔」，尼尔住 near 附近。',
    'piano': 'piano 音近「皮安诺」，皮安诺弹 piano 钢琴。',
    'picnic': 'picnic 音近「皮克尼克」，皮克尼克去 picnic 野餐。',
    'poem': 'poem 音近「剖姆」，剖姆读 poem 诗。',
    'robot': 'robot 音近「柔伯特」，柔伯特是 robot 机器人。',
    'sad': 'sad 音近「赛的」，赛的 feel sad 感到悲伤。',
    'ship': 'ship 音近「希普」，希普坐 ship 船。',
    'sit': 'sit 音近「西特」，西特 sit 坐下。',
    'story': 'story 音近「斯托瑞」，斯托瑞讲 story 故事。',
    'subway': 'subway 音近「萨布威」，萨布威坐 subway 地铁。',
    'swan': 'swan 音近「斯旺」，斯旺是 swan 天鹅。',
    'take': 'take 音近「泰克」，泰克 take 带走。',
    'tell': 'tell 音近「泰尔」，泰尔 tell 告诉你。',
    'train': 'train 音近「吹恩」，train 火车吹一声就开。',
    'travel': 'travel 音近「特拉沃尔」，特拉沃尔 travel 旅游。',
    'water': 'water 音近「沃特」，沃特喝 water 水。',
    'week': 'week 音近「喂克」，一周 week 喂饱七天。',
    'why': 'why 音近「外」，外问 why 为什么。',
    'work': 'work 音近「沃克」，沃克去 work 工作。',
}

ROOT_MNEMONICS: dict[str, str] = {
    'activity': 'active 活跃 + ity，activity 是活动。',
    'duckling': 'duck 鸭 + ling 小，duckling 是小鸭。',
    'evening': 'even 平 + ing，evening 是傍晚。',
    'exercise': 'ex 出 + ercise，exercise 是锻炼。',
    'feeling': 'feel 感觉 + ing，feeling 是感觉。',
    'helpful': 'help 帮助 + ful，helpful 是有帮助的。',
    'holiday': 'holi 神圣 + day 日，holiday 是假期、节日。',
    'information': 'inform 通知 + ation，information 是信息。',
    'internet': 'inter 之间 + net 网，internet 是互联网。',
    'lonely': 'lone 独自 + ly，lonely 是孤独的。',
    'nervous': 'nerve 神经 + ous，nervous 是紧张的。',
    'parent': 'par 生 + ent，parent 是父母、家长。',
    'search': 'sea 搜寻 + rch，search 是搜查、搜寻。',
    "i'll=i will": "I 我 + will 将，I'll 就是我将会。",
    'slide show': 'slide 幻灯片 + show 放映，slide show 是幻灯片放映。',
    'subject': 'sub 下 + ject 投，subject 是科目。',
    'subway': 'sub 地下 + way 路，subway 是地铁。',
    'surprise': 'sur 超过 + prise 取，surprise 是惊喜。',
    'thirsty': 'thirst 渴 + y，thirsty 是渴的。',
    'tomorrow': 'to 向 + morrow 明天，tomorrow 是明天。',
    'useful': 'use 用 + ful，useful 是有用的。',
    'weekday': 'week 周 + day 日，weekday 是工作日。',
    'weekend': 'week 周 + end 末，weekend 是周末。',
    'weekly': 'week 周 + ly，weekly 是每周的。',
    'winner': 'win 赢 + ner，winner 是获胜者。',
}

IMAGE_MNEMONICS: dict[str, str] = {
    'angry': '想象 parent duck angry 愤怒地拍翅膀。',
    'chess': '想象黑白棋子在 chess 棋盘上。',
    'duckling': '想象 ugly duckling 小鸭在 farm 里。',
    'farm': '想象 farm 农场里有 duckling 和 swan。',
    'film': '想象 evening 在 sofa 上看 film 电影。',
    'fox': '想象 story 里 clever fox 狐狸。',
    'internet': '想象 internet 电脑屏幕上 search 信息。',
    'office': '想象 dad 在 office 办公室里 work。',
    'picnic': '想象 weekend 在 grass 上 picnic 野餐。',
    'piano': '想象 sit at the piano 弹钢琴。',
    'plane': '想象 plane 飞机飞过 summer 天空。',
    'robot': '想象 classroom 里 helpful robot 机器人。',
    'ship': '想象 ship 大船在 sea 上 travel。',
    'slide show': '想象 classroom 里 slide show 投影。',
    'subway': '想象 take the subway 进地下站。',
    'swan': '想象 ugly duckling 变成 beautiful swan 天鹅。',
    'train': '想象 cheap train 火车 travel 旅行。',
    'weekend': '想象 weekend 不用上学，hooray 好哇！',
}

SEMANTIC_MNEMONICS: dict[str, str] = {
    'activity': 'What is your activity? activity 是活动。',
    'angry': 'Do not be angry. angry 是愤怒的。',
    'away': 'The UK is far away. away 是去别处、离开。',
    'because': 'I like it because it is useful. because 是因为。',
    'better': 'I feel better now. better 是较好的、更好的。',
    'bored': 'I feel bored. bored 是厌倦的、烦闷的。',
    'but': 'I like math, but it is hard. but 是但是。',
    'by': 'Go by subway. by 是通过、以……方式。',
    'cheap': 'The train is cheap. cheap 是便宜的。',
    'count': 'Count from one to ten. count 是数数、计算。',
    'dad': 'My dad goes to work. dad 是爸爸。',
    'does': 'What does he do? does 是 do 的第三人称单数。',
    'enjoy': 'I enjoy the story. enjoy 是欣赏、享受。',
    'every': 'Every week I play piano. every 是每个。',
    'excited': 'I am excited! excited 是激动的。',
    'far': 'The UK is far. far 是遥远的。',
    'feel': 'How do you feel? feel 是感到、觉得。',
    'fifty': 'Count to fifty. fifty 是五十。',
    'fly': 'Birds fly high. fly 是飞、放飞。',
    'forty': 'Dad is forty. forty 是四十。',
    'friday': 'Friday is the last weekday. Friday 是星期五。',
    'high': 'The swan flies high. high 是高的。',
    'him': 'Tell him the story. him 是他（宾格）。',
    'his': 'This is his office. his 是他的。',
    'holiday': 'Summer holiday is coming. holiday 是假期、节日。',
    'kind': 'You are very kind. kind 是体贴的、友好的。',
    'live': 'We live near the subway. live 是生活、居住。',
    'monday': 'We have math on Monday. Monday 是星期一。',
    'must': 'You must sit down. must 是必须。',
    'next': 'Who is next? next 是下一个的。',
    'over': 'The swan flies over the farm. over 是在……上面。',
    'poor': 'The poor duckling is sad. poor 是可怜的、贫穷的。',
    'proud': 'I am proud of you. proud 是自豪的。',
    'sad': 'The duckling feels sad. sad 是悲伤的。',
    'saturday': 'We have a picnic on Saturday. Saturday 是星期六。',
    'science': 'I like science. science 是科学。',
    'sit': 'Please sit down. sit 是坐。',
    'summer': 'We travel in summer. summer 是夏天。',
    'sunday': 'Sunday is the first day. Sunday 是星期日。',
    'thursday': 'We have robot show on Thursday. Thursday 是星期四。',
    'tired': 'I feel tired. tired 是疲倦的。',
    'tuesday': 'We play chess on Tuesday. Tuesday 是星期二。',
    'turn': 'Turn left at the subway. turn 是转动、转弯。',
    'ugly': 'The ugly duckling. ugly 是丑陋的。',
    'useful': 'Science is useful. useful 是有用的。',
    'water': 'I need water. water 是水、浇水。',
    'wednesday': 'We have piano on Wednesday. Wednesday 是星期三。',
    'will': 'I will travel. will 是将、会（将来时）。',
    'worry': "Don't worry. worry 是担心。",
    'zero': 'Zero is a number. zero 是零。',
    'hong kong': 'We travel to Hong Kong. Hong Kong 是香港。',
    'the uk': 'Travel to the UK. the UK 是英国。',
}

INFLECTION_NOTES: dict[str, str] = {
    'activity': '复数 activities',
    'angry': '比较级 angrier；最高级 angriest',
    'better': 'good/well 的比较级',
    'bored': '比较级 more bored',
    'cheap': '比较级 cheaper；最高级 cheapest',
    'count': '第三人称单数 counts',
    'does': 'do 的第三人称单数形式',
    'enjoy': '第三人称单数 enjoys',
    'excited': '动词 excite 的过去分词作形容词',
    'exercise': '第三人称单数 exercises',
    'feel': '第三人称单数 feels；过去式 felt',
    'feeling': '复数 feelings',
    'fly': '第三人称单数 flies；过去式 flew',
    'foot': '复数 feet（不规则变化）',
    'high': '比较级 higher；最高级 highest',
    'live': '第三人称单数 lives',
    'lonely': '比较级 lonelier；最高级 loneliest',
    'parent': '复数 parents',
    'poor': '比较级 poorer；最高级 poorest',
    'sad': '比较级 sadder；最高级 saddest',
    'search': '第三人称单数 searches',
    'sit': '第三人称单数 sits；过去式 sat',
    'story': '复数 stories',
    'surprise': '复数 surprises',
    'take': '第三人称单数 takes；过去式 took',
    'tell': '第三人称单数 tells；过去式 told',
    'thirsty': '比较级 thirstier；最高级 thirstiest',
    'tired': '比较级 more tired',
    'travel': '第三人称单数 travels',
    'turn': '第三人称单数 turns',
    'ugly': '比较级 uglier；最高级 ugliest',
    'useful': '比较级 more useful',
    'water': '第三人称单数 waters（浇水）',
    'winner': '复数 winners',
    'work': '第三人称单数 works',
    'worry': '第三人称单数 worries',
}

DEFINITION_OVERRIDES: dict[str, str] = {
    'Friday': '星期五',
    'Hong Kong': '香港',
    "I'll=I will": '我将会',
    'Monday': '星期一',
    'Saturday': '星期六',
    'Sunday': '星期日',
    'Thursday': '星期四',
    'Tuesday': '星期二',
    'Wednesday': '星期三',
    'activity': '活动',
    'angry': '愤怒的',
    'away': '去别处；离开',
    'because': '因为',
    'better': '较好的；更好的',
    'bored': '厌倦的；烦闷的',
    'but': '但是',
    'by': '通过；以……（方式）',
    'cheap': '便宜的',
    'chess': '国际象棋',
    'count': '数数；计算',
    'dad': '爸爸',
    'does': '做',
    'door': '门',
    'duckling': '小鸭',
    'enjoy': '欣赏；享受',
    'evening': '傍晚',
    'every': '每个',
    'excited': '激动的',
    'exercise': '锻炼',
    'far': '遥远的',
    'farm': '农场',
    'feel': '感到；觉得',
    'feeling': '感觉',
    'fifty': '五十',
    'film': '电影',
    'fly': '飞；放飞',
    'foot': '脚',
    'forty': '四十',
    'fox': '狐狸',
    'helpful': '有帮助的；乐于助人的',
    'high': '高的',
    'him': '他（宾格）',
    'his': '他的',
    'holiday': '假期；节日',
    'hooray': '（表示高兴、赞许等）好哇',
    'information': '信息',
    'internet': '互联网',
    'kind': '体贴的；友好的',
    'live': '生活；居住',
    'lonely': '孤独的；寂寞的',
    'math': '数学',
    'must': '必须',
    'near': '在附近',
    'nervous': '紧张的',
    'next': '下一个的',
    'office': '办公室',
    'over': '在……上面',
    'parent': '父，母；家长',
    'piano': '钢琴',
    'picnic': '野餐',
    'plane': '飞机',
    'poem': '诗',
    'poor': '可怜的；贫穷的',
    'proud': '自豪的',
    'robot': '机器人',
    'sad': '悲伤的',
    'science': '科学',
    'search': '搜查；搜寻',
    'ship': '船',
    'sit': '坐',
    'slide show': '幻灯片放映',
    'story': '故事',
    'subject': '科目',
    'subway': '地铁',
    'summer': '夏天',
    'surprise': '惊喜',
    'swan': '天鹅',
    'take': '带走；拿走；搭乘（交通工具）',
    'tell': '告诉',
    'the UK': '英国',
    'thirsty': '渴的',
    'tired': '疲倦的',
    'tomorrow': '明天',
    'train': '火车',
    'travel': '旅游',
    'turn': '转动；转弯',
    'ugly': '丑陋的',
    'useful': '有用的',
    'water': '水；浇水',
    'week': '星期；周',
    'weekday': '工作日',
    'weekend': '周末',
    'weekly': '每周的',
    'why': '为什么',
    'will': '（构成将来时）将；会',
    'winner': '获胜者',
    'work': '工作',
    'worry': '担心',
    'zero': '零',
}

POS_OVERRIDES: dict[str, str] = {
    'Friday': 'n.',
    'Hong Kong': 'n.',
    "I'll=I will": 'v.',
    'Monday': 'n.',
    'Saturday': 'n.',
    'Sunday': 'n.',
    'Thursday': 'n.',
    'Tuesday': 'n.',
    'Wednesday': 'n.',
    'activity': 'n.',
    'angry': 'adj.',
    'away': 'adv.',
    'because': 'conj.',
    'better': 'adj./adv.',
    'bored': 'adj.',
    'but': 'conj.',
    'by': 'prep./adv.',
    'cheap': 'adj.',
    'chess': 'n.',
    'count': 'v.',
    'dad': 'n.',
    'does': 'v.',
    'door': 'n.',
    'duckling': 'n.',
    'enjoy': 'v.',
    'evening': 'n.',
    'every': 'det.',
    'excited': 'adj.',
    'exercise': 'n./v.',
    'far': 'adj./adv.',
    'farm': 'n.',
    'feel': 'v.',
    'feeling': 'n.',
    'fifty': 'num.',
    'film': 'n.',
    'fly': 'v.',
    'foot': 'n.',
    'forty': 'num.',
    'fox': 'n.',
    'helpful': 'adj.',
    'high': 'adj./adv.',
    'him': 'pron.',
    'his': 'det./pron.',
    'holiday': 'n.',
    'hooray': 'interj.',
    'information': 'n.',
    'internet': 'n.',
    'kind': 'adj.',
    'live': 'v.',
    'lonely': 'adj.',
    'math': 'n.',
    'must': 'v. modal',
    'near': 'adv./prep./adj.',
    'nervous': 'adj.',
    'next': 'adj./adv.',
    'office': 'n.',
    'over': 'prep./adv.',
    'parent': 'n.',
    'piano': 'n.',
    'picnic': 'n./v.',
    'plane': 'n.',
    'poem': 'n.',
    'poor': 'adj.',
    'proud': 'adj.',
    'robot': 'n.',
    'sad': 'adj.',
    'science': 'n.',
    'search': 'v./n.',
    'ship': 'n.',
    'sit': 'v.',
    'slide show': 'n.',
    'story': 'n.',
    'subject': 'n.',
    'subway': 'n.',
    'summer': 'n.',
    'surprise': 'n./v.',
    'swan': 'n.',
    'take': 'v.',
    'tell': 'v.',
    'the UK': 'n.',
    'thirsty': 'adj.',
    'tired': 'adj.',
    'tomorrow': 'adv./n.',
    'train': 'n./v.',
    'travel': 'v./n.',
    'turn': 'v./n.',
    'ugly': 'adj.',
    'useful': 'adj.',
    'water': 'n./v.',
    'week': 'n.',
    'weekday': 'n.',
    'weekend': 'n.',
    'weekly': 'adj./adv.',
    'why': 'adv.',
    'will': 'v. modal',
    'winner': 'n.',
    'work': 'v./n.',
    'worry': 'v./n.',
    'zero': 'num.',
}

IPA_OVERRIDES: dict[str, str] = {
    'Friday': '/ˈfraɪdeɪ/',
    'Hong Kong': '/ˌhɒŋ ˈkɒŋ/',
    "I'll=I will": '/aɪl/',
    'Monday': '/ˈmʌndeɪ/',
    'Saturday': '/ˈsætədeɪ/',
    'Sunday': '/ˈsʌndeɪ/',
    'Thursday': '/ˈθɜːzdeɪ/',
    'Tuesday': '/ˈtjuːzdeɪ, ˈtʃuːzdeɪ/',
    'Wednesday': '/ˈwenzdeɪ/',
    'activity': '/ækˈtɪvəti/',
    'angry': '/ˈæŋɡri/',
    'away': '/əˈweɪ/',
    'because': '/bɪˈkɒz, bɪˈkəz/',
    'better': '/ˈbetə(r)/',
    'bored': '/bɔːd/',
    'but': '/bʌt, bət/',
    'by': '/baɪ/',
    'cheap': '/tʃiːp/',
    'chess': '/tʃes/',
    'count': '/kaʊnt/',
    'dad': '/dæd/',
    'does': '/dʌz, dəz/',
    'door': '/dɔː(r)/',
    'duckling': '/ˈdʌklɪŋ/',
    'enjoy': '/ɪnˈdʒɔɪ/',
    'evening': '/ˈiːvnɪŋ/',
    'every': '/ˈevri/',
    'excited': '/ɪkˈsaɪtɪd/',
    'exercise': '/ˈeksəsaɪz/',
    'far': '/fɑː(r)/',
    'farm': '/fɑːm/',
    'feel': '/fiːl/',
    'feeling': '/ˈfiːlɪŋ/',
    'fifty': '/ˈfɪfti/',
    'film': '/fɪlm/',
    'fly': '/flaɪ/',
    'foot': '/fʊt/',
    'forty': '/ˈfɔːti/',
    'fox': '/fɒks/',
    'helpful': '/ˈhelpfl/',
    'high': '/haɪ/',
    'him': '/hɪm, ɪm/',
    'his': '/hɪz, ɪz/',
    'holiday': '/ˈhɒlədeɪ, ˈhɒlədi/',
    'hooray': '/hʊˈreɪ/',
    'information': '/ˌɪnfəˈmeɪʃn/',
    'internet': '/ˈɪntənet/',
    'kind': '/kaɪnd/',
    'live': '/lɪv/',
    'lonely': '/ˈləʊnli/',
    'math': '/mæθ/',
    'must': '/mʌst, məst/',
    'near': '/nɪə(r)/',
    'nervous': '/ˈnɜːvəs/',
    'next': '/nekst/',
    'office': '/ˈɒfɪs/',
    'over': '/ˈəʊvə(r)/',
    'parent': '/ˈpeərənt, ˈpærənt/',
    'piano': '/piˈænəʊ/',
    'picnic': '/ˈpɪknɪk/',
    'plane': '/pleɪn/',
    'poem': '/ˈpəʊɪm/',
    'poor': '/pɔː(r), pʊə(r)/',
    'proud': '/praʊd/',
    'robot': '/ˈrəʊbɒt/',
    'sad': '/sæd/',
    'science': '/ˈsaɪəns/',
    'search': '/sɜːtʃ/',
    'ship': '/ʃɪp/',
    'sit': '/sɪt/',
    'slide show': '/ˈslaɪd ʃəʊ/',
    'story': '/ˈstɔːri/',
    'subject': '/ˈsʌbdʒɪkt, ˈsʌbdʒekt/',
    'subway': '/ˈsʌbweɪ/',
    'summer': '/ˈsʌmə(r)/',
    'surprise': '/səˈpraɪz/',
    'swan': '/swɒn/',
    'take': '/teɪk/',
    'tell': '/tel/',
    'the UK': '/ðə ˌjuː ˈkeɪ/',
    'thirsty': '/ˈθɜːsti/',
    'tired': '/ˈtaɪəd/',
    'tomorrow': '/təˈmɒrəʊ/',
    'train': '/treɪn/',
    'travel': '/ˈtrævl/',
    'turn': '/tɜːn/',
    'ugly': '/ˈʌɡli/',
    'useful': '/ˈjuːsfl/',
    'water': '/ˈwɔːtə(r)/',
    'week': '/wiːk/',
    'weekday': '/ˈwiːkdeɪ/',
    'weekend': '/ˌwiːkˈend/',
    'weekly': '/ˈwiːkli/',
    'why': '/waɪ/',
    'will': '/wɪl, wəl/',
    'winner': '/ˈwɪnə(r)/',
    'work': '/wɜːk/',
    'worry': '/ˈwʌri/',
    'zero': '/ˈzɪərəʊ/',
}

def _secondary_mnemonic(key: str, headword: str, definition_zh: str, *, kind: str) -> str | None:
    if key in ROOT_MNEMONICS:
        return f'拆词联想：{ROOT_MNEMONICS[key]}'
    if key in IMAGE_MNEMONICS:
        return f'形象联想：{IMAGE_MNEMONICS[key]}'
    if key in SEMANTIC_MNEMONICS:
        return f'语义联想：{SEMANTIC_MNEMONICS[key]}'

    short = definition_zh.split('；')[0].split('，')[0].strip()
    if kind == 'phrase':
        return f'语义联想：把「{short}」和短语 {headword} 配对记忆。'

    number_words = {'fifty', 'forty', 'zero'}
    adjectives = {
        'angry', 'better', 'bored', 'cheap', 'excited', 'helpful', 'high',
        'kind', 'lonely', 'nervous', 'poor', 'proud', 'sad', 'thirsty',
        'tired', 'ugly', 'useful', 'weekly',
    }
    if key in number_words:
        return f'形象联想：想象 {short} 个数字 {headword}，边数边记住它。'
    if key in adjectives:
        return f'语义联想：看到「{short}」的事物时，就想到 {headword}。'
    return f'语义联想：把「{short}」和英文 {headword} 配对记忆。'


def mnemonic_for(headword: str, definition_zh: str, *, kind: str) -> str:
    key = headword.lower()
    parts: list[str] = []

    if key in SOUND_MNEMONICS:
        parts.append(f'谐音联想：{SOUND_MNEMONICS[key]}')

    secondary = _secondary_mnemonic(key, headword, definition_zh, kind=kind)
    if secondary:
        if parts:
            if secondary not in parts[0]:
                parts.append(secondary)
        else:
            parts.append(secondary)

    return parts[0] if len(parts) == 1 else '\n'.join(parts)
