"""Mnemonics and inflection notes for 闽教版 Grade 4 English, Volume 1 (上册).

谐音规则：仅真实谐音，不硬凑；优先语义/形象/拆词联想。
"""

from __future__ import annotations

SOUND_MNEMONICS: dict[str, str] = {
    'ball': 'ball 音近「包」，手里 ball 抱着一个球。',
    'bus': 'bus 音近「巴斯」，巴斯坐 bus 公共汽车。',
    'car': 'car 音近「卡」，卡着 car 小汽车。',
    'city': 'city 音近「西提」，西提住在 city 城市。',
    'clean': 'clean 音近「克林」，克林把 desk 擦 clean 干净。',
    'cold': 'cold 音近「扣的」，扣的 ice 冰真 cold 冷。',
    'come': 'come 音近「卡姆」，卡姆 come 过来。',
    'cow': 'cow 音近「考」，农场里的 cow 奶牛考你认不认识。',
    'dance': 'dance 音近「丹斯」，丹斯 love to dance 跳舞。',
    'desk': 'desk 音近「戴斯克」，戴斯克的书在 desk 书桌上。',
    'floor': 'floor 音近「佛楼」，佛楼扫 floor 地板。',
    'garden': 'garden 音近「嘎登」，嘎登在 garden 花园里。',
    'hand': 'hand 音近「汉的」，汉的 wash hand 洗手。',
    'house': 'house 音近「好斯」，好斯在 house 房子里。',
    'lake': 'lake 音近「雷克」，雷克边的 lake 湖。',
    'library': 'library 音近「来布瑞」，来布瑞在 library 图书馆。',
    'map': 'map 音近「麦普」，麦普看 map 地图。',
    'money': 'money 音近「马尼」，马尼的 money 钱。',
    'moon': 'moon 音近「木恩」，木恩看 moon 月亮。',
    'ms.': 'Ms. 音近「米兹」，米兹是 Ms. 女士。',
    'music': 'music 音近「缪兹克」，缪兹克听 music 音乐。',
    'new': 'new 音近「牛」，new 新的像新鲜出炉。',
    'say': 'say 音近「塞」，say 就是说出来。',
    'sing': 'sing 音近「星」，sing 唱歌像星星亮。',
    'talk': 'talk 音近「托克」，托克 love to talk 说话。',
    'tree': 'tree 音近「吹」，tree 树被风吹。',
    'wash': 'wash 音近「沃什」，沃什 wash 洗手。',
    'when': 'when 音近「温」，温问 when 什么时候。',
    'which': 'which 音近「威奇」，威奇问 which 哪一个。',
}
ROOT_MNEMONICS: dict[str, str] = {
    'basketball': 'basket 篮 + ball 球，basketball 是篮球。',
    'blackboard': 'black 黑 + board 板，blackboard 是黑板。',
    'classmate': 'class 班 + mate 伙伴，classmate 是同班同学。',
    'computer': 'compute 计算 + er，computer 是电脑。',
    'dragon boat festival': 'Dragon 龙 + Boat 船 + Festival 节日，Dragon Boat Festival 是端午节。',
    'football': 'foot 脚 + ball 球，football 是足球。',
    'get up': 'get 起来 + up 向上，get up 是起床。',
    "he's=he is": "he 他 + is 是，he's 就是「他是」。",
    'it（=（information technology）': 'Information 信息 + Technology 技术，IT 是信息技术。',
    'lantern festival': 'Lantern 灯笼 + Festival 节日，Lantern Festival 是元宵节。',
    'mid-autumn festival': 'Mid 中 + Autumn 秋 + Festival 节日，Mid-Autumn Festival 是中秋节。',
    'mooncake': 'moon 月亮 + cake 饼，mooncake 是月饼。',
    'peking opera': 'Peking 北京 + opera 歌剧，Peking opera 是京剧。',
    'pick up': 'pick 捡 + up 起来，pick up 是拾起、收拾。',
    'put up': 'put 放 + up 向上，put up 是张贴、挂起。',
    'spring festival': 'Spring 春 + Festival 节日，Spring Festival 是春节。',
    "they're=they are": "they 他们 + are 是，they're 就是「他们是」。",
}
IMAGE_MNEMONICS: dict[str, str] = {
    'blackboard': '想象 classroom 里 white chalk 写在 blackboard 黑板上。',
    'cinema': '想象 go to the cinema 看电影。',
    'computer': '想象 computer 在 desk 书桌上。',
    'cow': '想象 cow 奶牛在 farm 里吃 grass。',
    'desk': '想象 book 和 computer 在 desk 上。',
    'dragon': '想象 dragon 龙在 Dragon Boat Festival 赛龙舟上。',
    'dumpling': '想象 Spring Festival 盘里的 dumpling 饺子。',
    'football': '想象 gym 里 kick football 踢球。',
    'gym': '想象 play basketball 在 gym 体育馆。',
    'lantern': '想象 put up red lantern 挂红灯笼。',
    'library': '想象 quiet library 里有很多书。',
    'mooncake': '想象 Mid-Autumn Festival 吃 mooncake 月饼。',
    'ping-pong': '想象 gym 里打 ping-pong 乒乓球。',
    'stamp': '想象 collect stamps 收集邮票。',
    'toilet': '想象 wash hands in the toilet 卫生间。',
}
SEMANTIC_MNEMONICS: dict[str, str] = {
    'a lot': 'Thanks a lot! a lot 是许多。',
    'age': 'What is your age? age 是年龄。',
    'also': 'I also like music. also 是也。',
    'any': 'Do you have any stamps? any 是任何的。',
    'before': 'Before dinner, wash hands. before 是在……之前。',
    'best': 'the best festival. best 是最好的。',
    'boat': 'We race in a boat. boat 是小船。',
    'bright': 'The room is bright. bright 是明亮的。',
    'buy': 'Buy dumplings. buy 是买。',
    'card': 'This is my card. card 是卡片。',
    'china': 'I am from China. China 是中国。',
    'chore': 'I do chores at home. chore 是家务。',
    'christmas': 'Merry Christmas! Christmas 是圣诞节。',
    'collect': 'I collect stamps. collect 是收集。',
    'cousin': 'This is my cousin. cousin 是表（堂）兄弟姐妹。',
    'daily': 'daily life. daily 是每日的。',
    'else': 'What else? else 是其他的、此外。',
    'fair': 'Go to the fair. fair 是庙会。',
    'festival': 'Spring Festival. festival 是节日。',
    'from': 'I am from China. from 是来自。',
    'full': 'The bus is full. full 是满的、饱的。',
    'gala': 'Spring Festival gala. gala 是盛会、庆典。',
    'get': 'Get up! Get your ball. get 是拿、得到。',
    'grade': 'Grade Four. grade 是年级。',
    'has': 'She has a ball. has 是 have 的第三人称单数，表示有。',
    'her': 'This is her house. her 是她的。',
    'hobby': 'My hobby is music. hobby 是爱好。',
    'hope': 'I hope you have good luck. hope 是希望。',
    'ice': 'The ice is cold. ice 是冰。',
    'interesting': 'IT is interesting. interesting 是很有意思的。',
    'into': 'Get into the car. into 是到……里面。',
    'join': 'Join us at the fair. join 是参加。',
    'kung fu': 'Kung fu is from China. kung fu 是功夫。',
    'learn': 'I learn English. learn 是学习。',
    'life': 'School life is wonderful. life 是生活。',
    'listen': 'Listen to music. listen 是听。',
    'luck': 'Good luck! luck 是运气。',
    'lucky': 'You are lucky! lucky 是幸运的。',
    'merry': 'Merry Christmas! merry 是快乐的。',
    'often': 'I often get up early. often 是经常。',
    'peking opera': 'I like Peking opera. Peking opera 是中国京剧。',
    'quiet': 'Be quiet in the library. quiet 是安静的。',
    'race': 'boat race. race 是赛跑。',
    'riddle': 'Guess the riddle! riddle 是谜语。',
    'same': 'the same grade. same 是相同的。',
    'sleep': 'Go to sleep. sleep 是睡觉。',
    'sometimes': 'I sometimes wash the floor. sometimes 是有时。',
    'song': 'Sing a song. song 是歌曲。',
    'student': 'I am a student. student 是学生。',
    'sweep': 'Sweep the floor. sweep 是扫。',
    'tail': 'The dog has a long tail. tail 是尾巴。',
    'their': 'This is their hobby. their 是他们的。',
    'them': 'Say hello to them. them 是他们（宾格）。',
    'there': 'There is a library. there 表示有、在那里。',
    'thing': 'What is this thing? thing 是东西。',
    'try': 'Try a mooncake. try 是尝试。',
    'wonderful': 'The song is wonderful. wonderful 是极好的。',
    'yours': 'Is this yours? yours 是你的（东西）。',
}
INFLECTION_NOTES: dict[str, str] = {
    'buy': '第三人称单数 buys',
    'city': '复数 cities',
    'classmate': '复数 classmates',
    'clean': '动词第三人称单数 cleans',
    'collect': '第三人称单数 collects',
    'come': '第三人称单数 comes',
    'cow': '复数 cows',
    'dance': '第三人称单数 dances',
    'dumpling': '复数 dumplings',
    'get': '第三人称单数 gets；过去式 got',
    'has': 'have 的第三人称单数形式',
    'hope': '第三人称单数 hopes',
    'join': '第三人称单数 joins',
    'lantern': '复数 lanterns',
    'learn': '第三人称单数 learns',
    'listen': '第三人称单数 listens',
    'mooncake': '复数 mooncakes',
    'say': '第三人称单数 says',
    'sing': '第三人称单数 sings',
    'sleep': '第三人称单数 sleeps；过去式 slept',
    'stamp': '复数 stamps',
    'student': '复数 students',
    'sweep': '第三人称单数 sweeps',
    'talk': '第三人称单数 talks',
    'try': '第三人称单数 tries',
    'wash': '第三人称单数 washes',
}
DEFINITION_OVERRIDES: dict[str, str] = {
    'blackboard': '黑板',
    'bright': '明亮的',
    'card': '卡片',
    'cinema': '电影院',
    'city': '城市',
    'classmate': '同班同学',
    'clean': '干净的；打扫',
    'cold': '寒冷的；冷的',
    'come': '来；到',
    'computer': '电脑',
    'cousin': '表（堂）兄弟姐妹',
    'cow': '奶牛',
    'dance': '跳舞',
    'desk': '书桌',
    'grade': '年级',
    'ice': '冰',
    'IT（=（Information Technology）': '信息技术',
    'library': '图书馆',
    'Ms.': '女士',
    'new': '新的',
    'same': '同一的；相同的',
    'sing': '唱歌',
    'student': '学生',
    'there': '（表示存在）有；在那里',
    'which': '哪一个；哪一些',
    'age': '年龄',
    'ball': '球',
    'bus': '公共汽车',
    'car': '小汽车；轿车',
    'chore': '家务',
    'daily': '每日的',
    'floor': '地板；层',
    'football': '足球',
    'full': '满的；饱的',
    'garden': '花园',
    'get': '拿；得到',
    'get up': '起床',
    'gym': '健身房；体育馆',
    'hand': '手',
    'has': '有；吃',
    'her': '她的',
    'house': '房子',
    'into': '到……里面',
    'life': '生活；生命',
    'often': '经常',
    'pick up': '收拾；拾起',
    'sometimes': '有时',
    'sweep': '扫',
    'talk': '说话；谈论',
    'toilet': '卫生间；厕所',
    'wash': '洗',
    'when': '什么时候',
    'a lot': '许多',
    'also': '也',
    'basketball': '篮球',
    'China': '中国',
    'collect': '收集',
    'from': '来自',
    "he's=he is": '他是',
    'hobby': '爱好',
    'interesting': '有意思的；令人感兴趣的',
    'kung fu': '功夫',
    'lake': '湖',
    'learn': '学习',
    'listen': '听',
    'music': '音乐',
    'Peking opera': '中国京剧',
    'ping-pong': '乒乓球',
    'song': '歌；歌曲',
    'stamp': '邮票',
    'tail': '尾巴',
    'their': '他们的；她们的；它们的',
    "they're=they are": '他们是；她们是；它们是',
    'thing': '东西；事物',
    'tree': '树',
    'wonderful': '极好的',
    'any': '任何的；任一的',
    'before': '在……之前',
    'best': '最好的',
    'boat': '小船；划船',
    'buy': '买',
    'Christmas': '圣诞节',
    'dragon': '龙',
    'Dragon Boat Festival': '端午节',
    'dumpling': '饺子',
    'else': '其他的；此外',
    'fair': '庙会',
    'festival': '节日',
    'gala': '盛会；庆典',
    'hope': '希望',
    'join': '参加',
    'lantern': '灯笼',
    'Lantern Festival': '元宵节',
    'luck': '运气',
    'lucky': '幸运的',
    'map': '地图',
    'merry': '快乐的',
    'Mid-Autumn Festival': '中秋节',
    'money': '钱',
    'moon': '月亮',
    'mooncake': '月饼',
    'put up': '张贴',
    'quiet': '安静的',
    'race': '赛跑；速度竞赛',
    'riddle': '谜语',
    'say': '说',
    'sleep': '睡觉',
    'Spring Festival': '春节',
    'them': '他们；她们；它们（宾格）',
    'try': '尝试',
    'yours': '你（们）的（东西）；……谨上',
}
POS_OVERRIDES: dict[str, str] = {
    'blackboard': 'n.',
    'bright': 'adj.',
    'card': 'n.',
    'cinema': 'n.',
    'city': 'n.',
    'classmate': 'n.',
    'clean': 'adj./v.',
    'cold': 'adj./n.',
    'come': 'v.',
    'computer': 'n.',
    'cousin': 'n.',
    'cow': 'n.',
    'dance': 'v./n.',
    'desk': 'n.',
    'grade': 'n.',
    'ice': 'n.',
    'IT（=（Information Technology）': 'n.',
    'library': 'n.',
    'Ms.': 'n.',
    'new': 'adj.',
    'same': 'adj.',
    'sing': 'v.',
    'student': 'n.',
    'there': 'adv./pron.',
    'which': 'det./pron.',
    'age': 'n.',
    'ball': 'n.',
    'bus': 'n.',
    'car': 'n.',
    'chore': 'n.',
    'daily': 'adj.',
    'floor': 'n.',
    'football': 'n.',
    'full': 'adj.',
    'garden': 'n.',
    'get': 'v.',
    'get up': 'v. phr.',
    'gym': 'n.',
    'hand': 'n.',
    'has': 'v.',
    'her': 'det./pron.',
    'house': 'n.',
    'into': 'prep.',
    'life': 'n.',
    'often': 'adv.',
    'pick up': 'v. phr.',
    'sometimes': 'adv.',
    'sweep': 'v.',
    'talk': 'v.',
    'toilet': 'n.',
    'wash': 'v.',
    'when': 'adv./conj.',
    'a lot': 'adv./det.',
    'also': 'adv.',
    'basketball': 'n.',
    'China': 'n.',
    'collect': 'v.',
    'from': 'prep.',
    "he's=he is": 'v.',
    'hobby': 'n.',
    'interesting': 'adj.',
    'kung fu': 'n.',
    'lake': 'n.',
    'learn': 'v.',
    'listen': 'v.',
    'music': 'n.',
    'Peking opera': 'n.',
    'ping-pong': 'n.',
    'song': 'n.',
    'stamp': 'n.',
    'tail': 'n.',
    'their': 'det.',
    "they're=they are": 'v.',
    'thing': 'n.',
    'tree': 'n.',
    'wonderful': 'adj.',
    'any': 'det./pron.',
    'before': 'prep./adv.',
    'best': 'adj./adv.',
    'boat': 'n./v.',
    'buy': 'v.',
    'Christmas': 'n.',
    'dragon': 'n.',
    'Dragon Boat Festival': 'n.',
    'dumpling': 'n.',
    'else': 'adv.',
    'fair': 'n.',
    'festival': 'n.',
    'gala': 'n.',
    'hope': 'v./n.',
    'join': 'v.',
    'lantern': 'n.',
    'Lantern Festival': 'n.',
    'luck': 'n.',
    'lucky': 'adj.',
    'map': 'n.',
    'merry': 'adj.',
    'Mid-Autumn Festival': 'n.',
    'money': 'n.',
    'moon': 'n.',
    'mooncake': 'n.',
    'put up': 'v. phr.',
    'quiet': 'adj.',
    'race': 'n./v.',
    'riddle': 'n.',
    'say': 'v.',
    'sleep': 'v./n.',
    'Spring Festival': 'n.',
    'them': 'pron.',
    'try': 'v.',
    'yours': 'pron.',
}
IPA_OVERRIDES: dict[str, str] = {
    'blackboard': '/ˈblækbɔːd/',
    'bright': '/braɪt/',
    'card': '/kɑːd/',
    'cinema': '/ˈsɪnəmə/',
    'city': '/ˈsɪti/',
    'classmate': '/ˈklɑːsmeɪt/',
    'clean': '/kliːn/',
    'cold': '/kəʊld/',
    'come': '/kʌm/',
    'computer': '/kəmˈpjuːtə(r)/',
    'cousin': '/ˈkʌzn/',
    'cow': '/kaʊ/',
    'dance': '/dɑːns/',
    'desk': '/desk/',
    'grade': '/ɡreɪd/',
    'ice': '/aɪs/',
    'IT（=（Information Technology）': '/ˌaɪ ˈtiː/',
    'library': '/ˈlaɪbrəri, ˈlaɪbri/',
    'Ms.': '/mɪz, məz/',
    'new': '/njuː/',
    'same': '/seɪm/',
    'sing': '/sɪŋ/',
    'student': '/ˈstjuːdnt/',
    'there': '/ðeə(r)/',
    'which': '/wɪtʃ/',
    'age': '/eɪdʒ/',
    'ball': '/bɔːl/',
    'bus': '/bʌs/',
    'car': '/kɑː(r)/',
    'chore': '/tʃɔː(r)/',
    'daily': '/ˈdeɪli/',
    'floor': '/flɔː(r)/',
    'football': '/ˈfʊtbɔːl/',
    'full': '/fʊl/',
    'garden': '/ˈɡɑːdn/',
    'get': '/ɡet/',
    'get up': '/ɡet ʌp/',
    'gym': '/dʒɪm/',
    'hand': '/hænd/',
    'has': '/hæz, həz/',
    'her': '/hɜː(r), hə(r)/',
    'house': '/haʊs/',
    'into': '/ˈɪntuː, ˈɪntə/',
    'life': '/laɪf/',
    'often': '/ˈɒfn, ˈɒftən/',
    'pick up': '/pɪk ʌp/',
    'sometimes': '/ˈsʌmtaɪmz/',
    'sweep': '/swiːp/',
    'talk': '/tɔːk/',
    'toilet': '/ˈtɔɪlət/',
    'wash': '/wɒʃ/',
    'when': '/wen/',
    'a lot': '/ə ˈlɒt/',
    'also': '/ˈɔːlsəʊ/',
    'basketball': '/ˈbɑːskɪtbɔːl/',
    'China': '/ˈtʃaɪnə/',
    'collect': '/kəˈlekt/',
    'from': '/frɒm, frəm/',
    "he's=he is": '/hiːz/',
    'hobby': '/ˈhɒbi/',
    'interesting': '/ˈɪntrəstɪŋ, ˈɪntrestɪŋ/',
    'kung fu': '/ˌkʌŋ ˈfuː/',
    'lake': '/leɪk/',
    'learn': '/lɜːn/',
    'listen': '/ˈlɪsn/',
    'music': '/ˈmjuːzɪk/',
    'Peking opera': '/ˌpiːkɪŋ ˈɒprə/',
    'ping-pong': '/ˈpɪŋ pɒŋ/',
    'song': '/sɒŋ/',
    'stamp': '/stæmp/',
    'tail': '/teɪl/',
    'their': '/ðeə(r)/',
    "they're=they are": '/ðeə(r)/',
    'thing': '/θɪŋ/',
    'tree': '/triː/',
    'wonderful': '/ˈwʌndəfl/',
    'any': '/ˈeni/',
    'before': '/bɪˈfɔː(r)/',
    'best': '/best/',
    'boat': '/bəʊt/',
    'buy': '/baɪ/',
    'Christmas': '/ˈkrɪsməs/',
    'dragon': '/ˈdræɡən/',
    'Dragon Boat Festival': '/ˌdræɡən bəʊt ˈfestɪvl/',
    'dumpling': '/ˈdʌmplɪŋ/',
    'else': '/els/',
    'fair': '/feə(r)/',
    'festival': '/ˈfestɪvl/',
    'gala': '/ˈɡɑːlə/',
    'hope': '/həʊp/',
    'join': '/dʒɔɪn/',
    'lantern': '/ˈlæntən/',
    'Lantern Festival': '/ˌlæntən ˈfestɪvl/',
    'luck': '/lʌk/',
    'lucky': '/ˈlʌki/',
    'map': '/mæp/',
    'merry': '/ˈmeri/',
    'Mid-Autumn Festival': '/ˌmɪd ˈɔːtəm ˈfestɪvl/',
    'money': '/ˈmʌni/',
    'moon': '/muːn/',
    'mooncake': '/ˈmuːnkeɪk/',
    'put up': '/pʊt ʌp/',
    'quiet': '/ˈkwaɪət/',
    'race': '/reɪs/',
    'riddle': '/ˈrɪdl/',
    'say': '/seɪ/',
    'sleep': '/sliːp/',
    'Spring Festival': '/ˌsprɪŋ ˈfestɪvl/',
    'them': '/ðem, ðəm/',
    'try': '/traɪ/',
    'yours': '/jɔːz/',
}

def _secondary_mnemonic(key: str, headword: str, definition_zh: str, *, kind: str) -> str | None:
    if key in ROOT_MNEMONICS:
        return f'拆词联想：{ROOT_MNEMONICS[key]}'
    if key in IMAGE_MNEMONICS:
        return f'形象联想：{IMAGE_MNEMONICS[key]}'
    if key in SEMANTIC_MNEMONICS:
        return f'语义联想：{SEMANTIC_MNEMONICS[key]}'

    short = definition_zh.split('；')[0].split('，')[0].strip()
    if kind == 'phrase':
        return f'语义联想：把「{short}」和短语 {headword} 配对记忆。'

    adjectives = {
        'bright', 'clean', 'cold', 'new', 'same', 'daily', 'full', 'interesting',
        'wonderful', 'lucky', 'quiet', 'merry', 'best',
    }
    if key in adjectives:
        return f'语义联想：看到「{short}」的事物时，就想到 {headword}。'
    return f'语义联想：把「{short}」和英文 {headword} 配对记忆。'


def mnemonic_for(headword: str, definition_zh: str, *, kind: str) -> str:
    key = headword.lower()
    parts: list[str] = []

    if key in SOUND_MNEMONICS:
        parts.append(f'谐音联想：{SOUND_MNEMONICS[key]}')

    secondary = _secondary_mnemonic(key, headword, definition_zh, kind=kind)
    if secondary:
        if parts:
            if secondary not in parts[0]:
                parts.append(secondary)
        else:
            parts.append(secondary)

    return parts[0] if len(parts) == 1 else '\n'.join(parts)
