"""Mnemonics and inflection notes for PEP Grade 6 English, Volume 1 (上册).

谐音规则与 en-grade3-v2-rj 一致：仅真实谐音，不硬凑；优先语义/形象/拆词联想。
"""

from __future__ import annotations

# 谐音联想：仅 headword 与中文读音确有相似处才写。
SOUND_MNEMONICS: dict[str, str] = {
    'paris': 'Paris 音近「巴黎」，Paris 就是巴黎。',
    'send': 'send 音近「送」，send a postcard 就是邮寄发送。',
    'cheer': 'cheer 音近「起儿」，观众 cheer 欢呼加油。',
    'sale': 'sale 音近「售哦」，sale 是特价出售。',
    'cool': 'cool 音近「酷」，天气 cool 凉爽，也很酷。',
    'mars': 'Mars 音近「马斯」，Mars 是火星。',
    'glass': 'glass 音近「格拉斯」，a glass 可以指一杯或玻璃。',
    'fever': 'fever 音近「非热」，发烧 fever 体温升高。',
    'ticket': 'ticket 音近「提客」，ticket 是票。',
    'race': 'race 音近「瑞斯」，race 赛跑比速度。',
    'star': 'star 音近「斯达」，night sky 里的 star 是星。',
    'power': 'power 音近「泡儿」，power 是驱动机器的能源力量。',
    'market': 'market 音近「马keit」，market 是买卖东西的集市。',
}

ROOT_MNEMONICS: dict[str, str] = {
    'kilometre': 'kilo 千 + metre 米，kilometre 是千米、公里。',
    'gingerbread house': 'gingerbread 姜饼 + house 屋，gingerbread house 是姜饼屋。',
    'hong kong-zhuhai-macao bridge': 'Hong Kong 香港 + Zhuhai 珠海 + Macao 澳门 + Bridge 桥，港珠澳大桥。',
    'terracotta warriors': 'terracotta 陶 + warriors 战士，Terracotta Warriors 是兵马俑。',
    'jinggangshan revolution museum': 'Jinggangshan 井冈山 + Revolution 革命 + Museum 博物馆。',
    'the red army': 'the Red 红色 + Army 军队，the Red Army 是红军。',
    'new zealand': 'New 新 + Zealand 西兰，New Zealand 是新西兰。',
    'eiffel tower': 'Eiffel 埃菲尔 + Tower 塔，Eiffel Tower 是埃菲尔铁塔。',
    'inspiring': 'inspire 鼓舞 + ing，inspiring 是鼓舞人心的。',
    'airport': 'air 航空 + port 港，airport 是机场。',
    'count down': 'count 数 + down 向下，count down 是倒计时。',
    'book fair': 'book 书 + fair 集市，book fair 是书市。',
    'runny nose': 'runny 流淌的 + nose 鼻子，runny nose 是流鼻涕。',
    'stay up': 'stay 保持 + up 醒着，stay up 是熬夜。',
    'pocket money': 'pocket 口袋 + money 钱，pocket money 是零花钱。',
    'save up': 'save 存 + up 起来，save up 是攒钱。',
    'for example': 'for 为了 + example 例子，for example 是例如。',
    'outer space': 'outer 外层 + space 空间，outer space 是外太空。',
    'space station': 'space 太空 + station 站，space station 是空间站。',
    'astronaut': 'astro 星星 + naut 航行者，astronaut 是宇航员。',
    'run out': 'run 跑/运行 + out 出，run out 是用完。',
    'air conditioner': 'air 空气 + condition 调节 + er，air conditioner 是空调。',
    'sunrise': 'sun 太阳 + rise 升起，sunrise 是日出。',
    'sunset': 'sun 太阳 + set 落下，sunset 是日落。',
    'spaceship': 'space 太空 + ship 船，spaceship 是宇宙飞船。',
    'telescope': 'tele 远 + scope 看，telescope 是望远镜。',
    'taikonaut': 'taikong 太空 + naut 航行者，taikonaut 是中国航天员。',
    'toothpaste': 'tooth 牙 + paste 膏，toothpaste 是牙膏。',
    'electricity': 'electric 电的 + ity 名词，electricity 是电。',
    'solar': 'sol 太阳 + ar，solar 是太阳的。',
    'resource': 're 再 + source 来源，resource 是可利用的资源。',
    'reuse': 're 再 + use 使用，reuse 是重复使用。',
    'unplug': 'un 取消 + plug 插头，unplug 是拔插头。',
    'microscope': 'micro 微 + scope 看，microscope 是显微镜。',
    'exciting': 'excite 使激动 + ing，exciting 是令人激动的。',
    'yesterday': 'yester 昨日 + day 日，yesterday 是昨天。',
    'writer': 'write 写 + er 的人，writer 是作家。',
    'winner': 'win 赢 + er 的人，winner 是获胜者。',
    'marathon': '来自希腊 Marathon 地名，marathon 是马拉松赛跑。',
    'satellite': 'satell 伴随 + ite，satellite 是绕行星运行的人造卫星。',
    'daytime': 'day 日 + time 时间，daytime 是白天。',
    'haircut': 'hair 头发 + cut 剪，haircut 是发型、理发。',
    'schoolbag': 'school 学校 + bag 包，schoolbag 是书包。',
    'unhappy': 'un 不 + happy 快乐，unhappy 是不快乐的。',
    'another': 'an 一 + other 其他，another 是另一个。',
    'discuss': 'dis 分开 + cuss 议论，discuss 是讨论。',
    'difference': 'differ 不同 + ence，difference 是差别。',
    'useful': 'use 使用 + ful 充满，useful 是有用的。',
}

IMAGE_MNEMONICS: dict[str, str] = {
    'climb': '想象 climb 手脚并用爬上长城或小山。',
    'was': '想象 was 把现在的 is 推回到过去。',
    'go': '想象 go 背着包走向机场或博物馆。',
    'see': '想象 see 眼睛看到埃菲尔铁塔或兵马俑。',
    'take': '想象 take photos 举起相机拍照。',
    'dry': '想象 dry 沙漠里太阳晒得地面干干的。',
    'thousand': '想象 thousand 兵马俑排成成千上万行。',
    'clay': '想象 clay 陶土在手中捏成陶俑。',
    'view': '想象 view 站在山顶俯瞰村庄景色。',
    'village': '想象 village 小村庄里有梯田和竹林。',
    'bamboo': '想象 bamboo 绿竹成林，熊猫在吃竹子。',
    'pumpkin': '想象 pumpkin 橙色大南瓜摆在餐馆门口。',
    'restaurant': '想象 restaurant 旅行后坐下来吃饭。',
    'begin': '想象 begin 晚会倒计时后节目开始。',
    'count down': '想象 count down 十、九、八……烟花升空。',
    'gala': '想象 gala 舞台上灯光、歌声和欢呼。',
    'marathon': '想象 marathon 长跑选手冲过终点线。',
    'cold': '想象 cold 感冒时纸巾和 runny nose。',
    'fever': '想象 fever 体温计水银柱升高。',
    'stay up': '想象 stay up 深夜还亮着的台灯。',
    'money': '想象 money 硬币掉进攒钱 jar 里。',
    'jar': '想象 jar 玻璃罐里装满攒下的 pocket money。',
    'microscope': '想象 microscope 下放大的一片叶子。',
    'cloud': '想象 cloud 白云飘过 sky 遮住 sun。',
    'moon': '想象 moon 夜空中明亮的圆月。',
    'mars': '想象 Mars 红色星球上 rover 在行驶。',
    'rover': '想象 rover 在 Mars 上采集 soil 样本。',
    'spaceship': '想象 spaceship 载着 taikonaut 飞向 outer space。',
    'sunrise': '想象 sunrise 太阳从 ocean 上升起。',
    'sunset': '想象 sunset 天空染成橙红色。',
    'electricity': '想象 electricity 点亮 light 驱动 air conditioner。',
    'unplug': '想象 unplug 把插头从插座里拔出来省电。',
    'bottle': '想象 bottle 洗干净后 reuse 装水。',
    'shower': '想象 shower 喷头洒下热水。',
    'space station': '想象 taikonaut 在 space station 里看地球。',
    'astronaut': '想象 astronaut 在 spaceship 里向学生挥手。',
    'run out': '想象电池 run out，灯就灭了——资源用完。',
    'dirty': '想象 dirty bottle 要先洗才能 reuse。',
    'top': '想象把 top 盖在 bottle 上，或站在 top 层书架。',
}

SEMANTIC_MNEMONICS: dict[str, str] = {
    'send': 'I will send a postcard. send 是邮寄、发送。',
    'take': 'We take photos at every place. take 这里指拿、带，也指上（课）。',
    'inspiring': 'The Red Army story is inspiring. inspiring 是鼓舞人心的。',
    'judge': 'Teachers judge the contest. judge 是评判、裁判。',
    'notice': 'Read the notice on the board. notice 是通知。',
    'paste': 'Paste the poster on the wall. paste 是粘贴。',
    'as': 'She works as a writer. as 是作为。',
    'ever': 'Have you ever been to a book fair? ever 是以往任何时候。',
    'dress': 'Dress up for the gala. dress 是穿衣服、打扮。',
    'read': 'Read the notice carefully. read 是阅读。',
    'sing': 'We sing at the gala. sing 是唱、演唱。',
    'wear': 'Wear new clothes for the festival. wear 是穿、戴。',
    'head': 'My head hurts. head 是头部。',
    'soon': 'You will feel better soon. soon 是很快、马上。',
    'cough': 'Cover your mouth when you cough. cough 是咳嗽。',
    'diet': 'A good diet keeps you healthy. diet 是日常饮食。',
    'add': 'Add honey to warm water. add 是增加、补充说。',
    'better': 'I feel better today. better 是好转的、更好的。',
    'call': 'Call the doctor. call 是（给……）打电话。',
    'cry': "Don't cry. cry 是哭。",
    'email': 'Send an email to the nurse. email 是电子邮件。',
    'may': 'You may stay home. may 是也许、可能。',
    'goods': 'The shop sells many goods. goods 是商品。',
    'service': 'The shop has good service. service 是服务。',
    'lucky': "You're lucky to get a ticket. lucky 是幸运的。",
    'manage': 'Manage your pocket money. manage 是管理。',
    'sell': 'They sell drinks at the fair. sell 是卖、售卖。',
    'planet': 'Earth is our planet. planet 是行星。',
    'sky': 'Stars shine in the sky. sky 是天空。',
    'space': 'We learn about space. space 是太空、空间。',
    'alien': 'Children imagine aliens. alien 是外星生物。',
    'into': 'Go into outer space. into 是进入。',
    'month': 'It takes months to reach Mars. month 是月。',
    'cloth': 'Wipe with a clean cloth. cloth 是布。',
    'question': 'I have a question about space. question 是问题。',
    'time': 'How many times have you read it? time 是次、回。',
    'power': 'Solar power comes from the sun. power 是能源、力量。',
    'energy': 'Save energy at home. energy 是能源、能量。',
    'heat': 'The sun gives heat and light. heat 是加热、热量。',
    'light': 'Turn off the light. light 是光。',
    'source': 'The sun is a source of energy. source 是来源。',
    'type': 'What type of energy? type 是类型、种类。',
    'change': 'Change habits to save energy. change 是改变。',
    'few': 'Only a few lights are on. few 是不多、很少。',
    'quick': 'Take a quick shower. quick 是迅速的、快的。',
    'reduce': 'Reduce waste. reduce 是减少。',
    'side': 'On the other side of the table. side 是一面、一边。',
    'drive': 'Drive less to save energy. drive 是驾驶。',
    'own': 'I have my own bottle. own 是自己的。',
    'ocean': 'Fish live in the ocean. ocean 是海洋。',
    'earth': 'Protect the earth. earth 是地球。',
    'marble': 'He collects marbles. marble 是弹子、弹珠。',
    'soil': 'Plants need soil. soil 是土壤。',
    'video': 'Watch a video about health. video 是视频、录像。',
    'half': 'Half price today. half 是一半。',
    'difficult': 'Saving money is difficult. difficult 是困难的。',
    'drink': 'Would you like a drink? drink 是饮料。',
    'ticket': 'Buy a ticket for the show. ticket 是票。',
    'ill': 'He is ill today. ill 是有病的、不舒服的。',
    'discuss': 'Discuss a healthy diet. discuss 是讨论、商量。',
    'unhappy': 'He feels unhappy when ill. unhappy 是不快乐的。',
    'wake': 'Wake up early on festival days. wake 是醒来。',
    'win': 'Our class won the contest. win 是获胜。',
    'race': 'The race starts at nine. race 是赛跑。',
    'run': 'They run in the marathon. run 是跑、奔跑。',
    'make': 'Make posters for the fair. make 是做、使。',
    'cheer': 'Cheer for our team. cheer 是欢呼、加油。',
    'later': 'See you later. later 是后来。',
    'begin': 'The gala will begin at seven. begin 是开始。',
    'exciting': 'The gala was exciting. exciting 是令人激动的。',
    'cold': 'I have a cold. cold 这里指感冒。',
    'eat': 'We eat at a restaurant. eat 是吃。',
    'airport': 'We arrived at the airport. airport 是机场。',
    'view': 'The view is wonderful. view 是景色。',
    'village': 'They live in a village. village 是村庄。',
    'star': 'Stars shine at night. star 是恒星、星。',
    'satellite': 'A satellite goes around the earth. satellite 是人造卫星。',
    'cool': 'The room stays cool. cool 是凉爽的。',
    'useful': 'Solar energy is useful. useful 是有用的。',
    'reuse': 'Reuse old bottles. reuse 是重复使用。',
    'market': 'Buy fruit at the market. market 是市场。',
    'bottle': 'Reuse this bottle. bottle 是瓶子。',
    'haircut': 'A haircut costs twenty yuan. haircut 是发型。',
    'sale': 'Books are on sale. sale 是特价销售。',
    'writer': 'I want to be a writer. writer 是作家。',
    'yesterday': 'We had a gala yesterday. yesterday 是昨天。',
    'new zealand': 'We learn about New Zealand. New Zealand 是新西兰。',
    'paris': 'Paris is the capital of France. Paris 是巴黎。',
    'mars': 'The rover explores Mars. Mars 是火星。',
    'eiffel tower': 'The Eiffel Tower is in Paris. Eiffel Tower 是埃菲尔铁塔。',
    'terracotta warriors': "The Terracotta Warriors are in Xi'an. Terracotta Warriors 是兵马俑。",
    'hong kong-zhuhai-macao bridge': 'The bridge connects three places. Hong Kong-Zhuhai-Macao Bridge 是港珠澳大桥。',
    'jinggangshan revolution museum': 'We visited the museum. Jinggangshan Revolution Museum 是井冈山革命博物馆。',
    'the red army': 'The story of the Red Army is inspiring. the Red Army 是红军。',
    'book fair': 'There is a book fair at school. book fair 是书市。',
    'count down': 'Count down to the New Year. count down 是倒计时。',
    'runny nose': 'I have a runny nose. runny nose 是流鼻涕。',
    'stay up': "Don't stay up late. stay up 是熬夜。",
    'pocket money': 'Save your pocket money. pocket money 是零花钱。',
    'save up': 'Save up for a new bag. save up 是攒钱。',
    'for example': 'Reuse bottles, for example. for example 是例如。',
    'outer space': 'Taikonauts travel into outer space. outer space 是外太空。',
    'space station': 'Taikonauts work on the space station. space station 是空间站。',
    'astronaut': 'The astronaut waved from the spaceship. astronaut 是宇航员。',
    'air conditioner': 'Turn off the air conditioner. air conditioner 是空调。',
    'gingerbread house': 'Sarah saw a gingerbread house. gingerbread house 是姜饼屋。',
    'daytime': 'We see the sun in the daytime. daytime 是白天。',
    'schoolbag': 'My schoolbag is heavy. schoolbag 是书包。',
    'sunrise': 'We watched the sunrise. sunrise 是日出。',
    'sunset': 'The sunset looks beautiful. sunset 是日落。',
    'spaceship': 'The taikonaut flew in a spaceship. spaceship 是宇宙飞船。',
    'telescope': 'Look through the telescope. telescope 是望远镜。',
    'taikonaut': 'A taikonaut needs long training. taikonaut 是中国航天员。',
    'toothpaste': 'Buy toothpaste at the market. toothpaste 是牙膏。',
    'run out': 'Resources may run out. run out 是用完。',
    'dirty': 'Wash the dirty bottle. dirty 是脏的。',
    'top': 'Put the top on the bottle. top 是最高的/顶部的。',
    'electricity': 'Turn off the light to save electricity. electricity 是电。',
    'unplug': 'Unplug the TV to save power. unplug 是拔插头。',
    'microscope': 'Use a microscope in class. microscope 是显微镜。',
    'kilometre': 'The bridge is fifty-five kilometres long. kilometre 是千米、公里。',
    'thousand': 'Thousands of warriors stand in rows. thousand 是一千。',
}

INFLECTION_NOTES: dict[str, str] = {
    'was': 'be 动词过去式（第一、三人称单数）；复数过去式 were',
    'go': '第三人称单数 goes；过去式 went',
    'see': '第三人称单数 sees；过去式 saw',
    'eat': '第三人称单数 eats；过去式 ate',
    'take': '第三人称单数 takes；过去式 took',
    'send': '第三人称单数 sends；过去式 sent',
    'climb': '第三人称单数 climbs；过去式 climbed',
    'begin': '第三人称单数 begins；过去式 began',
    'wake': '第三人称单数 wakes；过去式 woke',
    'win': '第三人称单数 wins；过去式 won',
    'run': '第三人称单数 runs；过去式 ran',
    'read': '第三人称单数 reads；过去式 read /red/',
    'sing': '第三人称单数 sings；过去式 sang',
    'wear': '第三人称单数 wears；过去式 wore',
    'make': '第三人称单数 makes；过去式 made',
    'sell': '第三人称单数 sells；过去式 sold',
    'drive': '第三人称单数 drives；过去式 drove',
    'call': '第三人称单数 calls；过去式 called',
    'cry': '第三人称单数 cries；过去式 cried',
    'discuss': '第三人称单数 discusses；过去式 discussed',
    'manage': '第三人称单数 manages；过去式 managed',
    'change': '第三人称单数 changes；过去式 changed',
    'reduce': '第三人称单数 reduces；过去式 reduced',
    'goods': '复数形式；单数 good 指商品较少用',
    'kilometre': '复数 kilometres',
    'thousand': '复数 thousands',
    'village': '复数 villages',
    'winner': '复数 winners',
    'cloud': '复数 clouds',
    'planet': '复数 planets',
    'star': '复数 stars',
    'month': '复数 months',
    'question': '复数 questions',
    'bottle': '复数 bottles',
    'resource': '复数 resources',
    'difference': '复数 differences',
    'few': '比较级 fewer；最高级 fewest',
    'better': 'good/well 的比较级',
    'dress': '第三人称单数 dresses；过去式 dressed',
    'paste': '第三人称单数 pastes；过去式 pasted',
    'cheer': '第三人称单数 cheers；过去式 cheered',
}

DEFINITION_OVERRIDES: dict[str, str] = {
    'was': 'be 的过去式（第一、三人称单数）',
    'climb': '爬；攀登',
    'kilometre': '千米；公里',
    'gingerbread house': '姜饼屋',
    'send': '邮寄；发送',
    'go': '去；走',
    'see': '看见',
    'take': '学习；上（课）；拿',
    'dry': '干燥的',
    'eat': '吃',
    'inspiring': '鼓舞人心的',
    'clay': '陶土',
    'thousand': '一千',
    'view': '景色',
    'village': '村庄；村镇',
    'airport': '机场',
    'bamboo': '竹子',
    'pumpkin': '南瓜',
    'restaurant': '餐馆；餐厅',
    'New Zealand': '新西兰',
    'Paris': '巴黎',
    'Eiffel Tower': '埃菲尔铁塔',
    'Terracotta Warriors': '兵马俑',
    'Hong Kong-Zhuhai-Macao Bridge': '港珠澳大桥',
    'Jinggangshan Revolution Museum': '井冈山革命博物馆',
    'the Red Army': '红军',
    'begin': '开始',
    'judge': '评判；裁判',
    'later': '后来',
    'notice': '通知',
    'wake': '醒来',
    'win': '获胜',
    'winner': '获胜者',
    'ever': '以往任何时候',
    'paste': '粘贴',
    'count down': '倒计时',
    'dress': '穿衣服',
    'gala': '演出；庆典',
    'as': '作为',
    'book fair': '书市',
    'cheer': '欢呼；加油',
    'marathon': '马拉松赛跑',
    'race': '赛跑；速度竞赛',
    'run': '跑；奔跑',
    'make': '做；使',
    'read': '阅读',
    'sing': '唱；演唱',
    'wear': '穿；戴',
    'writer': '作家；作者',
    'yesterday': '昨天',
    'exciting': '令人激动的',
    'cold': '感冒',
    'head': '头部',
    'runny nose': '流鼻涕',
    'soon': '很快；马上',
    'ill': '有病的；不舒服的',
    'cough': '咳嗽',
    'fever': '发烧；发热',
    'discuss': '讨论；商量',
    'diet': '日常饮食',
    'stay up': '熬夜',
    'add': '补充说；增加',
    'another': '另一；不同的',
    'better': '好转的；更好的',
    'call': '（给……）打电话',
    'cry': '哭',
    'email': '电子邮件',
    'glass': '一杯（的量）；玻璃',
    'may': '也许；可能',
    'unhappy': '不快乐的；难过的',
    'video': '视频；录像',
    'money': '钱',
    'pocket money': '零花钱',
    'schoolbag': '书包',
    'drink': '饮料',
    'goods': '商品',
    'haircut': '发型',
    'service': '服务',
    'lucky': '幸运的',
    'microscope': '显微镜',
    'sale': '特价销售；出售',
    'save up': '攒钱',
    'ticket': '票',
    'difficult': '困难的',
    'for example': '例如',
    'half': '一半',
    'jar': '罐子',
    'manage': '管理',
    'sell': '卖；售卖',
    'cloud': '云',
    'daytime': '白天',
    'earth': '地球',
    'marble': '弹子；（玻璃）弹珠',
    'moon': '月球；月亮',
    'ocean': '海洋',
    'outer space': '外太空',
    'space station': '空间站',
    'astronaut': '宇航员；航天员',
    'planet': '行星',
    'sky': '天空',
    'space': '太空；空间',
    'star': '恒星；星',
    'satellite': '人造卫星',
    'alien': '外星生物',
    'Mars': '火星',
    'rover': '探测器',
    'soil': '土壤',
    'sunrise': '日出',
    'into': '进入；到……里',
    'month': '月',
    'spaceship': '宇宙飞船',
    'telescope': '望远镜',
    'cloth': '（一块）布',
    'question': '问题',
    'sunset': '日落',
    'taikonaut': '中国航天员',
    'time': '次；回',
    'toothpaste': '牙膏',
    'electricity': '电',
    'power': '能源；力量',
    'cool': '凉爽的；酷的',
    'energy': '能源；能量',
    'heat': '加热；热量',
    'light': '光',
    'solar': '太阳的',
    'source': '来源',
    'type': '类型；种类',
    'change': '改变',
    'difference': '差别',
    'few': '不多；很少',
    'quick': '迅速的；快的',
    'resource': '资源',
    'run out': '用完',
    'shower': '淋浴',
    'unplug': '拔插头',
    'air conditioner': '空调',
    'bottle': '瓶子',
    'drive': '驾驶',
    'market': '市场；集市',
    'own': '自己的',
    'reduce': '减少',
    'reuse': '再次使用；重复使用',
    'side': '一面；一边',
    'top': '最高的',
    'dirty': '脏的',
    'useful': '有用的；有益的',
}

# PDF 词表与通用 pos 推断冲突时的修正
POS_OVERRIDES: dict[str, str] = {
    'was': 'v.',
    'as': 'prep.',
    'into': 'prep.',
    'for example': 'prep. phrase',
    'may': 'modal v.',
    'ever': 'adv.',
    'soon': 'adv.',
    'later': 'adv.',
    'yesterday': 'n.',
    'half': 'n.',
    'goods': 'n.',
    'haircut': 'n.',
    'sale': 'n.',
    'call': 'v.',
    'dress': 'v.',
    'paste': 'v.',
    'cheer': 'v.',
    'manage': 'v.',
    'sell': 'v.',
    'reduce': 'v.',
    'reuse': 'v.',
    'unplug': 'v.',
    'drive': 'v.',
    'change': 'v.',
    'discuss': 'v.',
    'add': 'v.',
    'cry': 'v.',
    'stay up': 'v. phrase',
    'save up': 'v. phrase',
    'count down': 'v. phrase',
    'run out': 'v. phrase',
    'space station': 'n. phrase',
    'runny nose': 'n. phrase',
    'pocket money': 'n. phrase',
    'outer space': 'n. phrase',
    'air conditioner': 'n. phrase',
    'book fair': 'n. phrase',
    'gingerbread house': 'n. phrase',
    'the red army': 'n. phrase',
    'cool': 'adj.',
    'lucky': 'adj.',
    'difficult': 'adj.',
    'exciting': 'adj.',
    'inspiring': 'adj.',
    'unhappy': 'adj.',
    'useful': 'adj.',
    'quick': 'adj.',
    'dry': 'adj.',
    'ill': 'adj.',
    'better': 'adj.',
    'own': 'adj.',
    'solar': 'adj.',
    'few': 'adj.',
    'another': 'adj.',
    'drink': 'n.',
    'race': 'n.',
    'time': 'n.',
    'power': 'n.',
    'energy': 'n.',
    'heat': 'n.',
    'light': 'n.',
    'view': 'n.',
    'service': 'n.',
    'writer': 'n.',
    'winner': 'n.',
    'marathon': 'n.',
    'gala': 'n.',
    'notice': 'n.',
    'fever': 'n.',
    'cough': 'n.',
    'cold': 'n.',
    'head': 'n.',
    'money': 'n.',
    'ticket': 'n.',
    'jar': 'n.',
    'market': 'n.',
    'shower': 'n.',
    'bottle': 'n.',
    'side': 'n.',
    'type': 'n.',
    'source': 'n.',
    'resource': 'n.',
    'difference': 'n.',
    'question': 'n.',
    'video': 'n.',
    'email': 'n.',
    'glass': 'n.',
    'diet': 'n.',
    'microscope': 'n.',
    'telescope': 'n.',
    'spaceship': 'n.',
    'satellite': 'n.',
    'rover': 'n.',
    'alien': 'n.',
    'taikonaut': 'n.',
    'marble': 'n.',
    'cloth': 'n.',
    'toothpaste': 'n.',
    'electricity': 'n.',
    'kilometre': 'n.',
    'thousand': 'num.',
    'mars': 'n.',
    'paris': 'n.',
    'astronaut': 'n.',
    'top': 'adj.',
    'dirty': 'adj.',
    'judge': 'v.',
    'read': 'v.',
    'sing': 'v.',
    'wear': 'v.',
    'run': 'v.',
    'make': 'v.',
    'win': 'v.',
    'begin': 'v.',
    'wake': 'v.',
}

IPA_OVERRIDES: dict[str, str] = {
    'was': '/wɒz/',
    'climb': '/klaɪm/',
    'kilometre': '/kɪˈlɒmɪtə(r)/',
    'gingerbread house': '/ˈdʒɪndʒəbred haʊs/',
    'new zealand': '/ˌnjuː ˈziːlənd/',
    'send': '/send/',
    'go': '/ɡəʊ/',
    'thousand': '/ˈθaʊznd/',
    'clay': '/kleɪ/',
    'see': '/siː/',
    'village': '/ˈvɪlɪdʒ/',
    'eat': '/iːt/',
    'take': '/teɪk/',
    'view': '/vjuː/',
    'inspiring': '/ɪnˈspaɪərɪŋ/',
    'bamboo': '/ˌbæmˈbuː/',
    'pumpkin': '/ˈpʌmpkɪn/',
    'restaurant': '/ˈrestrɒnt/',
    'airport': '/ˈeəpɔːt/',
    'paris': '/ˈpærɪs/',
    'dry': '/draɪ/',
    'begin': '/bɪˈɡɪn/',
    'judge': '/dʒʌdʒ/',
    'later': '/ˈleɪtə(r)/',
    'notice': '/ˈnəʊtɪs/',
    'wake': '/weɪk/',
    'win': '/wɪn/',
    'winner': '/ˈwɪnə(r)/',
    'ever': '/ˈevə(r)/',
    'paste': '/peɪst/',
    'eiffel tower': '/ˌaɪfəl ˈtaʊə(r)/',
    'terracotta warriors': '/ˌterəˈkɒtə ˈwɒriəz/',
    'book fair': '/bʊk feə(r)/',
    'runny nose': '/ˈrʌni nəʊz/',
    'stay up': '/steɪ ʌp/',
    'pocket money': '/ˈpɒkɪt ˈmʌni/',
    'save up': '/seɪv ʌp/',
    'outer space': '/ˌaʊtə ˈspeɪs/',
    'space station': '/speɪs ˈsteɪʃn/',
    'astronaut': '/ˈæstrənɔːt/',
    'count down': '/kaʊnt daʊn/',
    'run out': '/rʌn aʊt/',
    'hong kong-zhuhai-macao bridge': '/ˌhɒŋ kɒŋ ˌʒuːˈhaɪ məˈkaʊ ˈbrɪdʒ/',
    'jinggangshan revolution museum': '/dʒɪŋˈɡæŋʃæn ˌrevəˈluːʃn mjuːˈziːəm/',
    'the red army': '/ðə red ˈɑːmi/',
    'dress': '/dres/',
    'gala': '/ˈɡɑːlə/',
    'as': '/æz/',
    'cheer': '/tʃɪə(r)/',
    'marathon': '/ˈmærəθən/',
    'race': '/reɪs/',
    'run': '/rʌn/',
    'make': '/meɪk/',
    'read': '/riːd/',
    'sing': '/sɪŋ/',
    'wear': '/weə(r)/',
    'writer': '/ˈraɪtə(r)/',
    'yesterday': '/ˈjestədeɪ/',
    'exciting': '/ɪkˈsaɪtɪŋ/',
    'cold': '/kəʊld/',
    'head': '/hed/',
    'soon': '/suːn/',
    'ill': '/ɪl/',
    'cough': '/kɒf/',
    'fever': '/ˈfiːvə(r)/',
    'discuss': '/dɪˈskʌs/',
    'diet': '/ˈdaɪət/',
    'add': '/æd/',
    'another': '/əˈnʌðə(r)/',
    'better': '/ˈbetə(r)/',
    'call': '/kɔːl/',
    'cry': '/kraɪ/',
    'email': '/ˈiːmeɪl/',
    'glass': '/ɡlɑːs/',
    'may': '/meɪ/',
    'unhappy': '/ʌnˈhæpi/',
    'video': '/ˈvɪdiəʊ/',
    'money': '/ˈmʌni/',
    'schoolbag': '/ˈskuːlbæɡ/',
    'drink': '/drɪŋk/',
    'goods': '/ɡʊdz/',
    'haircut': '/ˈheəkʌt/',
    'service': '/ˈsɜːvɪs/',
    'lucky': '/ˈlʌki/',
    'microscope': '/ˈmaɪkrəskəʊp/',
    'sale': '/seɪl/',
    'ticket': '/ˈtɪkɪt/',
    'difficult': '/ˈdɪfɪkəlt/',
    'for example': '/fɔːr ɪɡˈzɑːmpl/',
    'half': '/hɑːf/',
    'jar': '/dʒɑː(r)/',
    'manage': '/ˈmænɪdʒ/',
    'sell': '/sel/',
    'cloud': '/klaʊd/',
    'daytime': '/ˈdeɪtaɪm/',
    'earth': '/ɜːθ/',
    'marble': '/ˈmɑːbl/',
    'moon': '/muːn/',
    'ocean': '/ˈəʊʃn/',
    'planet': '/ˈplænɪt/',
    'sky': '/skaɪ/',
    'space': '/speɪs/',
    'star': '/stɑː(r)/',
    'satellite': '/ˈsætəlaɪt/',
    'alien': '/ˈeɪliən/',
    'mars': '/mɑːz/',
    'rover': '/ˈrəʊvə(r)/',
    'soil': '/sɔɪl/',
    'sunrise': '/ˈsʌnraɪz/',
    'into': '/ˈɪntuː/',
    'month': '/mʌnθ/',
    'spaceship': '/ˈspeɪsʃɪp/',
    'telescope': '/ˈtelɪskəʊp/',
    'cloth': '/klɒθ/',
    'question': '/ˈkwestʃən/',
    'sunset': '/ˈsʌnset/',
    'taikonaut': '/ˈtaɪkənɔːt/',
    'time': '/taɪm/',
    'toothpaste': '/ˈtuːθpeɪst/',
    'electricity': '/ɪˌlekˈtrɪsəti/',
    'power': '/ˈpaʊə(r)/',
    'cool': '/kuːl/',
    'energy': '/ˈenədʒi/',
    'heat': '/hiːt/',
    'light': '/laɪt/',
    'solar': '/ˈsəʊlə(r)/',
    'source': '/sɔːs/',
    'type': '/taɪp/',
    'change': '/tʃeɪndʒ/',
    'difference': '/ˈdɪfrəns/',
    'few': '/fjuː/',
    'quick': '/kwɪk/',
    'resource': '/rɪˈsɔːs/',
    'shower': '/ˈʃaʊə(r)/',
    'unplug': '/ˌʌnˈplʌɡ/',
    'air conditioner': '/ˈeə kənˌdɪʃənə(r)/',
    'bottle': '/ˈbɒtl/',
    'drive': '/draɪv/',
    'market': '/ˈmɑːkɪt/',
    'own': '/əʊn/',
    'reduce': '/rɪˈdjuːs/',
    'reuse': '/ˌriːˈjuːs/',
    'side': '/saɪd/',
    'top': '/tɒp/',
    'dirty': '/ˈdɜːti/',
    'useful': '/ˈjuːsfl/',
}


def _secondary_mnemonic(key: str, headword: str, definition_zh: str, *, kind: str) -> str | None:
    if key in ROOT_MNEMONICS:
        return f'拆词联想：{ROOT_MNEMONICS[key]}'
    if key in IMAGE_MNEMONICS:
        return f'形象联想：{IMAGE_MNEMONICS[key]}'
    if key in SEMANTIC_MNEMONICS:
        return f'语义联想：{SEMANTIC_MNEMONICS[key]}'

    short = definition_zh.split('；')[0].split('，')[0].strip()
    if kind == 'phrase':
        return f'语义联想：{headword} 表示「{short}」，在课文对话里反复出现。'
    return f'语义联想：{headword} 表示「{short}」，结合本课例句记忆。'


def mnemonic_for(headword: str, definition_zh: str, *, kind: str) -> str:
    key = headword.lower()
    parts: list[str] = []

    if key in SOUND_MNEMONICS:
        parts.append(f'谐音联想：{SOUND_MNEMONICS[key]}')

    secondary = _secondary_mnemonic(key, headword, definition_zh, kind=kind)
    if secondary:
        if parts:
            if secondary not in parts[0]:
                parts.append(secondary)
        else:
            parts.append(secondary)

    return parts[0] if len(parts) == 1 else '\n'.join(parts)
