"""Mnemonics and inflection notes for PEP Grade 6 English, Volume 2 (下册).

谐音规则与 en-grade3-v2-rj 一致：仅真实谐音，不硬凑；优先语义/形象/拆词联想。
"""

from __future__ import annotations

# 谐音联想：仅 headword 与中文读音确有相似处才写。
SOUND_MNEMONICS: dict[str, str] = {
    'hall': 'hall 音近「霍尔」，hall 是大厅。',
    'than': 'than 音近「赞」，A is taller than B 就是 A 比 B 更……',
    'both': 'both 音近「波思」，both 是两者都。',
    'kilogram': 'kilogram 音近「千克」，kilogram 就是千克。',
    'lamp': 'lamp 音近「兰普」，lamp 是灯。',
    'loud': 'loud 音近「劳德」，loud 是响亮的。',
    'hotel': 'hotel 音近「后 tell」，hotel 是旅馆。',
    'magazine': 'magazine 音近「麦格azine」，magazine 是杂志。',
    'gift': 'gift 音近「给夫特」，gift 是礼物。',
    'beach': 'beach 音近「比奇」，beach 是海滩。',
    'basket': 'basket 音近「巴斯ket」，basket 是篮子。',
    'grass': 'grass 音近「格拉斯」，grass 是草。',
    'gym': 'gym 音近「吉姆」，gym 是体育馆。',
    'ago': 'ago 音近「阿 go」，long ago 是很久以前。',
    'easy': 'easy 音近「伊 zi」，easy 是容易的。',
    'star': 'star 音近「斯达」，star 是星、明星。',
    'dream': 'dream 音近「追姆」，dream 是梦。',
    'turpan': 'Turpan 音近「吐鲁番」，Turpan 就是吐鲁番。',
    'cheetah': 'cheetah 音近「奇塔」，cheetah 是猎豹。',
    'mule': 'mule 音近「谬尔」，mule 是骡子。',
    'part': 'part 音近「帕特」，part 是部分、角色。',
    'till': 'till 音近「提尔」，till 是直到。',
    'enjoy': 'enjoy 音近「因 joy」，enjoy 是因喜欢而享受。',
    'race': 'race 音近「瑞斯」，race 是赛跑。',
    'yesterday': 'yesterday 音近「耶斯特 day」，yesterday 是昨天。',
    'show': 'show 音近「秀」，a show 是一场演出。',
}

ROOT_MNEMONICS: dict[str, str] = {
    'younger': 'young 年轻 + er 比较级，younger 是更年轻的。',
    'older': 'old 年长 + er 比较级，older 是更年长的；更旧的。',
    'taller': 'tall 高 + er 比较级，taller 是更高的。',
    'shorter': 'short 矮/短 + er 比较级，shorter 是更矮的；更短的。',
    'longer': 'long 长 + er 比较级，longer 是更长的。',
    'thinner': 'thin 瘦/薄 + er 比较级，thinner 是更瘦的；更薄的。',
    'heavier': 'heavy 重 + er 比较级，heavier 是更重的。',
    'bigger': 'big 大 + er 比较级，bigger 是更大的。',
    'smaller': 'small 小 + er 比较级，smaller 是更小的。',
    'stronger': 'strong 强壮 + er 比较级，stronger 是更强壮的。',
    'lower': 'low 低 + er 比较级，lower 是更低的。',
    'smarter': 'smart 聪明 + er 比较级，smarter 是更聪明的。',
    'dining hall': 'dining 用餐 + hall 大厅，dining hall 是食堂。',
    'had a cold': 'had 有 + a cold 感冒，had a cold 是感冒了。',
    'went fishing': 'went 去 + fishing 钓鱼，went fishing 是去钓鱼了。',
    'went camping': 'went 去 + camping 野营，went camping 是去野营了。',
    'took pictures': 'took 拿/拍 + pictures 照片，took pictures 是拍了照。',
    'go cycling': 'go 去 + cycling 骑车，go cycling 是去骑自行车。',
    'look up': 'look 看 + up 向上，look up 是在词典或网上查阅。',
    'ice-skate': 'ice 冰 + skate 滑，ice-skate 是滑冰。',
    'kilogram': 'kilo 千 + gram 克，kilogram 是千克。',
    'countryside': 'country 乡村 + side 边，countryside 是乡村、乡下。',
    'become': 'be 成为 + come 来，become 是变成、成为。',
    'before': 'be 在 + fore 前，before 是在……之前。',
    'better': 'good/well 的比较级，better 是更好的；好转的。',
    'faster': 'fast 快 + er 比较级，faster 是更快的。',
    'broken': 'break 打破 + en，broken 是损坏的、破碎的。',
    'internet': 'inter 互相 + net 网，Internet 是互联网。',
    'different': 'differ 不同 + ent，different 是不同的。',
    'active': 'act 行动 + ive，active 是活跃的。',
    'nothing': 'no 没有 + thing 东西，nothing 是没有东西、什么也没有。',
}

IMAGE_MNEMONICS: dict[str, str] = {
    'dinosaur': '想象 dinosaur 博物馆里巨大的恐龙骨架。',
    'meter': '想象 meter 用米尺量 hall 的高度。',
    'shadow': '想象 shadow 傍晚在地上拉得长长的。',
    'cleaned': '想象 cleaned 周末把房间打扫得干干净净。',
    'washed': '想象 washed 在水龙头下洗衣服。',
    'watched': '想象 watched 坐在沙发上看 TV show。',
    'slept': '想象 slept 盖着被子睡了一整晚。',
    'read': '想象 read 在 lamp 下读 magazine。',
    'saw': '想象 saw 用眼睛看到 stars 或 show。',
    'drank': '想象 drank 跑步后咕咚咕咚喝水。',
    'fixed': '想象 fixed 用工具修好 broken lamp。',
    'lamp': '想象 lamp 台灯照亮 read 的书页。',
    'stay': '想象 stay 拖着行李箱住进 hotel。',
    'went': '想象 went 背着包走向 Turpan 或 beach。',
    'camp': '想象 camp 在河边搭帐篷过夜。',
    'fish': '想象 fish 坐在湖边甩鱼竿钓鱼。',
    'rode': '想象 rode 骑在 mule 背上慢慢上山。',
    'hurt': '想象 hurt 摔下来捂着脚喊疼。',
    'ate': '想象 ate 从 basket 里拿葡萄吃。',
    'took': '想象 took 举起相机 took pictures。',
    'bought': '想象 bought 在商店挑选 gift。',
    'fell': '想象 fell 从 mule 上 fell off 摔下来。',
    'off': '想象 off 帽子从头上 off 掉下来。',
    'licked': '想象 licked 小狗舔手的画面。',
    'laughed': '想象 laughed 听笑话笑出声。',
    'grass': '想象 grass 操场上绿绿的草坪。',
    'gym': '想象 gym 室内打 badminton 或做运动。',
    'cycling': '想象 cycling 骑车穿过公园。',
    'badminton': '想象 badminton 羽毛球在 gym 里飞来飞去。',
    'cheetah': '想象 cheetah 在 race 里跑得飞快。',
    'trip': '想象 trip 被石头绊一下差点摔倒。',
    'woke': '想象 woke 闹钟响后从 dream 里醒来。',
    'dream': '想象 dream 梦见 cheetah 在跑 race。',
    'dining hall': '想象 dining hall 排队打饭的热闹场面。',
    'magazine': '想象 magazine 封面彩色图片和文章。',
    'hotel': '想象 hotel 旅行时入住的房间和 lamp。',
    'beach': '想象 beach 沙地、阳光和拍照片。',
    'basket': '想象 basket 提着装满葡萄的篮子。',
    'mule': '想象 mule 在 Turpan 驮着游客慢慢走。',
}

SEMANTIC_MNEMONICS: dict[str, str] = {
    'younger': 'My sister is younger than me. younger 是比较级，更年轻的。',
    'older': 'My brother is older than me. older 是比较级，更年长的。',
    'taller': 'John is taller than Mike. taller 是比较级，更高的。',
    'shorter': 'I am shorter than my dad. shorter 是比较级，更矮的。',
    'longer': 'My shadow is longer in the evening. longer 是比较级，更长的。',
    'thinner': 'The book is thinner than the dictionary. thinner 是比较级，更薄的。',
    'heavier': 'The bag is heavier than yesterday. heavier 是比较级，更重的。',
    'bigger': 'The dinosaur was bigger than a bus. bigger 是比较级，更大的。',
    'smaller': 'The mouse is smaller than the cat. smaller 是比较级，更小的。',
    'stronger': 'Exercise makes you stronger. stronger 是比较级，更强壮的。',
    'dinosaur': 'The dinosaur lived long ago. dinosaur 是恐龙。',
    'hall': 'We measured the hall together. hall 是大厅。',
    'meter': 'The hall is five meters tall. meter 是米（长度单位）。',
    'than': 'I am taller than you. than 用于比较，比。',
    'both': 'Both of them are taller than me. both 是两者都。',
    'kilogram': 'The bag weighs two kilograms. kilogram 是千克。',
    'countryside': 'My grandparents live in the countryside. countryside 是乡村。',
    'lower': 'The sun is lower in the winter sky. lower 是比较级，更低的。',
    'shadow': 'Look at your shadow on the ground. shadow 是影子。',
    'smarter': 'Reading makes you smarter. smarter 是比较级，更聪明的。',
    'become': 'Days become longer in spring. become 是变成、成为。',
    'cleaned': 'I cleaned my room last weekend. cleaned 是 clean 的过去式，打扫了。',
    'stayed': 'I stayed at home last Sunday. stayed 是 stay 的过去式，停留了。',
    'washed': 'I washed my clothes yesterday. washed 是 wash 的过去式，洗了。',
    'watched': 'We watched a show on TV. watched 是 watch 的过去式，观看了。',
    'had': 'I had a good time last weekend. had 是 have 的过去式。',
    'had a cold': 'I had a cold last week. had a cold 是感冒了。',
    'slept': 'I slept for ten hours last night. slept 是 sleep 的过去式，睡了。',
    'read': 'I read a magazine yesterday. read 过去式读 /red/，与现在式拼写相同。',
    'saw': 'I saw a film last Saturday. saw 是 see 的过去式，看见了。',
    'last': 'Last weekend was very busy. last 是上一个、刚过去的。',
    'yesterday': 'I washed my clothes yesterday. yesterday 是昨天。',
    'before': 'Wash your hands before dinner. before 是在……之前。',
    'drank': 'I drank some water after running. drank 是 drink 的过去式，喝了。',
    'show': 'We watched a show on TV. show 这里作名词，演出。',
    'magazine': 'I read an English magazine. magazine 是杂志。',
    'better': 'I feel better today. better 是 good/well 的比较级，更好的。',
    'faster': 'He runs faster than his friend. faster 是 fast 的比较级，更快的。',
    'hotel': 'We stayed in a hotel last weekend. hotel 是旅馆。',
    'fixed': 'Dad fixed the broken lamp. fixed 是 fix 的过去式，修好了。',
    'broken': 'The lamp is broken. broken 是损坏的、破碎的。',
    'lamp': 'Turn on the lamp, please. lamp 是灯。',
    'loud': 'The music is too loud. loud 是响亮的、大声的。',
    'enjoy': 'Did you enjoy the show? enjoy 是享受、喜欢。',
    'stay': 'Did you stay at home last weekend? stay 是停留、暂住。',
    'went': 'We went to Turpan last summer. went 是 go 的过去式，去了。',
    'camp': 'We camp by the river in summer. camp 是露营。',
    'fish': 'My grandpa likes to fish by the lake. fish 作动词，钓鱼；捕鱼。',
    'went fishing': 'We went fishing last Sunday. went fishing 是去钓鱼了。',
    'went camping': 'We went camping in the mountains. went camping 是去野营了。',
    'rode': 'I rode a mule in Turpan. rode 是 ride 的过去式，骑了。',
    'hurt': 'I hurt my foot on the trip. hurt 过去式不变，弄伤了、疼。',
    'ate': 'We ate fresh fruit in Turpan. ate 是 eat 的过去式，吃了。',
    'took': 'I took many pictures at the beach. took 是 take 的过去式，拿了、拍了。',
    'took pictures': 'We took pictures of the mule. took pictures 是拍了照。',
    'bought': 'I bought a gift for my mum. bought 是 buy 的过去式，买了。',
    'gift': 'This gift is for you. gift 是礼物。',
    'fell': 'I fell off the mule. fell 是 fall 的过去式，摔倒了。',
    'off': 'I fell off the bike. off 是从……落下、离开。',
    'mule': 'I rode a mule in Turpan. mule 是骡子。',
    'turpan': 'We went to Turpan on holiday. Turpan 是吐鲁番。',
    'could': 'I could ride a bike when I was six. could 是 can 的过去式，能够。',
    'till': 'We camped till Sunday. till 是直到……为止。',
    'beach': 'We played on the beach all day. beach 是海滩。',
    'basket': 'She carried a basket of grapes. basket 是篮子。',
    'part': 'I played a small part in the school show. part 是角色、部分。',
    'licked': 'The dog licked my hand. licked 是 lick 的过去式，舔了。',
    'laughed': 'We laughed at the funny story. laughed 是 laugh 的过去式，笑了。',
    'dining hall': 'We eat lunch in the dining hall. dining hall 是食堂。',
    'grass': 'There is green grass on the playground. grass 是草、草地。',
    'gym': 'We have PE class in the gym. gym 是体育馆。',
    'ago': 'Long ago, there was no Internet at school. ago 是……以前。',
    'cycling': 'Cycling is good exercise. cycling 是骑自行车运动。',
    'go cycling': 'We go cycling on Sundays. go cycling 是去骑自行车。',
    'look up': 'Look up the word in the dictionary. look up 是查阅。',
    'ice-skate': 'I can ice-skate in winter. ice-skate 是滑冰。',
    'badminton': 'We play badminton in the gym. badminton 是羽毛球。',
    'star': 'She is a star in our class. star 是星、明星。',
    'easy': 'The race was easy for him. easy 是容易的。',
    'internet': 'We use the Internet to study now. Internet 是互联网。',
    'different': 'School is different from before. different 是不同的。',
    'active': 'She is very active in class. active 是活跃的。',
    'race': 'We had a race on the playground. race 是赛跑。',
    'nothing': 'There was nothing on the grass before. nothing 是没有东西。',
    'thought': 'I thought school was boring before. thought 是 think 的过去式，认为。',
    'felt': 'I felt happy after the race. felt 是 feel 的过去式，感到。',
    'cheetah': 'The cheetah runs faster than a lion. cheetah 是猎豹。',
    'trip': 'Be careful! Do not trip on the grass. trip 是绊倒。',
    'woke': 'I woke up early this morning. woke 是 wake 的过去式，醒了。',
    'dream': 'I had a dream about the cheetah. dream 是梦。',
}

INFLECTION_NOTES: dict[str, str] = {
    'younger': 'young 的比较级；最高级 youngest',
    'older': 'old 的比较级；最高级 oldest',
    'taller': 'tall 的比较级；最高级 tallest',
    'shorter': 'short 的比较级；最高级 shortest',
    'longer': 'long 的比较级；最高级 longest',
    'thinner': 'thin 的比较级；最高级 thinnest',
    'heavier': 'heavy 的比较级；最高级 heaviest',
    'bigger': 'big 的比较级；最高级 biggest',
    'smaller': 'small 的比较级；最高级 smallest',
    'stronger': 'strong 的比较级；最高级 strongest',
    'lower': 'low 的比较级；最高级 lowest',
    'smarter': 'smart 的比较级；最高级 smartest',
    'better': 'good/well 的比较级；最高级 best',
    'faster': 'fast 的比较级；最高级 fastest',
    'become': '第三人称单数 becomes；过去式 became',
    'cleaned': 'clean 的过去式；第三人称单数 cleans',
    'stayed': 'stay 的过去式；第三人称单数 stays',
    'washed': 'wash 的过去式；第三人称单数 washes',
    'watched': 'watch 的过去式；第三人称单数 watches',
    'had': 'have 的过去式；第三人称单数 has',
    'slept': 'sleep 的过去式；第三人称单数 sleeps',
    'read': '过去式 read /red/；第三人称单数 reads /riːdz/',
    'saw': 'see 的过去式；第三人称单数 sees',
    'drank': 'drink 的过去式；第三人称单数 drinks',
    'fixed': 'fix 的过去式；第三人称单数 fixes',
    'went': 'go 的过去式；第三人称单数 goes',
    'fish': '第三人称单数 fishes；过去式 fished',
    'rode': 'ride 的过去式；第三人称单数 rides',
    'hurt': '过去式 hurt 不变；第三人称单数 hurts',
    'ate': 'eat 的过去式；第三人称单数 eats',
    'took': 'take 的过去式；第三人称单数 takes',
    'bought': 'buy 的过去式；第三人称单数 buys',
    'fell': 'fall 的过去式；第三人称单数 falls',
    'could': 'can 的过去式',
    'licked': 'lick 的过去式；第三人称单数 licks',
    'laughed': 'laugh 的过去式；第三人称单数 laughs',
    'thought': 'think 的过去式；第三人称单数 thinks',
    'felt': 'feel 的过去式；第三人称单数 feels',
    'woke': 'wake 的过去式；第三人称单数 wakes',
    'trip': '第三人称单数 trips；过去式 tripped',
    'ice-skate': '第三人称单数 ice-skates；过去式 ice-skated',
    'stay': '第三人称单数 stays；过去式 stayed',
    'enjoy': '第三人称单数 enjoys；过去式 enjoyed',
    'camp': '第三人称单数 camps；过去式 camped',
    'dream': '第三人称单数 dreams；过去式 dreamed/dreamt',
    'meter': '英式拼写 metre；复数 meters/metres',
    'kilogram': '复数 kilograms',
    'dinosaur': '复数 dinosaurs',
    'magazine': '复数 magazines',
}

DEFINITION_OVERRIDES: dict[str, str] = {
    'younger': '更年轻的',
    'older': '更年长的；更旧的',
    'taller': '更高的',
    'shorter': '更矮的；更短的',
    'longer': '更长的',
    'thinner': '更瘦的；更薄的',
    'heavier': '更重的',
    'bigger': '更大的',
    'smaller': '更小的',
    'stronger': '更强壮的',
    'dinosaur': '恐龙',
    'hall': '大厅',
    'meter': '米（metre）',
    'than': '比',
    'both': '两者都',
    'kilogram': '千克',
    'countryside': '乡村',
    'lower': '更低的',
    'shadow': '影子',
    'smarter': '更聪明的',
    'become': '变成；成为',
    'cleaned': '打扫（过去式）',
    'stayed': '停留；暂住（过去式）',
    'washed': '洗（过去式）',
    'watched': '观看（过去式）',
    'had': '有；经历（过去式）',
    'had a cold': '感冒',
    'slept': '睡觉（过去式）',
    'read': '阅读（过去式）',
    'saw': '看见（过去式）',
    'last': '上一个；刚过去的',
    'yesterday': '昨天',
    'before': '在……之前',
    'drank': '喝（过去式）',
    'show': '演出',
    'magazine': '杂志',
    'better': '更好的；好转的',
    'faster': '更快的',
    'hotel': '旅馆',
    'fixed': '修理（过去式）',
    'broken': '损坏的；破碎的',
    'lamp': '灯',
    'loud': '响亮的；大声的',
    'enjoy': '享受；喜欢',
    'stay': '停留；暂住',
    'went': '去（过去式）',
    'camp': '露营',
    'fish': '钓鱼；捕鱼',
    'went fishing': '去钓鱼',
    'went camping': '去野营',
    'rode': '骑（过去式）',
    'hurt': '弄伤；感到疼',
    'ate': '吃（过去式）',
    'took': '拿；带；拍（过去式）',
    'took pictures': '拍照',
    'bought': '买（过去式）',
    'gift': '礼物',
    'fell': '摔倒（过去式）',
    'off': '从……落下；离开',
    'mule': '骡子',
    'Turpan': '吐鲁番',
    'could': '能；会（过去式）',
    'till': '直到……为止',
    'beach': '海滩',
    'basket': '篮子',
    'part': '角色；部分',
    'licked': '舔（过去式）',
    'laughed': '笑（过去式）',
    'dining hall': '食堂',
    'grass': '草；草地',
    'gym': '体育馆',
    'ago': '……以前',
    'cycling': '骑自行车运动',
    'go cycling': '去骑自行车',
    'ice-skate': '滑冰',
    'badminton': '羽毛球',
    'star': '星；明星',
    'easy': '容易的',
    'look up': '查阅',
    'Internet': '互联网',
    'different': '不同的',
    'active': '活跃的',
    'race': '赛跑',
    'nothing': '没有什么；没有东西',
    'thought': '想；认为（过去式）',
    'felt': '感到（过去式）',
    'cheetah': '猎豹',
    'trip': '绊倒',
    'woke': '醒来（过去式）',
    'dream': '梦',
}

POS_OVERRIDES: dict[str, str] = {
    'younger': 'adj.',
    'older': 'adj.',
    'taller': 'adj.',
    'shorter': 'adj.',
    'longer': 'adj.',
    'thinner': 'adj.',
    'heavier': 'adj.',
    'bigger': 'adj.',
    'smaller': 'adj.',
    'stronger': 'adj.',
    'lower': 'adj.',
    'smarter': 'adj.',
    'better': 'adj.',
    'faster': 'adj.',
    'broken': 'adj.',
    'loud': 'adj.',
    'easy': 'adj.',
    'different': 'adj.',
    'active': 'adj.',
    'last': 'adj.',
    'yesterday': 'adv.',
    'before': 'prep.',
    'than': 'conj.',
    'both': 'pron.',
    'off': 'adv.',
    'ago': 'adv.',
    'till': 'conj.',
    'nothing': 'pron.',
    'cleaned': 'v.',
    'stayed': 'v.',
    'washed': 'v.',
    'watched': 'v.',
    'had': 'v.',
    'slept': 'v.',
    'read': 'v.',
    'saw': 'v.',
    'drank': 'v.',
    'fixed': 'v.',
    'enjoy': 'v.',
    'stay': 'v.',
    'went': 'v.',
    'camp': 'v.',
    'fish': 'v.',
    'rode': 'v.',
    'hurt': 'v.',
    'ate': 'v.',
    'took': 'v.',
    'bought': 'v.',
    'fell': 'v.',
    'could': 'modal v.',
    'licked': 'v.',
    'laughed': 'v.',
    'thought': 'v.',
    'felt': 'v.',
    'woke': 'v.',
    'trip': 'v.',
    'become': 'v.',
    'ice-skate': 'v.',
    'cycling': 'n.',
    'show': 'n.',
    'race': 'n.',
    'dream': 'n.',
    'star': 'n.',
    'part': 'n.',
    'gift': 'n.',
    'magazine': 'n.',
    'hotel': 'n.',
    'lamp': 'n.',
    'dinosaur': 'n.',
    'hall': 'n.',
    'meter': 'n.',
    'kilogram': 'n.',
    'countryside': 'n.',
    'shadow': 'n.',
    'mule': 'n.',
    'beach': 'n.',
    'basket': 'n.',
    'grass': 'n.',
    'gym': 'n.',
    'badminton': 'n.',
    'cheetah': 'n.',
    'turpan': 'n.',
    'internet': 'n.',
    'dining hall': 'n. phrase',
    'had a cold': 'v. phrase',
    'went fishing': 'v. phrase',
    'went camping': 'v. phrase',
    'took pictures': 'v. phrase',
    'go cycling': 'v. phrase',
    'look up': 'v. phrase',
}

IPA_OVERRIDES: dict[str, str] = {
    'younger': '/ˈjʌŋɡə(r)/',
    'older': '/ˈəʊldə(r)/',
    'taller': '/ˈtɔːlə(r)/',
    'shorter': '/ˈʃɔːtə(r)/',
    'longer': '/ˈlɒŋɡə(r)/',
    'thinner': '/ˈθɪnə(r)/',
    'heavier': '/ˈheviə(r)/',
    'bigger': '/ˈbɪɡə(r)/',
    'smaller': '/ˈsmɔːlə(r)/',
    'stronger': '/ˈstrɒŋɡə(r)/',
    'dinosaur': '/ˈdaɪnəsɔː(r)/',
    'hall': '/hɔːl/',
    'meter': '/ˈmiːtə(r)/',
    'than': '/ðæn/',
    'both': '/bəʊθ/',
    'kilogram': '/ˈkɪləɡræm/',
    'countryside': '/ˈkʌntrisaɪd/',
    'lower': '/ˈləʊə(r)/',
    'shadow': '/ˈʃædəʊ/',
    'smarter': '/ˈsmɑːtə(r)/',
    'become': '/bɪˈkʌm/',
    'cleaned': '/kliːnd/',
    'stayed': '/steɪd/',
    'washed': '/wɒʃt/',
    'watched': '/wɒtʃt/',
    'had': '/hæd/',
    'had a cold': '/hæd ə kəʊld/',
    'slept': '/slept/',
    'read': '/red/',
    'saw': '/sɔː/',
    'last': '/lɑːst/',
    'yesterday': '/ˈjestədeɪ/',
    'before': '/bɪˈfɔː(r)/',
    'drank': '/dræŋk/',
    'show': '/ʃəʊ/',
    'magazine': '/ˌmæɡəˈziːn/',
    'better': '/ˈbetə(r)/',
    'faster': '/ˈfɑːstə(r)/',
    'hotel': '/həʊˈtel/',
    'fixed': '/fɪkst/',
    'broken': '/ˈbrəʊkən/',
    'lamp': '/læmp/',
    'loud': '/laʊd/',
    'enjoy': '/ɪnˈdʒɔɪ/',
    'stay': '/steɪ/',
    'went': '/went/',
    'camp': '/kæmp/',
    'fish': '/fɪʃ/',
    'went fishing': '/went ˈfɪʃɪŋ/',
    'went camping': '/went ˈkæmpɪŋ/',
    'rode': '/rəʊd/',
    'hurt': '/hɜːt/',
    'ate': '/et/',
    'took': '/tʊk/',
    'took pictures': '/tʊk ˈpɪktʃəz/',
    'bought': '/bɔːt/',
    'gift': '/ɡɪft/',
    'fell': '/fel/',
    'off': '/ɒf/',
    'mule': '/mjuːl/',
    'turpan': '/ˈtʊəpɑːn/',
    'could': '/kʊd/',
    'till': '/tɪl/',
    'beach': '/biːtʃ/',
    'basket': '/ˈbɑːskɪt/',
    'part': '/pɑːt/',
    'licked': '/lɪkt/',
    'laughed': '/lɑːft/',
    'dining hall': '/ˈdaɪnɪŋ hɔːl/',
    'grass': '/ɡrɑːs/',
    'gym': '/dʒɪm/',
    'ago': '/əˈɡəʊ/',
    'cycling': '/ˈsaɪklɪŋ/',
    'go cycling': '/ɡəʊ ˈsaɪklɪŋ/',
    'ice-skate': '/ˈaɪs skeɪt/',
    'badminton': '/ˈbædmɪntən/',
    'star': '/stɑː(r)/',
    'easy': '/ˈiːzi/',
    'look up': '/lʊk ʌp/',
    'internet': '/ˈɪntənet/',
    'different': '/ˈdɪfrənt/',
    'active': '/ˈæktɪv/',
    'race': '/reɪs/',
    'nothing': '/ˈnʌθɪŋ/',
    'thought': '/θɔːt/',
    'felt': '/felt/',
    'cheetah': '/ˈtʃiːtə/',
    'trip': '/trɪp/',
    'woke': '/wəʊk/',
    'dream': '/driːm/',
}


def _secondary_mnemonic(key: str, headword: str, definition_zh: str, *, kind: str) -> str | None:
    if key in ROOT_MNEMONICS:
        return f'拆词联想：{ROOT_MNEMONICS[key]}'
    if key in IMAGE_MNEMONICS:
        return f'形象联想：{IMAGE_MNEMONICS[key]}'
    if key in SEMANTIC_MNEMONICS:
        return f'语义联想：{SEMANTIC_MNEMONICS[key]}'

    short = definition_zh.split('；')[0].split('，')[0].strip()
    if kind == 'phrase':
        return f'语义联想：{headword} 表示「{short}」，在课文对话里反复出现。'
    return f'语义联想：{headword} 表示「{short}」，结合本课例句记忆。'


def mnemonic_for(headword: str, definition_zh: str, *, kind: str) -> str:
    key = headword.lower()
    parts: list[str] = []

    if key in SOUND_MNEMONICS:
        parts.append(f'谐音联想：{SOUND_MNEMONICS[key]}')

    secondary = _secondary_mnemonic(key, headword, definition_zh, kind=kind)
    if secondary:
        if parts:
            if secondary not in parts[0]:
                parts.append(secondary)
        else:
            parts.append(secondary)

    return parts[0] if len(parts) == 1 else '\n'.join(parts)
