"""Mnemonics and inflection notes for 闽教版 Grade 6 English, Volume 2 (下册).

谐音规则：仅真实谐音，不硬凑；优先语义/形象/拆词联想。
"""

from __future__ import annotations

SOUND_MNEMONICS: dict[str, str] = {
    'along': 'along 音近「阿龙」，阿龙 walk along 沿着走。',
    'anywhere': 'anywhere 音近「埃尼威尔」，埃尼威尔 go anywhere 任何地方。',
    'famous': 'famous 音近「费默斯」，费默斯说 famous 著名。',
    'fat': 'fat 音近「法特」，法特 is fat 胖的。',
    'hear': 'hear 音近「希尔」，希尔 hear 听见。',
    'heavy': 'heavy 音近「海维」，海维 carry heavy 重的。',
    'hope': 'hope 音近「厚普」，厚普 hope 希望。',
    'lesson': 'lesson 音近「莱森」，莱森上 lesson 课。',
    'light': 'light 音近「莱特」，莱特拿 light 轻的。',
    'soon': 'soon 音近「苏恩」，苏恩 hope soon 不久。',
    'cross': 'cross 音近「克罗斯」，克罗斯 cross 横穿。',
    'doctor': 'doctor 音近「道克特」，道克特是 doctor 医生。',
    'fever': 'fever 音近「菲弗」，菲弗 have fever 发烧。',
    'ill': 'ill 音近「伊尔」，伊尔 feel ill 生病。',
    'medicine': 'medicine 音近「麦德森」，麦德森 take medicine 吃药。',
    'must': 'must 音近「马斯特」，马斯特说 must 必须。',
    'open': 'open 音近「欧喷」，欧喷 open 打开。',
    'street': 'street 音近「斯特里特」，斯特里特 cross street 过马路。',
    'kiss': 'kiss 音近「基斯」，基斯 kiss 亲吻。',
    'love': 'love 音近「拉夫」，拉夫 love 爱。',
    'restaurant': 'restaurant 音近「瑞斯托朗」，瑞斯托朗在 restaurant 餐馆。',
    'surprise': 'surprise 音近「瑟普莱斯」，瑟普莱斯 give surprise 惊喜。',
    'cook': 'cook 音近「库克」，库克是 cook 厨师。',
    'farmer': 'farmer 音近「法默」，法默是 farmer 农民。',
    'grow': 'grow 音近「格柔」，格柔 grow 种植。',
    'job': 'job 音近「乔布」，乔布找 job 工作。',
    'nurse': 'nurse 音近「讷斯」，讷斯是 nurse 护士。',
    'singer': 'singer 音近「辛格」，辛格是 singer 歌手。',
    'worker': 'worker 音近「沃克」，沃克是 worker 工人。',
    'driver': 'driver 音近「德莱弗」，德莱弗是 driver 司机。',
    'learn': 'learn 音近「勒恩」，勒恩 learn 学习。',
    'scientist': 'scientist 音近「赛恩提斯特」，赛恩提斯特是 scientist 科学家。',
    'true': 'true 音近「楚」，楚说 true 确实。',
    'bottle': 'bottle 音近「博头」，博头拿 bottle 瓶子。',
    'chemistry': 'chemistry 音近「凯米斯特里」，凯米斯特里学 chemistry 化学。',
    'geography': 'geography 音近「吉奥格拉菲」，吉奥格拉菲学 geography 地理。',
    'history': 'history 音近「希斯托里」，希斯托里学 history 历史。',
    'physics': 'physics 音近「菲兹克斯」，菲兹克斯学 physics 物理。',
    'study': 'study 音近「斯塔迪」，斯塔迪 study 学习。',
    'subject': 'subject 音近「萨布杰克特」，萨布杰克特学 subject 科目。',
    'address': 'address 音近「阿德瑞斯」，阿德瑞斯写 address 地址。',
    'leave': 'leave 音近「里夫」，里夫 leave 离开。',
    'miss': 'miss 音近「密斯」，密斯 miss 想念。',
}

ROOT_MNEMONICS: dict[str, str] = {
    'go back': 'go 去 + back 回，go back 是回到。',
    'ice and snow festival': 'Ice 冰 + Snow 雪 + Festival 节，Ice and Snow Festival 是冰雪节。',
    'the yangtze river': 'Yangtze 长江 + River 河，the Yangtze River 是长江。',
    'a lot of': 'a lot 大量 + of 的，a lot of 是大量的。',
    'have a cold': 'have 有 + a cold 感冒，have a cold 是感冒。',
    "mustn't = must not": 'must 必须 + not 不，must not 是不允许。',
    'dining room': 'dining 用餐 + room 房间，dining room 是餐厅。',
    'police officer': 'police 警察 + officer 官员，police officer 是警察。',
    'middle school': 'middle 中间 + school 学校，middle school 是中学。',
    "teachers' office": 'teachers 教师 + office 办公室，teachers\' office 是教师办公室。',
    'year book': 'year 年 + book 书，year book 是毕业留念册。',
}

IMAGE_MNEMONICS: dict[str, str] = {
    'travel': '想象 travel 旅行沿 the Yangtze River 长江。',
    'famous': '想象 famous 著名的 Ice and Snow Festival 冰雪节。',
    'fat': '想象 fat 胖的 panda 和 thin 瘦的 cat 对比。',
    'thin': '想象 thin 瘦的 ice 冰 along 沿江。',
    'the yangtze river': '想象 the Yangtze River 长江上 travel 旅行。',
    'ice and snow festival': '想象 Ice and Snow Festival 冰雕 snow 雪。',
    'heavy': '想象 carry heavy 重包和 light 轻包对比。',
    'light': '想象 light 轻的 bag 和 heavy 重的 box 对比。',
    'doctor': '想象 doctor 医生在 hospital 给 ill 病人开 medicine。',
    'medicine': '想象 doctor 给 fever 病人 medicine 药。',
    'dining room': '想象 Mother\'s Day 在 dining room 吃 surprise 晚餐。',
    'restaurant': '想象 restaurant 餐馆里 cook 厨师做饭。',
    'farmer': '想象 farmer 农民在 farm grow 种 vegetables。',
    'lab': '想象 scientist 在 lab 实验室做 chemistry 实验。',
    'edison': '想象 Edison 爱迪生在 lab 发明 light bulb。',
    'inventor': '想象 inventor 发明家 Edison 在 lab 工作。',
    'year book': '想象 year book 毕业留念册上有同学 address 地址。',
}

SEMANTIC_MNEMONICS: dict[str, str] = {
    'made': 'She made a snow sculpture. made 是 make 的过去式，制作了。',
    'show': 'Show me your photos. show 是给……看。',
    'break': 'Do not break your leg. break 是摔断，过去式 broke。',
    'carry': 'Carry this heavy bag. carry 是携带、搬运。',
    'feel': 'I feel better soon. feel 是感觉到。',
    'headache': 'I have a headache. headache 是头疼。',
    'toothache': 'I have a toothache. toothache 是牙疼。',
    'wrong': 'Something is wrong. wrong 是不正常、不对。',
    'kind': 'What kind of food? kind 是种、类。',
    'dancer': 'She wants to be a dancer. dancer 是舞蹈演员。',
    'gave': 'She gave me her year book. gave 是 give 的过去式，给了。',
    'information': 'Write your information. information 是信息。',
}

INFLECTION_NOTES: dict[str, str] = {
    'along': '可作介词或副词',
    'anywhere': '常用于否定句和疑问句',
    'famous': '比较级 more famous；最高级 most famous',
    'fat': '比较级 fatter；最高级 fattest',
    'made': 'make 的过去式',
    'show': '第三人称单数 shows；过去式 showed',
    'thin': '比较级 thinner；最高级 thinnest',
    'travel': '第三人称单数 travels；过去式 traveled/travelled',
    'break': '第三人称单数 breaks；过去式 broke；过去分词 broken',
    'carry': '第三人称单数 carries；过去式 carried',
    'feel': '第三人称单数 feels；过去式 felt',
    'hear': '第三人称单数 hears；过去式 heard',
    'heavy': '比较级 heavier；最高级 heaviest',
    'hope': '第三人称单数 hopes；过去式 hoped',
    'light': '比较级 lighter；最高级 lightest（作「轻的」讲）',
    'cross': '第三人称单数 crosses；过去式 crossed',
    'grow': '第三人称单数 grows；过去式 grew',
    'ill': '比较级 worse（与 well 相对）；ill 也可作副词',
    'open': '第三人称单数 opens；过去式 opened',
    'wrong': '比较级 more wrong；最高级 most wrong',
    'kind': '复数 kinds',
    'kiss': '第三人称单数 kisses；过去式 kissed',
    'love': '第三人称单数 loves；过去式 loved',
    'surprise': '第三人称单数 surprises；过去式 surprised',
    'cook': '第三人称单数 cooks；过去式 cooked',
    'learn': '第三人称单数 learns；过去式 learned/learnt',
    'true': '比较级 truer；最高级 truest',
    'study': '第三人称单数 studies；过去式 studied',
    'gave': 'give 的过去式',
    'leave': '第三人称单数 leaves；过去式 left',
    'miss': '第三人称单数 misses；过去式 missed',
}

DEFINITION_OVERRIDES: dict[str, str] = {
    'along': '沿着',
    'anywhere': '任何地方',
    'famous': '著名的',
    'fat': '胖的',
    'go back': '回到',
    'ice and snow festival': '冰雪节',
    'made': '制作（过去式）',
    'show': '给……看',
    'the yangtze river': '长江',
    'thin': '瘦的',
    'travel': '旅行',
    'break': '摔断（过去式 broke）',
    'carry': '携带；搬运',
    'feel': '感觉到',
    'hear': '听见',
    'heavy': '重的',
    'hope': '希望',
    'lesson': '功课；课文',
    'light': '轻的',
    'soon': '不久',
    'a lot of': '大量的',
    'cross': '横穿',
    'doctor': '医生',
    'fever': '发烧',
    'have a cold': '感冒',
    'headache': '头疼',
    'ill': '不适；生病的',
    'medicine': '药',
    'must': '必须',
    "mustn't = must not": '不允许',
    'open': '张开；打开',
    'street': '街；街道',
    'toothache': '牙疼',
    'wrong': '不正常',
    'dining room': '餐厅',
    'kind': '种；类',
    'kiss': '亲吻',
    'love': '爱',
    'restaurant': '餐馆',
    'surprise': '惊讶',
    'cook': '厨师',
    'dancer': '舞蹈演员',
    'farmer': '农民',
    'grow': '种植',
    'job': '工作',
    'nurse': '护士',
    'police officer': '警察',
    'singer': '歌唱演员',
    'worker': '工人',
    'driver': '司机',
    'learn': '学习',
    'scientist': '科学家',
    'true': '确实的',
    'bottle': '瓶子',
    'chemistry': '化学',
    'edison': '爱迪生',
    'geography': '地理',
    'history': '历史',
    'inventor': '发明家',
    'lab': '实验室',
    'middle school': '中学',
    'physics': '物理',
    'study': '学习',
    'subject': '科目',
    "teachers' office": '教师办公室',
    'address': '地址',
    'gave': '给（过去式）',
    'information': '信息',
    'leave': '离开',
    'miss': '想念',
    'year book': '毕业留念册',
}

POS_OVERRIDES: dict[str, str] = {
    'along': 'prep./adv.',
    'anywhere': 'adv.',
    'famous': 'adj.',
    'fat': 'adj.',
    'go back': 'v. phr.',
    'ice and snow festival': 'n.',
    'made': 'v.',
    'show': 'v.',
    'the yangtze river': 'n.',
    'thin': 'adj.',
    'travel': 'v./n.',
    'break': 'v.',
    'carry': 'v.',
    'feel': 'v.',
    'hear': 'v.',
    'heavy': 'adj.',
    'hope': 'v./n.',
    'lesson': 'n.',
    'light': 'adj.',
    'soon': 'adv.',
    'a lot of': 'det.',
    'cross': 'v.',
    'doctor': 'n.',
    'fever': 'n.',
    'have a cold': 'v. phr.',
    'headache': 'n.',
    'ill': 'adj.',
    'medicine': 'n.',
    'must': 'modal v.',
    "mustn't = must not": 'modal v. phr.',
    'open': 'v./adj.',
    'street': 'n.',
    'toothache': 'n.',
    'wrong': 'adj.',
    'dining room': 'n.',
    'kind': 'n.',
    'kiss': 'v./n.',
    'love': 'v./n.',
    'restaurant': 'n.',
    'surprise': 'n./v.',
    'cook': 'n./v.',
    'dancer': 'n.',
    'farmer': 'n.',
    'grow': 'v.',
    'job': 'n.',
    'nurse': 'n.',
    'police officer': 'n.',
    'singer': 'n.',
    'worker': 'n.',
    'driver': 'n.',
    'learn': 'v.',
    'scientist': 'n.',
    'true': 'adj.',
    'bottle': 'n.',
    'chemistry': 'n.',
    'edison': 'n.',
    'geography': 'n.',
    'history': 'n.',
    'inventor': 'n.',
    'lab': 'n.',
    'middle school': 'n.',
    'physics': 'n.',
    'study': 'v./n.',
    'subject': 'n.',
    "teachers' office": 'n.',
    'address': 'n./v.',
    'gave': 'v.',
    'information': 'n.',
    'leave': 'v.',
    'miss': 'v.',
    'year book': 'n.',
}

IPA_OVERRIDES: dict[str, str] = {
    'along': '/əˈlɒŋ/',
    'anywhere': '/ˈeniweə(r)/',
    'famous': '/ˈfeɪməs/',
    'fat': '/fæt/',
    'go back': '/ɡəʊ bæk/',
    'ice and snow festival': '/aɪs ənd snəʊ ˈfestɪvl/',
    'made': '/meɪd/',
    'show': '/ʃəʊ/',
    'the yangtze river': '/ðə ˈjæŋtsi ˈrɪvə(r)/',
    'thin': '/θɪn/',
    'travel': '/ˈtrævl/',
    'break': '/breɪk/',
    'carry': '/ˈkæri/',
    'feel': '/fiːl/',
    'hear': '/hɪə(r)/',
    'heavy': '/ˈhevi/',
    'hope': '/həʊp/',
    'lesson': '/ˈlesn/',
    'light': '/laɪt/',
    'soon': '/suːn/',
    'a lot of': '/ə lɒt əv/',
    'cross': '/krɒs/',
    'doctor': '/ˈdɒktə(r)/',
    'fever': '/ˈfiːvə(r)/',
    'have a cold': '/hæv ə kəʊld/',
    'headache': '/ˈhedeɪk/',
    'ill': '/ɪl/',
    'medicine': '/ˈmedsn, ˈmedsɪn/',
    'must': '/mʌst, məst/',
    "mustn't = must not": '/ˈmʌsnt/',
    'open': '/ˈəʊpən/',
    'street': '/striːt/',
    'toothache': '/ˈtuːθeɪk/',
    'wrong': '/rɒŋ/',
    'dining room': '/ˈdaɪnɪŋ ruːm/',
    'kind': '/kaɪnd/',
    'kiss': '/kɪs/',
    'love': '/lʌv/',
    'restaurant': '/ˈrestrɒnt, ˈrestrɒ̃/',
    'surprise': '/səˈpraɪz/',
    'cook': '/kʊk/',
    'dancer': '/ˈdɑːnsə(r)/',
    'farmer': '/ˈfɑːmə(r)/',
    'grow': '/ɡrəʊ/',
    'job': '/dʒɒb/',
    'nurse': '/nɜːs/',
    'police officer': '/pəˈliːs ˈɒfɪsə(r)/',
    'singer': '/ˈsɪŋə(r)/',
    'worker': '/ˈwɜːkə(r)/',
    'driver': '/ˈdraɪvə(r)/',
    'learn': '/lɜːn/',
    'scientist': '/ˈsaɪəntɪst/',
    'true': '/truː/',
    'bottle': '/ˈbɒtl/',
    'chemistry': '/ˈkemɪstri/',
    'edison': '/ˈedɪsn/',
    'geography': '/dʒiˈɒɡrəfi/',
    'history': '/ˈhɪstri/',
    'inventor': '/ɪnˈventə(r)/',
    'lab': '/læb/',
    'middle school': '/ˈmɪdl skuːl/',
    'physics': '/ˈfɪzɪks/',
    'study': '/ˈstʌdi/',
    'subject': '/ˈsʌbdʒɪkt, ˈsʌbdʒekt/',
    "teachers' office": '/ˈtiːtʃəz ˈɒfɪs/',
    'address': '/əˈdres/',
    'gave': '/ɡeɪv/',
    'information': '/ˌɪnfəˈmeɪʃn/',
    'leave': '/liːv/',
    'miss': '/mɪs/',
    'year book': '/jɪə bʊk/',
}


def _secondary_mnemonic(key: str, headword: str, definition_zh: str, *, kind: str) -> str | None:
    if key in ROOT_MNEMONICS:
        return f'拆词联想：{ROOT_MNEMONICS[key]}'
    if key in IMAGE_MNEMONICS:
        return f'形象联想：{IMAGE_MNEMONICS[key]}'
    if key in SEMANTIC_MNEMONICS:
        return f'语义联想：{SEMANTIC_MNEMONICS[key]}'

    short = definition_zh.split('；')[0].split('，')[0].strip()
    if kind == 'phrase':
        return f'语义联想：把「{short}」和短语 {headword} 配对记忆。'

    adjectives = {
        'famous', 'fat', 'thin', 'heavy', 'light', 'ill', 'wrong', 'true',
    }
    if key in adjectives:
        return f'语义联想：看到「{short}」的事物时，就想到 {headword}。'
    return f'语义联想：把「{short}」和英文 {headword} 配对记忆。'


def mnemonic_for(headword: str, definition_zh: str, *, kind: str) -> str:
    key = headword.lower()
    parts: list[str] = []

    if key in SOUND_MNEMONICS:
        parts.append(f'谐音联想：{SOUND_MNEMONICS[key]}')

    secondary = _secondary_mnemonic(key, headword, definition_zh, kind=kind)
    if secondary:
        if parts:
            if secondary not in parts[0]:
                parts.append(secondary)
        else:
            parts.append(secondary)

    return parts[0] if len(parts) == 1 else '\n'.join(parts)
