"""Mnemonics and inflection notes for 闽教版 Grade 3 English, Volume 1 (上册).

谐音规则：仅真实谐音，不硬凑；优先语义/形象/拆词联想。
"""

from __future__ import annotations

SOUND_MNEMONICS: dict[str, str] = {
    'book': 'book 音近「布克」，book 就是书。',
    'bye': 'bye 音近「拜」，挥手说 bye 再见。',
    'cook': 'cook 音近「库克」，cook 是厨师也会煮。',
    'game': 'game 音近「盖姆」，盖姆就是游戏 game。',
    'hen': 'hen 音近「哼」，母鸡 hen 咯咯叫。',
    'hi': 'hi 就像中文打招呼的「嗨」。',
    'look': 'look 音近「路克」，look 就是看一看。',
    'nice': 'nice 读起来像「奈斯」，夸别人真 nice 友好。',
    'pen': 'pen 音近「喷」，钢笔 pen 用来写字。',
    'ten': 'ten 音近「疼」的轻读，数到 ten 十。',
    'woof': 'woof 音近「呜夫」，像狗汪汪叫。',
    'wow': 'wow 音近「哇」，看到惊喜时说 wow。',
    'yeah': 'yeah 音近「耶」，开心同意时说 yeah。',
}

ROOT_MNEMONICS: dict[str, str] = {
    'afternoon': 'after 在……之后 + noon 中午，afternoon 是下午。',
    'birthday': 'birth 出生 + day 日，birthday 是生日。',
    'blow out': 'blow 吹 + out 出去，blow out 是把蜡烛吹灭。',
    'classroom': 'class 课 + room 房间，classroom 是上课的教室。',
    'colorful': 'color 颜色 + ful 充满，colorful 是多彩的。',
    'goodbye': 'good 好 + bye 再见，goodbye 是正式说再见。',
    'grandma': 'grand 祖辈 + ma 妈，grandma 是奶奶、外婆。',
    'grandpa': 'grand 祖辈 + pa 爸，grandpa 是爷爷、外公。',
    'how about': 'how 怎样 + about 关于，how about 问「……怎么样」。',
    'how many': 'how 多少 + many 许多，how many 问「有多少」。',
    'how old': 'how 怎样 + old 岁/老，how old 问「多大」。',
    "i'm=i am": "I 我 + am 是，I'm 就是「我是」。",
    'ice cream': 'ice 冰 + cream 奶油，ice cream 是冰激凌。',
    "it's=it is": "it 它 + is 是，it's 就是「它是」。",
    "let's=let us": "let 让 + us 我们，let's 就是「让我们」。",
    'morning': 'morn 早晨 + ing，morning 是早晨、上午。',
    'number': 'num 数 + ber，number 是数字、号码。',
    'pencil box': 'pencil 铅笔 + box 盒，pencil box 是装铅笔的笔盒。',
    'school': 'school 学校，去 school 就是去上学。',
    'schoolbag': 'school 学校 + bag 包，schoolbag 是书包。',
    'teacher': 'teach 教 + er 的人，teacher 是老师。',
    "that's=that is": "that 那 + is 是，that's 就是「那是」。",
    "what's=what is": "what 什么 + is 是，what's 就是「是什么」。",
    'worker': 'work 工作 + er 的人，worker 是工人。',
}

IMAGE_MNEMONICS: dict[str, str] = {
    'apple': '想象一颗红 apple 苹果。',
    'banana': '想象一根弯弯的 yellow banana 香蕉。',
    'cake': '想象生日会上插着 candle 的 cake 蛋糕。',
    'candle': '想象生日蛋糕上五根 candle 蜡烛。',
    'cat': '想象小猫喵喵叫，cat 就是猫。',
    'dog': '想象小狗摇尾巴并发出 woof 的声音。',
    'duck': '想象鸭子在公园水里游泳。',
    'eraser': '想象用 white eraser 橡皮擦掉错字。',
    'flower': '想象一朵 pink flower 花。',
    'gate': '想象站在 school gate 校门口等朋友。',
    'hen': '想象母鸡 hen 旁边有一个 egg 蛋。',
    'kite': '想象风筝在天上飞，kite 就是风筝。',
    'light': '想象 red light 红灯停、green light 绿灯行。',
    'lion': '想象狮子在动物园里大声吼叫。',
    'monkey': '想象猴子在树上跳来跳去。',
    'pen': '想象从 pencil box 里拿出一支 pen 钢笔。',
    'pencil': '想象用 pencil 铅笔画一颗 star。',
    'photo': '想象一张 family photo 全家福。',
    'pig': '想象粉红色的 pig 猪在农场里。',
    'rabbit': '想象兔子竖着长耳朵跳来跳去。',
    'ruler': '想象用 ruler 尺子画直线。',
    'schoolbag': '想象背着 schoolbag 书包去上学。',
    'star': '想象夜空里闪亮的 star 星星。',
    'umbrella': '想象下雨天打着 colorful umbrella 雨伞。',
    'violin': '想象在 art 课上拉 violin 小提琴。',
    'x-ray': '想象 doctor 用 X-ray 看骨头。',
    'zoo': '想象去 zoo 动物园看 lion 和 monkey。',
}

SEMANTIC_MNEMONICS: dict[str, str] = {
    'a/an': 'An apple. a/an 表示「一个」。',
    'after': 'After class. after 是……之后。',
    'am': 'I am fine. am 和 I 连用表示「是」。',
    'and': 'A boy and a girl. and 是「和」。',
    'are': 'How are you? are 和 you/we/they 连用。',
    'around': 'Look around. around 是周围。',
    'art': 'We have art class. art 是美术。',
    'at': 'I am at school. at 是在某处。',
    'aunt': 'My aunt is a nurse. aunt 是阿姨等。',
    'big': 'My family is big. big 是大的。',
    'black': 'The cat is black. black 是黑色。',
    'blue': 'The sky is blue. blue 是蓝色。',
    'book': 'Open your book. book 是书。',
    'boy': 'The boy is my friend. boy 是男孩。',
    'brother': 'This is my brother. brother 是哥哥或弟弟。',
    'class': 'Good morning, class! class 是班级、课。',
    'color': 'What color is it? color 是颜色。',
    'cut': 'Cut the paper. cut 是剪。',
    'cute': 'You are so cute. cute 是可爱的。',
    'day': 'Have a nice day! day 是一天。',
    'doctor': 'My uncle is a doctor. doctor 是医生。',
    'draw': 'Draw a star. draw 是画画。',
    'egg': 'An egg from the hen. egg 是蛋。',
    'eight': 'Eight ducks. eight 是八。',
    'english': 'English book 英语书，English 是英语。',
    'family': 'I love my family. 爸爸妈妈兄弟姐妹组成 family 家庭。',
    'farmer': 'My grandpa is a farmer. farmer 是农民。',
    'father': 'This is my father. father 是爸爸。',
    'fine': 'I am fine. 回答 How are you? 用 fine 很好。',
    'fish': 'I see a fish. fish 是鱼。',
    'five': 'I am five years old. five 是五。',
    'for': 'A present for you. for 表示「给」。',
    'four': 'Four ducks. four 是四。',
    'friend': 'She is my friend. 一起玩的人就是 friend 朋友。',
    'fun': 'It is fun! fun 是有趣的。',
    'game': 'Play a game. game 是游戏。',
    'girl': 'The girl is nice. girl 是女孩。',
    'go': "Let's go! go 是走、去。",
    'good': 'Good morning! good 是好的。',
    'great': 'Great! great 是太好了。',
    'green': 'The light is green. Go! green 是绿色，绿灯行。',
    'happy': 'Happy birthday! happy 是开心的。',
    'have': 'I have a cat. have 表示「有」。',
    'he': 'He is my father. he 是他。',
    'hello': 'Hello! 见面打招呼就说 hello。',
    'here': 'Come here. here 是这里。',
    'home': 'I am at home. home 是家。',
    'how': 'How are you? / How many? / How old? how 问方式或数量。',
    'i': 'I am Lily. I 是「我」。',
    'in': 'We are in the classroom. in 是在……里。',
    'is': 'My name is Lily. is 是「是」。',
    'it': 'It is red. it 是「它」。',
    'jacket': 'Put on your jacket. jacket 是夹克。',
    'let': 'Let us play. let 是「让」。',
    'love': 'I love my family. love 是爱。',
    'make': 'Make a star. make 是制作。',
    'many': 'How many ducks? many 表示许多。',
    'me': 'Show me your pen. me 是「我（宾格）」。',
    'meet': 'Nice to meet you! 第一次见面说 meet 遇见。',
    'miss': 'Good morning, Miss! Miss 是对女老师的称呼。',
    'mom': 'This is my mom. mom 是妈妈。',
    'mother': 'This is my mother. mother 是妈妈。',
    'my': 'My name is Lily. my 是「我的」。',
    'name': "What's your name? 问名字用 name。",
    'nine': 'Nine ducks. nine 是九。',
    'noodle': 'I like noodles. noodle 是面条。',
    'now': 'Stop now. now 是现在。',
    'nurse': 'My mother is a nurse. nurse 是护士。',
    'oh': 'Oh, sorry! oh 表示惊讶或恍然大悟。',
    'ok': "OK! Let's go. OK 表示好的、行。",
    'old': 'How old are you? old 问年龄。',
    'on': 'The book is on the desk. on 是在……上。',
    'one': 'One, two, three! one 是一。',
    'orange': 'An orange fruit. orange 是橙子，也可指橙色。',
    'park': "Let's play in the park. park 是公园。",
    'pet': 'It is my pet. pet 是宠物。',
    'phone': 'Call me on the phone. phone 是电话。',
    'photo': 'A family photo. photo 是照片。',
    'pink': 'The pig is pink. pink 是粉色。',
    'play': "Let's play! play 是玩耍。",
    'please': 'Sit down, please. 礼貌请求加 please 请。',
    'present': 'A birthday present. present 是礼物。',
    'question': 'I have a question. question 是问题。',
    'really': 'Really? really 表示真的吗。',
    'red': 'Stop at the red light. red 是红色，红灯停。',
    'right': 'That is right. right 是正确、对的。',
    'school': 'Welcome to our school. school 是学校。',
    'seven': 'Seven ducks. seven 是七。',
    'she': 'She is my mother. she 是她。',
    'show': 'Show me your pen. show 是展示、给……看。',
    'sister': 'This is my sister. sister 是姐姐或妹妹。',
    'six': 'Six ducks. six 是六。',
    'so': 'You are so cute. so 表示「如此、这么」。',
    'sorry': 'Oh, sorry! sorry 是对不起。',
    'step': 'Step one. step 是步骤。',
    'stop': 'Stop at the red light. stop 是停下。',
    'street': 'Stop on the street. street 是街道。',
    'ten': 'Count to ten. ten 是十。',
    'thank': 'Thank you. 别人帮忙后说 thank 谢谢。',
    'that': 'That is right. that 是「那、那个」。',
    'the': 'Open the door. the 是指那个、这个。',
    'they': 'They are my friends. they 是他们。',
    'this': 'This is my cat. this 是「这、这个」。',
    'three': 'One, two, three! three 是三。',
    'to': 'Nice to meet you. to 表示方向「向、到」。',
    'too': 'Nice to meet you, too. too 是「也」。',
    'two': 'One, two, three! two 是二。',
    'uncle': 'My uncle is a doctor. uncle 是叔叔等。',
    'us': 'Let us play. us 是「我们（宾格）」。',
    'way': 'On my way to school. way 是路、方式。',
    'we': 'We are a family. we 是我们。',
    'welcome': 'Welcome to my home. welcome 是欢迎。',
    'what': "What's this? what 问「什么」。",
    'white': 'The rabbit is white. white 是白色。',
    'who': 'Who is he? who 问「谁」。',
    'window': 'Open the window. window 是窗户。',
    'wish': 'Make a wish! wish 是许愿。',
    'worker': 'My father is a worker. worker 是工人。',
    'x-ray': 'The doctor takes an X-ray. X-ray 是 X 光。',
    'year': 'I am eight years old. year 是年、岁。',
    'yellow': 'The star is yellow. yellow 是黄色。',
    'yes': 'Yes, I am fine. yes 表示同意、是。',
    'you': 'How are you? you 是「你」。',
    'your': "What's your name? your 是「你的」。",
}

INFLECTION_NOTES: dict[str, str] = {
    'am': '复数 are',
    'apple': '复数 apples',
    'are': '单数 is / am',
    'art': '不可数（泛指美术）',
    'aunt': '复数 aunts',
    'bag': '复数 bags',
    'ball': '复数 balls',
    'banana': '复数 bananas',
    'basket': '复数 baskets',
    'blow out': '第三人称单数 blows out',
    'book': '复数 books',
    'box': '复数 boxes',
    'boy': '复数 boys',
    'brother': '复数 brothers',
    'cake': '复数 cakes',
    'candle': '复数 candles',
    'car': '复数 cars',
    'cat': '复数 cats',
    'class': '复数 classes',
    'classroom': '复数 classrooms',
    'close': '第三人称单数 closes',
    'color': '第三人称单数 colors',
    'come': '第三人称单数 comes',
    'cook': '第三人称单数 cooks',
    'cut': '第三人称单数 cuts',
    'day': '复数 days',
    'do': '第三人称单数 does',
    'doctor': '复数 doctors',
    'dog': '复数 dogs',
    'draw': '第三人称单数 draws',
    'duck': '复数 ducks',
    'egg': '复数 eggs',
    'eraser': '复数 erasers',
    'family': '复数 families',
    'farmer': '复数 farmers',
    'father': '复数 fathers',
    'fish': '复数 fish（形式不变）',
    'flower': '复数 flowers',
    'friend': '复数 friends',
    'gate': '复数 gates',
    'girl': '复数 girls',
    'go': '第三人称单数 goes',
    'grandma': '复数 grandmas',
    'grandpa': '复数 grandpas',
    'have': '第三人称单数 has',
    'he': '复数 they',
    'hen': '复数 hens',
    'ice cream': '不可数/可数均可',
    'is': '复数 are',
    'it': '复数 they',
    'jacket': '复数 jackets',
    'kite': '复数 kites',
    'lion': '复数 lions',
    'look': '第三人称单数 looks',
    'love': '第三人称单数 loves',
    'make': '第三人称单数 makes',
    'meet': '第三人称单数 meets',
    'mom': '复数 moms',
    'monkey': '复数 monkeys',
    'mother': '复数 mothers',
    'name': '复数 names',
    'noodle': '复数 noodles',
    'number': '复数 numbers',
    'nurse': '复数 nurses',
    'open': '第三人称单数 opens',
    'orange': '复数 oranges',
    'pen': '复数 pens',
    'pencil': '复数 pencils',
    'pencil box': '复数 pencil boxes',
    'pet': '复数 pets',
    'phone': '复数 phones',
    'photo': '复数 photos',
    'pig': '复数 pigs',
    'play': '第三人称单数 plays',
    'present': '复数 presents',
    'question': '复数 questions',
    'rabbit': '复数 rabbits',
    'ruler': '复数 rulers',
    'run': '第三人称单数 runs',
    'say': '第三人称单数 says',
    'school': '复数 schools',
    'schoolbag': '复数 schoolbags',
    'she': '复数 they',
    'show': '第三人称单数 shows',
    'sister': '复数 sisters',
    'sit': '第三人称单数 sits',
    'star': '复数 stars',
    'step': '复数 steps',
    'stop': '第三人称单数 stops',
    'street': '复数 streets',
    'teacher': '复数 teachers',
    'thank': '第三人称单数 thanks',
    'that': '复数 those',
    'this': '复数 these',
    'umbrella': '复数 umbrellas',
    'uncle': '复数 uncles',
    'violin': '复数 violins',
    'welcome': '第三人称单数 welcomes',
    'window': '复数 windows',
    'wish': '第三人称单数 wishes',
    'worker': '复数 workers',
    'year': '复数 years',
    'zoo': '复数 zoos',
}

DEFINITION_OVERRIDES: dict[str, str] = {
    'meet': '遇见',
    'friend': '朋友',
    'nice': '令人愉快的；友好的',
    'to': '对；向；到',
    'you': '你；您；你们',
    'in': '在……内；在……状态中',
    'the': '这（那）个；这（那）些',
    'classroom': '教室',
    'hello': '你好',
    'boy': '男孩',
    'and': '和',
    'girl': '女孩',
    'I': '我',
    'am': '是',
    "I'm=I am": '我是',
    'Miss': '（学生对女教师的称呼）女士；小姐',
    'too': '也；太',
    'a/an': '一个',
    'apple': '苹果',
    'banana': '香蕉',
    'what': '什么',
    'is': '是',
    "what's=what is": '是什么',
    'your': '你的；你们的',
    'name': '名字',
    'please': '请',
    'at': '在（某处）；在（几点钟）',
    'school': '学校',
    'gate': '大门',
    'hi': '你好',
    'my': '我的',
    'cat': '猫',
    'dog': '狗',
    'how': '怎样；多少',
    'are': '是',
    'home': '家',
    'good': '好的',
    'morning': '早晨；上午',
    'mom': '妈妈',
    'woof': '（狗叫声）汪',
    'fine': '健康的；好的',
    'thank': '谢谢',
    'afternoon': '下午',
    'egg': '蛋',
    'fish': '鱼；鱼肉',
    'have': '有；吃；喝',
    'day': '（一）天；（一）日',
    'street': '大街；街道',
    'this': '这个',
    'goodbye': '再见',
    'bye': '再见',
    'hen': '母鸡',
    'fun': '有趣的；乐趣',
    'number': '号码；数字',
    'let': '让',
    'us': '我们（宾格）',
    "let's=let us": '让我们',
    'play': '玩耍；玩',
    'park': '公园',
    'OK': '好的；行',
    'one': '一',
    'two': '二',
    'three': '三',
    'four': '四',
    'five': '五',
    'six': '六',
    'seven': '七',
    'eight': '八',
    'nine': '九',
    'ten': '十',
    'great': '极好的；杰出的',
    'ice cream': '冰激凌',
    'jacket': '夹克',
    'how many': '多少',
    'duck': '鸭子',
    'look': '看',
    'many': '许多的',
    'really': '（表示惊奇、兴趣、怀疑等）当真；真正地',
    'yes': '是，是的；同意',
    'that': '那；那个',
    "that's=that is": '那是',
    'right': '正确的；对的',
    'kite': '风筝',
    'lion': '狮子',
    'how old': '多大（年龄）',
    'go': '去；走',
    'old': '……岁；年老的',
    'year': '年',
    'oh': '啊；呀',
    'sorry': '对不起，抱歉',
    'how about': '……怎么样',
    'yeah': '是的',
    'monkey': '猴子',
    'noodle': '面条',
    'phone': '电话',
    'it': '它',
    "it's=it is": '它是',
    'pet': '宠物',
    'orange': '橙子；橙色的',
    'pig': '猪',
    'color': '颜色；给……着色',
    'around': '围绕',
    'green': '绿色；绿色的',
    'on': '在……之上；在……时候',
    'way': '路，道路；方式',
    'stop': '停止；停下',
    'light': '灯；光线',
    'red': '红色；红色的',
    'now': '现在',
    'question': '问题',
    'rabbit': '兔子',
    'art': '美术；艺术',
    'class': '课；班级',
    'game': '游戏；比赛',
    'blue': '蓝色；蓝色的',
    'yellow': '黄色；黄色的',
    'wow': '呀；哇',
    'white': '白色；白色的',
    'pink': '粉红色；粉红色的',
    'star': '星星',
    'teacher': '老师',
    'show': '给……看；展示',
    'me': '我（宾格）',
    'schoolbag': '书包',
    'pencil box': '笔盒',
    'black': '黑色；黑色的',
    'pen': '钢笔',
    'pencil': '铅笔',
    'ruler': '尺子',
    'book': '书',
    'eraser': '橡皮擦',
    'umbrella': '雨伞',
    'violin': '小提琴',
    'they': '他们；她们；它们',
    'colorful': '多彩的',
    'flower': '花',
    'after': '在……之后',
    'step': '步骤；脚步',
    'draw': '画画',
    'cut': '剪；切',
    'make': '制作；使变得',
    'window': '窗户',
    'X-ray': 'X光',
    'love': '爱；喜爱',
    'family': '家庭；家人',
    'father': '父亲；爸爸',
    'brother': '哥哥；弟弟',
    'sister': '姐姐；妹妹',
    'welcome': '欢迎',
    'mother': '母亲；妈妈',
    'here': '这里',
    'cake': '蛋糕',
    'zoo': '动物园',
    'who': '谁',
    'he': '他',
    'happy': '开心的',
    'birthday': '生日',
    'we': '我们',
    'present': '礼物',
    'for': '给；为了',
    'grandpa': '爷爷；外公',
    'she': '她',
    'grandma': '奶奶；外婆',
    'wish': '愿望；希望',
    'blow out': '吹灭',
    'candle': '蜡烛',
    'photo': '照片',
    'so': '如此；这么；所以',
    'cute': '可爱的',
    'doctor': '医生',
    'English': '英语；英国的',
    'farmer': '农民',
    'cook': '厨师；煮',
    'uncle': '叔叔；舅舅等',
    'worker': '工人',
    'aunt': '阿姨；姑姑等',
    'nurse': '护士',
    'big': '大的',
}

POS_OVERRIDES: dict[str, str] = {
    # PDF 词表与通用 pos 推断冲突时的修正
    'I': 'pron.',
    'you': 'pron.',
    'he': 'pron.',
    'she': 'pron.',
    'we': 'pron.',
    'it': 'pron.',
    'me': 'pron.',
    'us': 'pron.',
    'they': 'pron.',
    'my': 'det.',
    'your': 'det.',
    'the': 'det.',
    'a/an': 'det.',
    'this': 'pron./det.',
    'that': 'pron./det.',
    'who': 'pron.',
    'what': 'pron.',
    'Miss': 'n.',
    'am': 'v.',
    'is': 'v.',
    'are': 'v.',
    'have': 'v.',
    'let': 'v.',
    'play': 'v.',
    'go': 'v.',
    'look': 'v.',
    'stop': 'v.',
    'show': 'v.',
    'draw': 'v.',
    'cut': 'v.',
    'make': 'v.',
    'love': 'v.',
    'welcome': 'v./interj.',
    'wish': 'v./n.',
    'cook': 'v./n.',
    'color': 'v./n.',
    'fine': 'adj.',
    'good': 'adj.',
    'nice': 'adj.',
    'old': 'adj.',
    'big': 'adj.',
    'happy': 'adj.',
    'cute': 'adj.',
    'colorful': 'adj.',
    'green': 'adj./n.',
    'red': 'adj./n.',
    'blue': 'adj./n.',
    'yellow': 'adj./n.',
    'white': 'adj./n.',
    'pink': 'adj./n.',
    'black': 'adj./n.',
    'orange': 'adj./n.',
    'to': 'prep.',
    'in': 'prep.',
    'at': 'prep.',
    'on': 'prep.',
    'for': 'prep.',
    'around': 'prep./adv.',
    'after': 'prep./adv.',
    'please': 'adv.',
    'too': 'adv.',
    'now': 'adv.',
    'so': 'adv.',
    'here': 'adv.',
    'really': 'adv.',
    'yes': 'adv./interj.',
    'yeah': 'adv./interj.',
    'oh': 'interj.',
    'wow': 'interj.',
    'woof': 'interj.',
    'sorry': 'adj./interj.',
    'OK': 'adj./adv./interj.',
    'thank': 'v.',
    'English': 'n./adj.',
    'X-ray': 'n.',
    'bye': 'interj.',
    'gate': 'n.',
    'goodbye': 'interj./n.',
    'hello': 'interj./n.',
    'hen': 'n.',
    'hi': 'interj.',
    "I'm=I am": 'phrase',
    "what's=what is": 'phrase',
    'how about': 'phrase',
    'how many': 'phrase',
    'how old': 'phrase',
    'ice cream': 'n.',
    "it's=it is": 'phrase',
    'jacket': 'n.',
    "let's=let us": 'phrase',
    "that's=that is": 'phrase',
    'pencil box': 'n.',
    'step': 'n./v.',
    'umbrella': 'n.',
    'violin': 'n.',
    'blow out': 'v.',
    'candle': 'n.',
    'doctor': 'n.',
    'nurse': 'n.',
    'present': 'n.',
    'worker': 'n.',
    'meet': 'v.',
    'friend': 'n.',
    'boy': 'n.',
    'girl': 'n.',
    'mom': 'n.',
    'street': 'n.',
    'phone': 'n.',
    'question': 'n.',
    'art': 'n.',
    'class': 'n.',
    'game': 'n.',
    'cake': 'n.',
    'zoo': 'n.',
    'window': 'n.',
    'number': 'n.',
}

IPA_OVERRIDES: dict[str, str] = {
    'meet': '/miːt/',
    'friend': '/frend/',
    'nice': '/naɪs/',
    'to': '/tuː, tə/',
    'you': '/juː, jʊ/',
    'in': '/ɪn/',
    'the': '/ðə, ðiː/',
    'classroom': '/ˈklɑːsruːm, ˈklɑːsrʊm/',
    'hello': '/həˈləʊ/',
    'boy': '/bɔɪ/',
    'and': '/ænd, ənd/',
    'girl': '/ɡɜːl/',
    'I': '/aɪ/',
    'am': '/æm, əm/',
    "I'm=I am": '/aɪm/',
    'Miss': '/mɪs/',
    'too': '/tuː/',
    'a/an': '/ə, æn/',
    'apple': '/ˈæpl/',
    'banana': '/bəˈnɑːnə/',
    'what': '/wɒt/',
    'is': '/ɪz, əz/',
    "what's=what is": '/wɒts/',
    'your': '/jɔː(r), jʊə(r)/',
    'name': '/neɪm/',
    'please': '/pliːz/',
    'at': '/æt, ət/',
    'school': '/skuːl/',
    'gate': '/ɡeɪt/',
    'hi': '/haɪ/',
    'my': '/maɪ/',
    'cat': '/kæt/',
    'dog': '/dɒɡ/',
    'how': '/haʊ/',
    'are': '/ɑː(r)/',
    'home': '/həʊm/',
    'good': '/ɡʊd/',
    'morning': '/ˈmɔːnɪŋ/',
    'mom': '/mɒm/',
    'woof': '/wʊf/',
    'fine': '/faɪn/',
    'thank': '/θæŋk/',
    'afternoon': '/ˌɑːftəˈnuːn/',
    'egg': '/eɡ/',
    'fish': '/fɪʃ/',
    'have': '/hæv/',
    'day': '/deɪ/',
    'street': '/striːt/',
    'this': '/ðɪs/',
    'goodbye': '/ˌɡʊdˈbaɪ/',
    'bye': '/baɪ/',
    'hen': '/hen/',
    'fun': '/fʌn/',
    'number': '/ˈnʌmbə(r)/',
    'let': '/let/',
    'us': '/əs, ʌs/',
    "let's=let us": '/lets/',
    'play': '/pleɪ/',
    'park': '/pɑːk/',
    'OK': '/ˌəʊˈkeɪ/',
    'one': '/wʌn/',
    'two': '/tuː/',
    'three': '/θriː/',
    'four': '/fɔː(r)/',
    'five': '/faɪv/',
    'six': '/sɪks/',
    'seven': '/ˈsevn/',
    'eight': '/eɪt/',
    'nine': '/naɪn/',
    'ten': '/ten/',
    'great': '/ɡreɪt/',
    'ice cream': '/ˌaɪs ˈkriːm/',
    'jacket': '/ˈdʒækɪt/',
    'how many': '/haʊ ˈmeni/',
    'duck': '/dʌk/',
    'look': '/lʊk/',
    'many': '/ˈmeni/',
    'really': '/ˈrɪəli/',
    'yes': '/jes/',
    'that': '/ðæt, ðət/',
    "that's=that is": '/ðæts/',
    'right': '/raɪt/',
    'kite': '/kaɪt/',
    'lion': '/ˈlaɪən/',
    'how old': '/haʊ əʊld/',
    'go': '/ɡəʊ/',
    'old': '/əʊld/',
    'year': '/jɪə(r)/',
    'oh': '/əʊ/',
    'sorry': '/ˈsɒri/',
    'how about': '/haʊ əˈbaʊt/',
    'yeah': '/jeə/',
    'monkey': '/ˈmʌŋki/',
    'noodle': '/ˈnuːdl/',
    'phone': '/fəʊn/',
    'it': '/ɪt/',
    "it's=it is": '/ɪts/',
    'pet': '/pet/',
    'orange': '/ˈɒrɪndʒ/',
    'pig': '/pɪɡ/',
    'color': '/ˈkʌlə(r)/',
    'around': '/əˈraʊnd/',
    'green': '/ɡriːn/',
    'on': '/ɒn/',
    'way': '/weɪ/',
    'stop': '/stɒp/',
    'light': '/laɪt/',
    'red': '/red/',
    'now': '/naʊ/',
    'question': '/ˈkwestʃən/',
    'rabbit': '/ˈræbɪt/',
    'art': '/ɑːt/',
    'class': '/klɑːs/',
    'game': '/ɡeɪm/',
    'blue': '/bluː/',
    'yellow': '/ˈjeləʊ/',
    'wow': '/waʊ/',
    'white': '/waɪt/',
    'pink': '/pɪŋk/',
    'star': '/stɑː(r)/',
    'teacher': '/ˈtiːtʃə(r)/',
    'show': '/ʃəʊ/',
    'me': '/miː/',
    'schoolbag': '/ˈskuːlbæɡ/',
    'pencil box': '/ˈpensl bɒks/',
    'black': '/blæk/',
    'pen': '/pen/',
    'pencil': '/ˈpensl/',
    'ruler': '/ˈruːlə(r)/',
    'book': '/bʊk/',
    'eraser': '/ɪˈreɪzə(r)/',
    'umbrella': '/ʌmˈbrelə/',
    'violin': '/ˌvaɪəˈlɪn/',
    'they': '/ðeɪ/',
    'colorful': '/ˈkʌləfl/',
    'flower': '/ˈflaʊə(r)/',
    'after': '/ˈɑːftə(r)/',
    'step': '/step/',
    'draw': '/drɔː/',
    'cut': '/kʌt/',
    'make': '/meɪk/',
    'window': '/ˈwɪndəʊ/',
    'X-ray': '/ˈeks reɪ/',
    'love': '/lʌv/',
    'family': '/ˈfæməli/',
    'father': '/ˈfɑːðə(r)/',
    'brother': '/ˈbrʌðə(r)/',
    'sister': '/ˈsɪstə(r)/',
    'welcome': '/ˈwelkəm/',
    'mother': '/ˈmʌðə(r)/',
    'here': '/hɪə(r)/',
    'cake': '/keɪk/',
    'zoo': '/zuː/',
    'who': '/huː/',
    'he': '/hiː/',
    'happy': '/ˈhæpi/',
    'birthday': '/ˈbɜːθdeɪ/',
    'we': '/wiː, wi/',
    'present': '/ˈpreznt/',
    'for': '/fɔː(r), fə(r)/',
    'grandpa': '/ˈɡrænpɑː/',
    'she': '/ʃiː/',
    'grandma': '/ˈɡrænmɑː/',
    'wish': '/wɪʃ/',
    'blow out': '/bləʊ aʊt/',
    'candle': '/ˈkændl/',
    'photo': '/ˈfəʊtəʊ/',
    'so': '/səʊ/',
    'cute': '/kjuːt/',
    'doctor': '/ˈdɒktə(r)/',
    'English': '/ˈɪŋɡlɪʃ/',
    'farmer': '/ˈfɑːmə(r)/',
    'cook': '/kʊk/',
    'uncle': '/ˈʌŋkl/',
    'worker': '/ˈwɜːkə(r)/',
    'aunt': '/ɑːnt/',
    'nurse': '/nɜːs/',
    'big': '/bɪɡ/',
}


def _secondary_mnemonic(key: str, headword: str, definition_zh: str, *, kind: str) -> str | None:
    if key in ROOT_MNEMONICS:
        return f'拆词联想：{ROOT_MNEMONICS[key]}'
    if key in IMAGE_MNEMONICS:
        return f'形象联想：{IMAGE_MNEMONICS[key]}'
    if key in SEMANTIC_MNEMONICS:
        return f'语义联想：{SEMANTIC_MNEMONICS[key]}'

    short = definition_zh.split('；')[0].split('，')[0].strip()
    if kind == 'phrase':
        return f'语义联想：把「{short}」和短语 {headword} 配对记忆。'

    number_words = {
        'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten',
    }
    adjectives = {
        'nice', 'good', 'big', 'cute', 'happy', 'fine', 'great', 'colorful', 'fun',
        'green', 'red', 'blue', 'yellow', 'pink', 'white', 'black', 'orange', 'old',
    }
    if key in number_words:
        return f'形象联想：想象 {short} 个数字 {headword}，边数边记住它。'
    if key in adjectives:
        return f'语义联想：看到「{short}」的事物时，就想到 {headword}。'
    return f'语义联想：把「{short}」和英文 {headword} 配对记忆。'


def mnemonic_for(headword: str, definition_zh: str, *, kind: str) -> str:
    key = headword.lower()
    parts: list[str] = []

    if key in SOUND_MNEMONICS:
        parts.append(f'谐音联想：{SOUND_MNEMONICS[key]}')

    secondary = _secondary_mnemonic(key, headword, definition_zh, kind=kind)
    if secondary:
        if parts:
            if secondary not in parts[0]:
                parts.append(secondary)
        else:
            parts.append(secondary)

    return parts[0] if len(parts) == 1 else '\n'.join(parts)
