"""Mnemonics and inflection notes for 闽教版 Grade 3 English, Volume 2 (下册).

谐音规则：仅真实谐音，不硬凑；优先语义/形象/拆词联想。
"""

from __future__ import annotations

SOUND_MNEMONICS: dict[str, str] = {
    'bag': 'bag 音近「拜格」，背着 bag 包去上学。',
    'bear': 'bear 音近「贝尔」，贝尔熊就是 bear。',
    'bird': 'bird 音近「伯德」，伯德是一只 bird 鸟。',
    'cool': 'cool 音近「酷」，cool 就是酷、凉爽。',
    'dear': 'dear 音近「迪尔」，迪尔是 dear 亲爱的。',
    'hat': 'hat 音近「哈特」，哈特戴着 hat 帽子。',
    'horse': 'horse 音近「霍斯」，霍斯骑着 horse 马。',
    'juice': 'juice 音近「久斯」，久斯爱喝 juice 果汁。',
    'lovely': 'lovely 音近「拉夫利」，拉夫利真 lovely 可爱。',
    'meat': 'meat 音近「米特」，米特爱吃 meat 肉。',
    'mouse': 'mouse 音近「毛斯」，毛斯是小 mouse 老鼠。',
    'nose': 'nose 音近「诺兹」，诺兹的 nose 鼻子。',
    'panda': 'panda 音近「潘达」，潘达就是 panda 熊猫。',
    'ride': 'ride 音近「莱德」，莱德 ride 骑马。',
    'room': 'room 音近「如姆」，如姆在 room 房间里。',
    'shoe': 'shoe 音近「舒」，舒穿着 shoe 鞋。',
    'sun': 'sun 音近「桑」，桑看着 sun 太阳。',
    'sweet': 'sweet 音近「斯威特」，斯威特喜欢 sweet 甜的。',
    'team': 'team 音近「提姆」，提姆在 team 队里。',
    'tiger': 'tiger 音近「泰格」，泰格是 tiger 老虎。',
    'toy': 'toy 音近「托伊」，托伊玩 toy 玩具。',
    'very': 'very 音近「维瑞」，维瑞 very 非常。',
    'wear': 'wear 音近「维尔」，维尔 wear 穿衣服。',
    'where': 'where 音近「威尔」，威尔问 where 哪里。',
}

ROOT_MNEMONICS: dict[str, str] = {
    'a.m.': 'ante meridiem 上午，a.m. 是上午。',
    'beautiful': 'beauty 美 + ful，beautiful 是美丽的。',
    'breakfast': 'break 打破 + fast 禁食，打破一夜禁食就是 breakfast 早餐。',
    "can't=cannot": "can 能 + not 不，can't 就是「不能、不会」。",
    'favorite': 'favor 喜爱 + ite，favorite 是最喜欢的。',
    'hamburger': 'Hamburg 汉堡 + er，hamburger 是汉堡包。',
    'healthy': 'health 健康 + y，healthy 是健康的。',
    'homework': 'home 家 + work 工作，homework 是家庭作业。',
    "isn't=is not": "is 是 + not 不，isn't 就是「不是」。",
    'new york': 'New 新 + York 约克，New York 是纽约。',
    "o'clock": "of the clock 的缩写，o'clock 是……点钟。",
    'p.m.': 'post meridiem 下午，p.m. 是下午。',
    'put away': 'put 放 + away 离开，put away 是把东西收好。',
    'put on': 'put 放 + on 上，put on 是穿上、戴上。',
    'sports ground': 'sports 运动 + ground 场地，sports ground 是运动场。',
    't-shirt': 'T 形 + shirt 衫，T-shirt 是 T 恤衫。',
    'together': 'to 向 + gether 聚集，together 是一起。',
    'vegetable': 'veget 生命 + able，vegetable 是蔬菜。',
    "you're=you are": "you 你 + are 是，you're 就是「你是」。",
}

IMAGE_MNEMONICS: dict[str, str] = {
    'animal': '想象 zoo 里各种 animal 动物。',
    'baby': '想象 baby panda 熊猫宝宝。',
    'bear': '想象 brown bear 棕熊在森林里。',
    'bed': '想象 bed 在 room 里。',
    'bike': '想象 ride a bike 骑自行车。',
    'bird': '想象 bird 在树上飞。',
    'box': '想象 shoes 在 box 盒子里。',
    'bread': '想象 breakfast 盘里的 bread 面包。',
    'carrot': '想象 orange carrot 胡萝卜。',
    'chair': '想象 sit on the chair 坐在椅子上。',
    'clock': "想象 clock 显示 eight o'clock。",
    'clothes': '想象 put away your clothes 收衣服。',
    'dinner': '想象 dinner 后 watch TV。',
    'ear': '想象 rabbit 的长 ear 耳朵。',
    'eye': '想象 panda 的大 eye 眼睛。',
    'face': '想象 touch your face 摸摸脸。',
    'forest': '想象 bear 住在 forest 森林里。',
    'fruit': '想象 sweet fruit 甜甜的水果。',
    'glass': '想象 a glass of juice 一杯果汁。',
    'grass': '想象 horse 在 green grass 上吃草。',
    'hamburger': '想象 big hamburger 大汉堡包。',
    'hat': '想象 put on your hat 戴帽子。',
    'horse': '想象 horse 在 grass 上 run fast。',
    'hotel': '想象 stay in a hotel in London。',
    'leg': '想象 horse 的四条 leg 腿。',
    'london': '想象 Big Ben 在 London 伦敦。',
    'mouth': '想象 open your mouth 张开嘴。',
    'panda': '想象 lovely panda 可爱的熊猫。',
    'paris': '想象 Eiffel Tower 在 Paris 巴黎。',
    'picture': '想象 a picture of the sun 太阳的图片。',
    'salad': '想象 healthy salad 健康沙拉。',
    'shirt': '想象 put on your shirt 穿衬衫。',
    'shorts': '想象 PE 课上穿 shorts 短裤。',
    'skirt': '想象 she wears a skirt 穿裙子。',
    'soup': '想象 hot soup 热汤。',
    'sweater': '想象 warm sweater 暖和的毛衣。',
    'tiger': '想象 cool tiger 酷酷的老虎。',
    'tokyo': '想象 Tokyo 东京的 tall buildings。',
    'tv': '想象 watch TV after dinner 晚饭后看电视。',
    'vegetable': '想象 eat your vegetables 吃蔬菜。',
}

SEMANTIC_MNEMONICS: dict[str, str] = {
    'about': 'Tell me about food. about 是关于、大约。',
    'all': 'We can all run. all 表示全部、所有。',
    'animal': 'Look at our animal! animal 是动物。',
    'baby': 'The baby panda is lovely. baby 是婴儿、幼崽。',
    'bag': 'This is my bag. bag 是包、袋子。',
    'beautiful': 'The panda is beautiful. beautiful 是美丽的。',
    'bed': 'The bed is in my room. bed 是床。',
    'breakfast': 'Eat breakfast at 7. breakfast 是早餐。',
    'brown': 'The bear is brown. brown 是棕色的。',
    'can': 'The horse can run. can 表示能、会。',
    'chair': 'Sit on the chair. chair 是椅子。',
    'chicken': 'I like chicken. chicken 是鸡肉。',
    'chinese': 'Chinese food. Chinese 是中国的。',
    'clock': 'Look at the clock. clock 是钟。',
    'clothes': 'Put away your clothes. clothes 是衣服。',
    'cool': 'The tiger is cool! cool 是酷的、凉爽的。',
    'dinner': 'We have dinner at six. dinner 是晚餐。',
    'do': 'Do you want a T-shirt? do 是助动词或「做」。',
    'drink': 'Drink some juice. drink 是喝、饮品。',
    'eat': 'Eat your vegetables. eat 是吃。',
    'eighteen': 'I am eighteen. eighteen 是十八。',
    'eleven': "Eleven o'clock. eleven 是十一。",
    'fast': 'Run fast! fast 是快地、快的。',
    'favorite': 'My favorite food. favorite 是最喜欢的。',
    'fifteen': 'Fifteen kids. fifteen 是十五。',
    'food': 'Eat healthy food. food 是食物。',
    'fourteen': 'Fourteen pictures. fourteen 是十四。',
    'fruit': 'Eat some fruit. fruit 是水果。',
    'guess': 'Guess! What animal? guess 是猜。',
    'healthy': 'Eat healthy food. healthy 是健康的。',
    'help': 'Can you help me? help 是帮助。',
    'homework': 'Do my homework. homework 是家庭作业。',
    'hungry': 'I am hungry. hungry 是饥饿的。',
    'idea': 'Good idea! idea 是想法。',
    'juice': 'A glass of juice. juice 是果汁。',
    'jump': 'The rabbit can jump. jump 是跳。',
    'kid': 'I am a kid. kid 是孩子。',
    'like': 'I like our panda. like 是喜欢。',
    'long': 'Long ears. long 是长的。',
    'lovely': 'The baby panda is lovely. lovely 是可爱的。',
    'lunch': 'Eat lunch at twelve. lunch 是午餐。',
    'meat': 'The tiger eats meat. meat 是肉。',
    'milk': 'Drink milk. milk 是牛奶。',
    'moscow': 'Moscow is a big city. Moscow 是莫斯科。',
    'mr.': 'Good morning, Mr. Wang! Mr. 是先生。',
    'much': 'Thank you very much! much 表示非常、许多。',
    'nineteen': 'Nineteen kids. nineteen 是十九。',
    'no': 'No, thank you. no 是不、不是。',
    'not': 'It is not my shoe. not 是不、没有。',
    'of': 'A glass of juice. of 表示……的。',
    'our': 'Look at our animal! our 是我们的。',
    'pe': 'We have PE today. PE 是体育。',
    'push': 'Push the door. push 是推。',
    'read': 'I read a book. read 是读。',
    'rice': 'Chicken and rice. rice 是米饭。',
    'ride': 'I can ride a horse. ride 是骑。',
    'room': 'This is my room. room 是房间。',
    'run': 'The horse can run fast. run 是跑。',
    'salad': 'Salad is healthy. salad 是沙拉。',
    'see': 'I can see a panda. see 是看。',
    'seventeen': 'Seventeen toys. seventeen 是十七。',
    'sixteen': 'Sixteen kids. sixteen 是十六。',
    'size': 'What size? size 是尺寸。',
    'small': 'The mouse is small. small 是小的。',
    'some': 'Some bread, please. some 是一些。',
    'soup': 'A bowl of soup. soup 是汤。',
    'sport': 'I like sport. sport 是运动。',
    'sweet': 'Sweet fruit. sweet 是甜的。',
    'swim': 'I can swim. swim 是游泳。',
    'these': 'These are our animals. these 是这些。',
    'thirteen': 'Thirteen kids. thirteen 是十三。',
    'thirty': 'Eight thirty. thirty 是三十。',
    'those': 'Those are pandas. those 是那些。',
    'time': 'What time is it? time 是时间。',
    'today': 'What do we eat today? today 是今天。',
    'together': 'We run together. together 是一起。',
    'twelve': "Twelve o'clock. twelve 是十二。",
    'twenty': 'Twenty kids. twenty 是二十。',
    'under': 'Under the bed. under 是在……下面。',
    'use': 'Use the clock. use 是使用。',
    'vegetable': 'Eat vegetables. vegetable 是蔬菜。',
    'want': 'I want a T-shirt. want 是想、想要。',
    'watch': 'Watch TV. watch 是观看。',
    'whose': 'Whose T-shirt is this? whose 是谁的。',
    'with': 'Read with my kid. with 是和、用、关于。',
}

INFLECTION_NOTES: dict[str, str] = {
    'animal': '复数 animals',
    'baby': '复数 babies',
    'bag': '复数 bags',
    'bear': '复数 bears',
    'bed': '复数 beds',
    'bike': '复数 bikes',
    'bird': '复数 birds',
    'box': '复数 boxes',
    'can': "否定 can't / cannot",
    'carrot': '复数 carrots',
    'chair': '复数 chairs',
    'drink': '第三人称单数 drinks',
    'ear': '复数 ears',
    'eat': '第三人称单数 eats',
    'eye': '复数 eyes',
    'face': '复数 faces',
    'guess': '第三人称单数 guesses',
    'hat': '复数 hats',
    'help': '第三人称单数 helps',
    'horse': '复数 horses',
    'jump': '第三人称单数 jumps',
    'kid': '复数 kids',
    'leg': '复数 legs',
    'like': '第三人称单数 likes',
    'mouse': '复数 mice（不规则变化）',
    'mouth': '复数 mouths',
    'nose': '复数 noses',
    'panda': '复数 pandas',
    'picture': '复数 pictures',
    'push': '第三人称单数 pushes',
    'read': '第三人称单数 reads',
    'ride': '第三人称单数 rides',
    'run': '第三人称单数 runs',
    'see': '第三人称单数 sees',
    'shirt': '复数 shirts',
    'shoe': '复数 shoes',
    'shorts': '形式不变（通常用复数）',
    'skirt': '复数 skirts',
    'sweater': '复数 sweaters',
    'swim': '第三人称单数 swims',
    'team': '复数 teams',
    'tiger': '复数 tigers',
    'toy': '复数 toys',
    'use': '第三人称单数 uses',
    'vegetable': '复数 vegetables',
    'want': '第三人称单数 wants',
    'watch': '第三人称单数 watches',
    'wear': '第三人称单数 wears',
}

DEFINITION_OVERRIDES: dict[str, str] = {
    'all': '全部；所有',
    'animal': '动物',
    'baby': '婴儿；幼崽',
    'bag': '包；手提包；袋子',
    'bear': '熊',
    'beautiful': '美丽的；漂亮的',
    'bird': '鸟',
    'brown': '棕色的；棕色',
    'can': '能；会',
    'carrot': '胡萝卜',
    'cool': '酷的；凉爽的',
    'ear': '耳朵',
    'eye': '眼睛',
    'face': '脸',
    'fast': '快速地；快的',
    'grass': '草',
    'guess': '猜',
    'hat': '帽子',
    'horse': '马',
    'jump': '跳',
    'leg': '腿',
    'like': '喜欢；像',
    'long': '长的',
    'lovely': '可爱的',
    'meat': '肉',
    'mouse': '老鼠',
    'mouth': '嘴巴',
    'Mr.': '先生',
    'no': '不；不是；没有',
    'nose': '鼻子',
    'our': '我们的',
    'panda': '熊猫',
    'ride': '骑',
    'run': '跑',
    'see': '看；看望',
    'small': '小的',
    'these': '这些',
    'those': '那些',
    'tiger': '老虎',
    'together': '一起',
    'bed': '床',
    'bike': '自行车',
    'box': '盒；箱',
    "can't=cannot": '不能；不会',
    'chair': '椅子',
    'clothes': '衣服',
    'dear': '亲爱的',
    'do': '（助动词，无词义）；做',
    'forest': '森林',
    "isn't=is not": '不是',
    'much': '非常；很；许多',
    'not': '不；没有',
    'PE': '体育',
    'put away': '把某物收拾起来（放好）',
    'put on': '穿上；戴上',
    'room': '房间',
    'shirt': '衬衫',
    'shoe': '鞋',
    'shorts': '短裤',
    'size': '尺寸',
    'skirt': '裙子',
    'sport': '运动',
    'sports ground': '运动场',
    'sweater': '毛衣',
    'swim': '游泳',
    'T-shirt': 'T 恤衫',
    'team': '队',
    'under': '在……下面',
    'very': '很；非常',
    'want': '想；想要',
    'wear': '穿；戴',
    'where': '哪里',
    'whose': '谁的',
    "you're=you are": '你是',
    'a.m.': '上午',
    'clock': '钟',
    'dinner': '正餐；晚餐',
    'eighteen': '十八',
    'eleven': '十一',
    'fifteen': '十五',
    'fourteen': '十四',
    'homework': '家庭作业',
    'hotel': '旅馆',
    'kid': '孩子',
    'London': '伦敦',
    'Moscow': '莫斯科',
    'New York': '纽约',
    'nineteen': '十九',
    "o'clock": '（几）点钟',
    'p.m.': '下午',
    'Paris': '巴黎',
    'picture': '图片',
    'push': '推',
    'read': '读；阅读',
    'seventeen': '十七',
    'sixteen': '十六',
    'sun': '太阳',
    'thirteen': '十三',
    'thirty': '三十',
    'time': '时间',
    'Tokyo': '东京',
    'toy': '玩具',
    'TV': '电视',
    'twelve': '十二',
    'twenty': '二十',
    'use': '使用',
    'watch': '观看',
    'with': '关于；具有；和；用',
    'about': '关于；大约',
    'bread': '面包',
    'breakfast': '早餐',
    'chicken': '鸡肉；鸡',
    'Chinese': '中国的；中国人',
    'drink': '喝；饮品',
    'eat': '吃',
    'favorite': '最喜欢的',
    'food': '食物',
    'fruit': '水果',
    'glass': '玻璃杯',
    'hamburger': '汉堡包',
    'healthy': '健康的',
    'help': '帮助',
    'hungry': '饥饿的',
    'idea': '想法；主意',
    'juice': '果汁',
    'lunch': '午餐',
    'milk': '牛奶',
    'of': '（表示所属、数量、其中）……的',
    'rice': '米；米饭',
    'salad': '沙拉',
    'some': '一些',
    'soup': '汤',
    'sweet': '甜的',
    'today': '今天',
    'vegetable': '蔬菜',
}

POS_OVERRIDES: dict[str, str] = {
    'a.m.': 'adv.',
    'about': 'prep./adv.',
    'all': 'det./pron.',
    'animal': 'n.',
    'baby': 'n.',
    'bag': 'n.',
    'bear': 'n.',
    'beautiful': 'adj.',
    'bed': 'n.',
    'bike': 'n.',
    'bird': 'n.',
    'box': 'n.',
    'bread': 'n.',
    'breakfast': 'n.',
    'brown': 'adj./n.',
    'can': 'v. modal',
    "can't=cannot": 'v. modal',
    'carrot': 'n.',
    'chair': 'n.',
    'chicken': 'n.',
    'Chinese': 'adj./n.',
    'clock': 'n.',
    'clothes': 'n.',
    'cool': 'adj.',
    'dear': 'adj.',
    'dinner': 'n.',
    'do': 'v./aux.',
    'drink': 'v./n.',
    'ear': 'n.',
    'eat': 'v.',
    'eye': 'n.',
    'face': 'n.',
    'fast': 'adv./adj.',
    'favorite': 'adj.',
    'food': 'n.',
    'forest': 'n.',
    'fruit': 'n.',
    'glass': 'n.',
    'grass': 'n.',
    'guess': 'v.',
    'hamburger': 'n.',
    'hat': 'n.',
    'healthy': 'adj.',
    'help': 'v./n.',
    'homework': 'n.',
    'horse': 'n.',
    'hotel': 'n.',
    'hungry': 'adj.',
    'idea': 'n.',
    "isn't=is not": 'v.',
    'juice': 'n.',
    'jump': 'v.',
    'kid': 'n.',
    'leg': 'n.',
    'like': 'v./prep.',
    'London': 'n.',
    'long': 'adj.',
    'lovely': 'adj.',
    'lunch': 'n.',
    'meat': 'n.',
    'milk': 'n.',
    'Moscow': 'n.',
    'mouse': 'n.',
    'mouth': 'n.',
    'Mr.': 'n.',
    'much': 'adv./det.',
    'New York': 'n.',
    'no': 'adv./det.',
    'nose': 'n.',
    'not': 'adv.',
    "o'clock": 'adv.',
    'of': 'prep.',
    'our': 'det.',
    'p.m.': 'adv.',
    'panda': 'n.',
    'Paris': 'n.',
    'PE': 'n.',
    'picture': 'n.',
    'push': 'v.',
    'put away': 'v. phr.',
    'put on': 'v. phr.',
    'read': 'v.',
    'rice': 'n.',
    'ride': 'v.',
    'room': 'n.',
    'run': 'v.',
    'salad': 'n.',
    'see': 'v.',
    'shirt': 'n.',
    'shoe': 'n.',
    'shorts': 'n.',
    'size': 'n.',
    'skirt': 'n.',
    'small': 'adj.',
    'some': 'det./pron.',
    'soup': 'n.',
    'sport': 'n.',
    'sports ground': 'n.',
    'sun': 'n.',
    'sweater': 'n.',
    'sweet': 'adj.',
    'swim': 'v.',
    'T-shirt': 'n.',
    'team': 'n.',
    'these': 'det./pron.',
    'those': 'det./pron.',
    'tiger': 'n.',
    'time': 'n.',
    'today': 'adv./n.',
    'together': 'adv.',
    'Tokyo': 'n.',
    'toy': 'n.',
    'TV': 'n.',
    'under': 'prep.',
    'use': 'v.',
    'vegetable': 'n.',
    'very': 'adv.',
    'want': 'v.',
    'watch': 'v.',
    'wear': 'v.',
    'whose': 'det./pron.',
    'with': 'prep.',
    "you're=you are": 'v.',
}

IPA_OVERRIDES: dict[str, str] = {
    'all': '/ɔːl/',
    'animal': '/ˈænɪml/',
    'baby': '/ˈbeɪbi/',
    'bag': '/bæɡ/',
    'bear': '/beə(r)/',
    'beautiful': '/ˈbjuːtɪfl/',
    'bird': '/bɜːd/',
    'brown': '/braʊn/',
    'can': '/kæn, kən/',
    'carrot': '/ˈkærət/',
    'cool': '/kuːl/',
    'ear': '/ɪə(r)/',
    'eye': '/aɪ/',
    'face': '/feɪs/',
    'fast': '/fɑːst/',
    'grass': '/ɡrɑːs/',
    'guess': '/ɡes/',
    'hat': '/hæt/',
    'horse': '/hɔːs/',
    'jump': '/dʒʌmp/',
    'leg': '/leɡ/',
    'like': '/laɪk/',
    'long': '/lɒŋ/',
    'lovely': '/ˈlʌvli/',
    'meat': '/miːt/',
    'mouse': '/maʊs/',
    'mouth': '/maʊθ/',
    'Mr.': '/ˈmɪstə(r)/',
    'no': '/nəʊ/',
    'nose': '/nəʊz/',
    'our': '/ˈaʊə(r), ɑː(r)/',
    'panda': '/ˈpændə/',
    'ride': '/raɪd/',
    'run': '/rʌn/',
    'see': '/siː/',
    'small': '/smɔːl/',
    'these': '/ðiːz/',
    'those': '/ðəʊz/',
    'tiger': '/ˈtaɪɡə(r)/',
    'together': '/təˈɡeðə(r)/',
    'bed': '/bed/',
    'bike': '/baɪk/',
    'box': '/bɒks/',
    "can't=cannot": '/kɑːnt/',
    'chair': '/tʃeə(r)/',
    'clothes': '/kləʊðz/',
    'dear': '/dɪə(r)/',
    'do': '/duː, də/',
    'forest': '/ˈfɒrɪst/',
    "isn't=is not": '/ˈɪznt/',
    'much': '/mʌtʃ/',
    'not': '/nɒt/',
    'PE': '/ˌpiː ˈiː/',
    'put away': '/pʊt əˈweɪ/',
    'put on': '/pʊt ɒn/',
    'room': '/ruːm/',
    'shirt': '/ʃɜːt/',
    'shoe': '/ʃuː/',
    'shorts': '/ʃɔːts/',
    'size': '/saɪz/',
    'skirt': '/skɜːt/',
    'sport': '/spɔːt/',
    'sports ground': '/spɔːts ɡraʊnd/',
    'sweater': '/ˈswetə(r)/',
    'swim': '/swɪm/',
    'T-shirt': '/ˈtiː ʃɜːt/',
    'team': '/tiːm/',
    'under': '/ˈʌndə(r)/',
    'very': '/ˈveri/',
    'want': '/wɒnt/',
    'wear': '/weə(r)/',
    'where': '/weə(r)/',
    'whose': '/huːz/',
    "you're=you are": '/jɔː(r)/',
    'a.m.': '/ˌeɪ ˈem/',
    'clock': '/klɒk/',
    'dinner': '/ˈdɪnə(r)/',
    'eighteen': '/ˌeɪˈtiːn/',
    'eleven': '/ɪˈlevn/',
    'fifteen': '/ˌfɪfˈtiːn/',
    'fourteen': '/ˌfɔːˈtiːn/',
    'homework': '/ˈhəʊmwɜːk/',
    'hotel': '/həʊˈtel/',
    'kid': '/kɪd/',
    'London': '/ˈlʌndən/',
    'Moscow': '/ˈmɒskəʊ/',
    'New York': '/ˌnjuː ˈjɔːk/',
    'nineteen': '/ˌnaɪnˈtiːn/',
    "o'clock": '/əˈklɒk/',
    'p.m.': '/ˌpiː ˈem/',
    'Paris': '/ˈpærɪs/',
    'picture': '/ˈpɪktʃə(r)/',
    'push': '/pʊʃ/',
    'read': '/riːd/',
    'seventeen': '/ˌsevnˈtiːn/',
    'sixteen': '/ˌsɪksˈtiːn/',
    'sun': '/sʌn/',
    'thirteen': '/ˌθɜːˈtiːn/',
    'thirty': '/ˈθɜːti/',
    'time': '/taɪm/',
    'Tokyo': '/ˈtəʊkiəʊ/',
    'toy': '/tɔɪ/',
    'TV': '/ˌtiː ˈviː/',
    'twelve': '/twelv/',
    'twenty': '/ˈtwenti/',
    'use': '/juːz/',
    'watch': '/wɒtʃ/',
    'with': '/wɪð, wɪθ/',
    'about': '/əˈbaʊt/',
    'bread': '/bred/',
    'breakfast': '/ˈbrekfəst/',
    'chicken': '/ˈtʃɪkɪn/',
    'Chinese': '/ˌtʃaɪˈniːz/',
    'drink': '/drɪŋk/',
    'eat': '/iːt/',
    'favorite': '/ˈfeɪvərɪt/',
    'food': '/fuːd/',
    'fruit': '/fruːt/',
    'glass': '/ɡlɑːs/',
    'hamburger': '/ˈhæmbɜːɡə(r)/',
    'healthy': '/ˈhelθi/',
    'help': '/help/',
    'hungry': '/ˈhʌŋɡri/',
    'idea': '/aɪˈdɪə/',
    'juice': '/dʒuːs/',
    'lunch': '/lʌntʃ/',
    'milk': '/mɪlk/',
    'of': '/ɒv, əv/',
    'rice': '/raɪs/',
    'salad': '/ˈsæləd/',
    'some': '/sʌm, səm/',
    'soup': '/suːp/',
    'sweet': '/swiːt/',
    'today': '/təˈdeɪ/',
    'vegetable': '/ˈvedʒtəbl/',
}



def _secondary_mnemonic(key: str, headword: str, definition_zh: str, *, kind: str) -> str | None:
    if key in ROOT_MNEMONICS:
        return f'拆词联想：{ROOT_MNEMONICS[key]}'
    if key in IMAGE_MNEMONICS:
        return f'形象联想：{IMAGE_MNEMONICS[key]}'
    if key in SEMANTIC_MNEMONICS:
        return f'语义联想：{SEMANTIC_MNEMONICS[key]}'

    short = definition_zh.split('；')[0].split('，')[0].strip()
    if kind == 'phrase':
        return f'语义联想：把「{short}」和短语 {headword} 配对记忆。'

    number_words = {
        'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen',
        'seventeen', 'eighteen', 'nineteen', 'twenty', 'thirty',
    }
    adjectives = {
        'beautiful', 'lovely', 'small', 'long', 'brown', 'cool', 'fast',
        'healthy', 'hungry', 'sweet', 'favorite',
    }
    if key in number_words:
        return f'形象联想：想象 {short} 个数字 {headword}，边数边记住它。'
    if key in adjectives:
        return f'语义联想：看到「{short}」的事物时，就想到 {headword}。'
    return f'语义联想：把「{short}」和英文 {headword} 配对记忆。'


def mnemonic_for(headword: str, definition_zh: str, *, kind: str) -> str:
    key = headword.lower()
    parts: list[str] = []

    if key in SOUND_MNEMONICS:
        parts.append(f'谐音联想：{SOUND_MNEMONICS[key]}')

    secondary = _secondary_mnemonic(key, headword, definition_zh, kind=kind)
    if secondary:
        if parts:
            if secondary not in parts[0]:
                parts.append(secondary)
        else:
            parts.append(secondary)

    return parts[0] if len(parts) == 1 else '\n'.join(parts)
