"""V1-style mnemonics for PEP Grade 3 English, Volume 1 (上册) — strict homophone rules."""

from __future__ import annotations

# 谐音联想：仅保留 headword 本身与中文读音确有相似之处的项；宁可空缺也不硬凑。
SOUND_MNEMONICS: dict[str, str] = {
    'ear': 'ear 读起来像「耳」，ear 就是耳朵。',
    'nice': 'nice 读起来像「奈斯」，夸别人真不错。',
}

ROOT_MNEMONICS: dict[str, str] = {
    'grandfather': 'grand 祖辈 + father 爸爸，grandfather 是爷爷或外公。',
    'grandmother': 'grand 祖辈 + mother 妈妈，grandmother 是奶奶或外婆。',
    'grandma': 'grand 祖辈 + ma 妈妈，grandma 是奶奶或姥姥。',
    'grandpa': 'grand 祖辈 + pa 爸爸，grandpa 是爷爷或姥爷。',
    'red panda': 'red 红色 + panda 熊猫，red panda 是小熊猫。',
}

IMAGE_MNEMONICS: dict[str, str] = {
    'hand': '想象挥手说 Hello，hand 就是手。',
    'eye': '想象用眼睛 Look，eye 就是眼睛。',
    'mouth': '想象用嘴巴 Say hello，mouth 就是嘴。',
    'arm': '想象挥动胳膊 Wave your arm 打招呼。',
    'dog': '想象小狗摇尾巴并发出 woof 的声音。',
    'cat': '想象小猫喵喵叫，cat 就是猫。',
    'rabbit': '想象兔子竖着长耳朵跳来跳去。',
    'panda': '想象圆滚滚的大熊猫吃竹子。',
    'giraffe': '想象长颈鹿伸长脖子吃树叶。',
    'apple': '想象一颗红苹果，apple 就是苹果。',
    'banana': '想象一根弯弯的黄色香蕉。',
    'tree': '想象一棵高高的树，tree 就是树。',
    'flower': '想象花园里盛开的花朵。',
    'cake': '想象生日会上香甜的蛋糕。',
    'bear': '想象棕色的大熊，bear 就是熊。',
    'duck': '想象鸭子在海里 swim 游泳。',
}

SEMANTIC_MNEMONICS: dict[str, str] = {
    # Unit 1
    'name': "What's your name? 第一次见面先问名字，name 就是名字。",
    'ear': 'Touch your ear. ear 是耳朵。',
    'share': 'We share our toys. 把玩具分给朋友一起用，就是 share，分享。',
    'smile': 'Please smile. 开心时嘴角上扬，就是 smile，微笑。',
    'listen': 'Listen to me. 老师说话时要认真听，就是 listen，倾听。',
    'help': 'I can help you. 朋友需要时伸手帮忙，就是 help，帮助。',
    'say': 'Say hello. 开口打招呼就是说 say，说；讲。',
    'friend': 'She is my friend. 一起玩、一起分享的人就是 friend，朋友。',
    'good': 'You are a good friend. good 是好的。',
    'can': 'I can help you. can 表示可以、能够。',
    "what's your name?": '第一次见面握手时，用这句话询问对方名字。',
    'nice to meet you.': '第一次见面时，用这句话表示见到你很高兴。',
    # Unit 2
    'mum': 'This is my mum. mum 是（口语）妈妈。',
    'dad': 'This is my dad. dad 是（口语）爸爸。',
    'mother': 'This is my mother. mother 是母亲、妈妈。',
    'father': 'This is my father. father 是父亲、爸爸。',
    'me': 'Look at me. me 是我（宾格）。',
    'sister': 'This is my sister. sister 是姐或妹。',
    'brother': 'This is my brother. brother 是哥或弟。',
    'family': 'I love my family. mum、dad、brother 组成 family，家庭。',
    'have': 'I have a book. have 表示有。',
    'big': 'It is a big family. big 是大的。',
    'small': 'The baby is small. small 是小的。',
    'cousin': 'My cousin is here. cousin 是堂（表）兄弟姐妹。',
    'baby': 'The baby is small. baby 是婴儿。',
    'uncle': 'This is my uncle. uncle 是叔叔、舅舅等。',
    'aunt': 'This is my aunt. aunt 是阿姨、姑姑等。',
    'this is my family.': '介绍家人照片时，用这句话开头。',
    # Unit 3
    'like': 'I like my pet. 喜欢动物或朋友时可以说 like，喜欢。',
    'pet': 'This is my pet. 家里养的小动物就是 pet，宠物。',
    'fish': 'I see a fish. fish 是鱼；也可指鱼肉。',
    'bird': 'The bird can fly. bird 是鸟。',
    'go': "Let's go to the zoo. go 是去、走。",
    'zoo': 'We go to the zoo. 可以看到很多动物的地方是 zoo，动物园。',
    'fox': 'The fox is fast. fox 是狐狸。',
    'miss': 'Miss White is kind. Miss 是对女教师的称呼。',
    'cute': 'The monkey is cute. cute 是可爱的。',
    'monkey': 'The monkey can jump. monkey 是猴子。',
    'tiger': 'The tiger is big. tiger 是老虎。',
    'elephant': 'The elephant is big. elephant 是大象。',
    'lion': 'The lion is strong. lion 是狮子。',
    'animal': 'A dog is an animal. animal 是动物。',
    'tall': 'The giraffe is tall. tall 是高的。',
    'fast': 'The fox is fast. fast 是快的。',
    'i like animals.': '表达对动物的喜爱，就说 I like animals.',
    "let's play a game.": '邀请朋友一起玩时，就说 Let\'s play a game.',
    # Unit 4
    'farm': 'This is a farm. farm 是农场。',
    'air': 'Plants give us air. air 是空气。',
    'orange': 'I eat an orange. orange 是橙子；也可指橙红色。',
    'grape': 'I like grapes. grape 是葡萄。',
    'school': 'I go to school. school 是学校。',
    'garden': 'This is a garden. garden 是花园。',
    'need': 'Plants need water. need 是需要。',
    'water': 'I water the plant. water 可动词浇水，也可名词水。',
    'grass': 'The grass is green. grass 是草、草地。',
    'plant': 'Plants need the sun. 会生长的绿色朋友是 plant，植物；也可指种植。',
    'new': 'This is my new book. new 是新的。',
    'sun': 'Plants need the sun. sun 是阳光、太阳。',
    'give': 'Plants give us air. give 是给。',
    'them': 'I can help them. them 是它们、他们、她们（宾格）。',
    # Unit 5
    'colour': 'What colour is it? red、blue、green 都是 colour，颜色。',
    'green': 'The grass is green. green 是绿色；也可作形容词绿色的。',
    'red': 'The apple is red. red 是红色；也可作形容词红色的。',
    'blue': 'The sky is blue. blue 是蓝色；也可作形容词蓝色的。',
    'make': 'Colours make a rainbow. make 是使出现、做。',
    'purple': 'The flower is purple. purple 是紫色；也可作形容词紫色的。',
    'brown': 'The bear is brown. brown 是棕色；也可作形容词棕色的。',
    'yellow': 'The sun is yellow. yellow 是黄色；也可作形容词黄色的。',
    'pink': 'The flower is pink. pink 是粉色；也可作形容词粉色的。',
    'white': 'The cloud is white. white 是白色；也可作形容词白色的。',
    'black': 'The cat is black. black 是黑色；也可作形容词黑色的。',
    'sea': 'I see the sea. sea 是海、海洋。',
    'some': 'I have some apples. some 是一些。',
    'draw': 'I can draw a tree. draw 是画。',
    # Unit 6
    'old': 'How old are you? old 可问年龄，也可表示旧的。',
    'five': 'I am five years old. five 是五。',
    'year': 'I am five years old. year 是年；years old 表示几岁。',
    'one': 'I have one book. one 是一。',
    'two': 'I have two books. two 是二。',
    'three': 'I see three birds. three 是三。',
    'four': 'I see four fish. four 是四。',
    'ten': 'I can count to ten. ten 是十。',
    'six': 'I see six apples. six 是六。',
    'seven': 'I see seven ducks. seven 是七。',
    'eight': 'I see eight flowers. eight 是八。',
    'nine': 'I see nine trees. nine 是九。',
    "o'clock": "It is three o'clock. o'clock 表示整点……点钟。",
    'cut': 'Cut the cake. cut 是切块。',
    'eat': 'I eat cake. eat 是吃。',
    'how old are you?': '想知道朋友几岁，就用 How old are you?',
}

INFLECTION_NOTES: dict[str, str] = {
    # 名词复数
    'name': '复数 names',
    'hand': '复数 hands',
    'eye': '复数 eyes',
    'ear': '复数 ears',
    'mouth': '复数 mouths',
    'arm': '复数 arms',
    'friend': '复数 friends',
    'mum': '复数 mums',
    'dad': '复数 dads',
    'grandma': '复数 grandmas',
    'grandpa': '复数 grandpas',
    'grandfather': '复数 grandfathers',
    'grandmother': '复数 grandmothers',
    'mother': '复数 mothers',
    'father': '复数 fathers',
    'sister': '复数 sisters',
    'brother': '复数 brothers',
    'family': '复数 families',
    'cousin': '复数 cousins',
    'baby': '复数 babies',
    'uncle': '复数 uncles',
    'aunt': '复数 aunts',
    'dog': '复数 dogs',
    'pet': '复数 pets',
    'cat': '复数 cats',
    'fish': '复数 fish（形式不变）',
    'bird': '复数 birds',
    'rabbit': '复数 rabbits',
    'fox': '复数 foxes',
    'panda': '复数 pandas',
    'monkey': '复数 monkeys',
    'tiger': '复数 tigers',
    'elephant': '复数 elephants',
    'lion': '复数 lions',
    'animal': '复数 animals',
    'giraffe': '复数 giraffes',
    'apple': '复数 apples',
    'banana': '复数 bananas',
    'orange': '复数 oranges',
    'grape': '复数 grapes',
    'school': '复数 schools',
    'garden': '复数 gardens',
    'flower': '复数 flowers',
    'plant': '复数 plants',
    'tree': '复数 trees',
    'colour': '复数 colours',
    'bear': '复数 bears',
    'duck': '复数 ducks',
    'cake': '复数 cakes',
    'zoo': '复数 zoos',
    'year': '复数 years',
    # 动词
    'have': '第三人称单数 has',
    'go': '第三人称单数 goes',
    'give': '第三人称单数 gives',
    'make': '第三人称单数 makes',
    'draw': '第三人称单数 draws',
    'cut': '第三人称单数 cuts',
    'eat': '第三人称单数 eats',
    'water': '第三人称单数 waters',
    'need': '第三人称单数 needs',
    'share': '第三人称单数 shares',
    'help': '第三人称单数 helps',
    'say': '第三人称单数 says',
    'listen': '第三人称单数 listens',
}

DEFINITION_OVERRIDES: dict[str, str] = {
    # Unit 1
    'name': '名字',
    'nice': '令人愉快的；友好的',
    'ear': '耳朵',
    'hand': '手',
    'eye': '眼睛',
    'mouth': '嘴',
    'arm': '胳膊',
    'can': '可以',
    'share': '分享',
    'smile': '微笑；笑',
    'listen': '听；倾听',
    'help': '帮助',
    'say': '说；讲',
    'friend': '朋友',
    'good': '好的',
    "what's your name?": '你叫什么名字？',
    'nice to meet you.': '见到你很高兴。',
    # Unit 2
    'mum': '（口语）妈妈',
    'dad': '（口语）爸爸；爹爹',
    'grandma': '奶奶；姥姥',
    'grandpa': '爷爷；姥爷',
    'grandfather': '（外）祖父；爷爷；姥爷；外公',
    'grandmother': '（外）祖母；奶奶；姥姥；外婆',
    'mother': '母亲；妈妈',
    'father': '父亲；爸爸',
    'me': '我',
    'sister': '姐；妹',
    'family': '家；家庭',
    'have': '有',
    'big': '大的',
    'cousin': '堂（表）兄弟；堂（表）姐妹',
    'brother': '哥；弟',
    'baby': '婴儿',
    'uncle': '伯父；叔父；舅父；姑父；姨父',
    'aunt': '伯母；婶母；舅母；姑母；姨母',
    'small': '小的',
    'this is my family.': '这是我的家人。',
    # Unit 3
    'like': '喜欢',
    'dog': '狗',
    'pet': '宠物',
    'cat': '猫',
    'fish': '鱼；鱼肉',
    'bird': '鸟',
    'rabbit': '兔',
    'go': '去；走',
    'zoo': '动物园',
    'fox': '狐狸',
    'miss': '（学生对女教师的称呼）老师；女士',
    'panda': '大熊猫',
    'red panda': '小熊猫',
    'cute': '可爱的',
    'monkey': '猴子',
    'tiger': '老虎',
    'elephant': '大象',
    'lion': '狮；狮子',
    'animal': '动物',
    'giraffe': '长颈鹿',
    'tall': '高的',
    'fast': '快的',
    'i like animals.': '我喜欢动物。',
    "let's play a game.": '我们一起玩游戏吧。',
    # Unit 4
    'apple': '苹果',
    'banana': '香蕉',
    'farm': '农场',
    'air': '空气',
    'orange': '橙子；柑橘',
    'grape': '葡萄',
    'school': '学校',
    'garden': '花园',
    'need': '需要',
    'water': '给……浇水；水',
    'flower': '花；花朵',
    'grass': '草；草地',
    'plant': '种植；植物',
    'new': '新的',
    'tree': '树',
    'sun': '阳光；太阳',
    'give': '给',
    'them': '它们；他们；她们',
    # Unit 5
    'colour': '颜色',
    'green': '绿色；绿色的',
    'red': '红色；红色的',
    'blue': '蓝色；蓝色的',
    'make': '使出现；做',
    'purple': '紫色；紫色的',
    'brown': '棕色；棕色的',
    'bear': '熊',
    'yellow': '黄色；黄色的',
    'duck': '鸭',
    'sea': '海；海洋',
    'some': '一些',
    'pink': '粉色；粉色的',
    'draw': '画',
    'white': '白色；白色的',
    'black': '黑色；黑色的',
    # Unit 6
    'old': '（多少）岁；年纪；旧的',
    'five': '五',
    'year': '年纪；年',
    'one': '一',
    'two': '二',
    'three': '三',
    'four': '四',
    'ten': '十',
    'six': '六',
    'seven': '七',
    'eight': '八',
    'nine': '九',
    "o'clock": '（表示整点）……点钟',
    'cut': '切块',
    'eat': '吃',
    'cake': '蛋糕',
    'how old are you?': '你几岁了？',
}

# PDF 词表与通用 pos 推断冲突时的修正
POS_OVERRIDES: dict[str, str] = {
    'can': 'modal v.',
    'me': 'pron.',
    'them': 'pron.',
    'some': 'det.',
    'miss': 'n.',
    'water': 'v./n.',
    'plant': 'v./n.',
    'colour': 'n.',
    'green': 'adj./n.',
    'red': 'adj./n.',
    'blue': 'adj./n.',
    'purple': 'adj./n.',
    'brown': 'adj./n.',
    'yellow': 'adj./n.',
    'pink': 'adj./n.',
    'white': 'adj./n.',
    'black': 'adj./n.',
    'old': 'adj.',
    "o'clock": 'adv.',
}

IPA_OVERRIDES: dict[str, str] = {
    # Unit 1
    'name': '/neɪm/',
    'nice': '/naɪs/',
    'ear': '/ɪə(r)/',
    'hand': '/hænd/',
    'eye': '/aɪ/',
    'mouth': '/maʊθ/',
    'arm': '/ɑːm/',
    'can': '/kən, kæn/',
    'share': '/ʃeə(r)/',
    'smile': '/smaɪl/',
    'listen': '/ˈlɪsn/',
    'help': '/help/',
    'say': '/seɪ/',
    'friend': '/frend/',
    'good': '/ɡʊd/',
    "what's your name?": '/wɒts jɔː(r) neɪm/',
    'nice to meet you.': '/naɪs tə miːt juː/',
    # Unit 2
    'mum': '/mʌm/',
    'dad': '/dæd/',
    'grandma': '/ˈɡrænmɑː/',
    'grandpa': '/ˈɡrænpɑː/',
    'grandfather': '/ˈɡrænfɑːðə(r)/',
    'grandmother': '/ˈɡrænmʌðə(r)/',
    'mother': '/ˈmʌðə(r)/',
    'father': '/ˈfɑːðə(r)/',
    'me': '/miː/',
    'sister': '/ˈsɪstə(r)/',
    'family': '/ˈfæməli/',
    'have': '/hæv/',
    'big': '/bɪɡ/',
    'cousin': '/ˈkʌzn/',
    'brother': '/ˈbrʌðə(r)/',
    'baby': '/ˈbeɪbi/',
    'uncle': '/ˈʌŋkl/',
    'aunt': '/ɑːnt/',
    'small': '/smɔːl/',
    'this is my family.': '/ðɪs ɪz maɪ ˈfæməli/',
    # Unit 3
    'like': '/laɪk/',
    'dog': '/dɒɡ/',
    'pet': '/pet/',
    'cat': '/kæt/',
    'fish': '/fɪʃ/',
    'bird': '/bɜːd/',
    'rabbit': '/ˈræbɪt/',
    'go': '/ɡəʊ/',
    'zoo': '/zuː/',
    'fox': '/fɒks/',
    'miss': '/mɪs/',
    'panda': '/ˈpændə/',
    'red panda': '/red ˈpændə/',
    'cute': '/kjuːt/',
    'monkey': '/ˈmʌŋki/',
    'tiger': '/ˈtaɪɡə(r)/',
    'elephant': '/ˈelɪfənt/',
    'lion': '/ˈlaɪən/',
    'animal': '/ˈænɪml/',
    'giraffe': '/dʒəˈrɑːf/',
    'tall': '/tɔːl/',
    'fast': '/fɑːst/',
    'i like animals.': '/aɪ laɪk ˈænɪmlz/',
    "let's play a game.": '/lets pleɪ ə ɡeɪm/',
    # Unit 4
    'apple': '/ˈæpl/',
    'banana': '/bəˈnɑːnə/',
    'farm': '/fɑːm/',
    'air': '/eə(r)/',
    'orange': '/ˈɒrɪndʒ/',
    'grape': '/ɡreɪp/',
    'school': '/skuːl/',
    'garden': '/ˈɡɑːdn/',
    'need': '/niːd/',
    'water': '/ˈwɔːtə(r)/',
    'flower': '/ˈflaʊə(r)/',
    'grass': '/ɡrɑːs/',
    'plant': '/plɑːnt/',
    'new': '/njuː/',
    'tree': '/triː/',
    'sun': '/sʌn/',
    'give': '/ɡɪv/',
    'them': '/ðəm, ðem/',
    # Unit 5
    'colour': '/ˈkʌlə(r)/',
    'green': '/ɡriːn/',
    'red': '/red/',
    'blue': '/bluː/',
    'make': '/meɪk/',
    'purple': '/ˈpɜːpl/',
    'brown': '/braʊn/',
    'bear': '/beə(r)/',
    'yellow': '/ˈjeləʊ/',
    'duck': '/dʌk/',
    'sea': '/siː/',
    'some': '/səm, sʌm/',
    'pink': '/pɪŋk/',
    'draw': '/drɔː/',
    'white': '/waɪt/',
    'black': '/blæk/',
    # Unit 6
    'old': '/əʊld/',
    'five': '/faɪv/',
    'year': '/jɪə(r)/',
    'one': '/wʌn/',
    'two': '/tuː/',
    'three': '/θriː/',
    'four': '/fɔː(r)/',
    'ten': '/ten/',
    'six': '/sɪks/',
    'seven': '/ˈsevn/',
    'eight': '/eɪt/',
    'nine': '/naɪn/',
    "o'clock": '/əˈklɒk/',
    'cut': '/kʌt/',
    'eat': '/iːt/',
    'cake': '/keɪk/',
    'how old are you?': '/haʊ əʊld ɑː(r) juː/',
}


def _secondary_mnemonic(key: str, headword: str, definition_zh: str, *, kind: str) -> str | None:
    if key in ROOT_MNEMONICS:
        return f'拆词联想：{ROOT_MNEMONICS[key]}'
    if key in IMAGE_MNEMONICS:
        return f'形象联想：{IMAGE_MNEMONICS[key]}'
    if key in SEMANTIC_MNEMONICS:
        return f'语义联想：{SEMANTIC_MNEMONICS[key]}'

    short = definition_zh.split('；')[0].split('，')[0].strip()
    if kind == 'phrase':
        return f'语义联想：把「{short}」和短语 {headword} 配对记忆。'

    number_words = {
        'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten',
    }
    adjectives = {
        'nice', 'good', 'big', 'small', 'cute', 'tall', 'fast', 'new',
        'green', 'red', 'blue', 'purple', 'brown', 'yellow', 'pink', 'white', 'black', 'old',
    }
    if key in number_words:
        return f'形象联想：想象 {short} 个数字 {headword}，边数边记住它。'
    if key in adjectives:
        return f'语义联想：看到「{short}」的事物时，就想到 {headword}。'
    return f'语义联想：把「{short}」和英文 {headword} 配对记忆。'


def mnemonic_for(headword: str, definition_zh: str, *, kind: str) -> str:
    key = headword.lower()
    parts: list[str] = []

    if key in SOUND_MNEMONICS:
        parts.append(f'谐音联想：{SOUND_MNEMONICS[key]}')

    secondary = _secondary_mnemonic(key, headword, definition_zh, kind=kind)
    if secondary:
        if parts:
            if secondary not in parts[0]:
                parts.append(secondary)
        else:
            parts.append(secondary)

    return parts[0] if len(parts) == 1 else '\n'.join(parts)
