"""Mnemonics and inflection notes for PEP Grade 4 English, Volume 1 (上册).

谐音规则与 en-grade3-v2-rj 一致：仅真实谐音，不硬凑；优先语义/形象/拆词联想。
"""

from __future__ import annotations

# 谐音联想：仅 headword 与中文读音确有相似处才写。
SOUND_MNEMONICS: dict[str, str] = {
    'pe': 'PE 是 Physical Education 的缩写，就是体育（课）。',
}

ROOT_MNEMONICS: dict[str, str] = {
    'make the bed': 'make 整理 + the bed 床，合起来就是铺床。',
    'look after': 'look 看 + after 在……之后，look after 是照看、照顾。',
    'get together': 'get 聚 + together 一起，get together 是聚会、相聚。',
    'a lot of': 'a 一个 + lot 大量，a lot of 就是许多。',
    'firefighter': 'fire 火 + fighter 战斗者，firefighter 是消防员。',
    'snowman': 'snow 雪 + man 人，snowman 是雪人。',
    'playground': 'play 玩 + ground 场地，playground 是操场。',
    'football': 'foot 脚 + ball 球，football 是用脚踢的球类运动。',
    'basketball': 'basket 篮 + ball 球，basketball 是篮球。',
    't-shirt': 'T 形 + shirt 衫，T-shirt 是 T 恤衫。',
    'snowy': 'snow 雪 + y，snowy 是多雪的。',
    'rainy': 'rain 雨 + y，rainy 是多雨的。',
    'windy': 'wind 风 + y，windy 是多风的。',
    'cloudy': 'cloud 云 + y，cloudy 是多云的。',
    'sunny': 'sun 太阳 + ny，sunny 是阳光充足的。',
}

IMAGE_MNEMONICS: dict[str, str] = {
    'doctor': '想象穿白大褂的 doctor 在医院里看病。',
    'farmer': '想象 farmer 在田野里干活。',
    'nurse': '想象 nurse 在病房里照顾病人。',
    'floor': '想象用扫把扫 floor 地板。',
    'room': '想象自己的 room 里有一张床和书桌。',
    'kite': '想象在公园放 kite 风筝。',
    'snowman': '想象滚雪球堆 snowman 雪人。',
    'glove': '想象冬天戴上 glove 手套暖手。',
    'coat': '想象天冷穿上 coat 大衣。',
    'hospital': '想象 hospital 门口有红十字标志。',
    'library': '想象 library 里有很多书架，要安静。',
    'playground': '想象 playground 上有同学在跑步玩耍。',
}

SEMANTIC_MNEMONICS: dict[str, str] = {
    # Unit 1
    'job': "What's your job? 问职业，job 就是工作。",
    'office worker': 'office 办公室 + worker 工人，office worker 是公司职员。',
    'factory worker': 'factory 工厂 + worker 工人，factory worker 是工厂工人。',
    'busy': 'Are you busy? busy 表示忙碌。',
    'tired': "I'm tired. tired 是疲倦的。",
    'chore': 'I do chores at home. chore 是家务杂活。',
    'cook': 'Mum can cook well. cook 可指做饭，也可指厨师。',
    'clean': 'I clean my room. clean 是打扫；干净的。',
    'sweep': 'I sweep the floor. sweep 是扫。',
    'together': 'We work together. together 是一起、共同。',
    'look after': 'I look after my little sister. look after 是照顾、照看。',
    'get together': 'We get together on Spring Festival. get together 是聚会。',
    'people': 'Many people help us. people 是人们。',
    'child': 'Every child should help. child 是儿童、小孩。',
    # Unit 2
    'his': 'This is his book. his 表示他的。',
    'strong': 'He is tall and strong. strong 是强壮的。',
    'hair': 'She has long hair. hair 是头发。',
    'also': "He's also kind. also 表示也。",
    'kind': 'She is very kind. kind 是友好的。',
    'quiet': 'She is quiet in class. quiet 是文静的。',
    'best': 'He is my best friend. best 是最好的。',
    'read': 'I read books every day. read 是阅读。',
    'chinese': 'We have Chinese on Tuesday. Chinese 可指中文或语文课。',
    'play': 'We play in the playground. play 是玩耍。',
    'game': "Let's play a game. game 是游戏。",
    'always': 'She always helps me. always 是总是。',
    # Unit 3
    'afternoon': 'Good afternoon! afternoon 是下午。',
    'there': 'There is a park. there 表示存在或在那里。',
    'park': "Let's go to the park. park 是公园。",
    'over': 'The shop is over there. over 可表示在远端。',
    'shop': 'There is a shop on my street. shop 是商店。',
    'toilet': 'Where is the toilet? toilet 是卫生间。',
    'bus stop': 'bus 公共汽车 + stop 站，bus stop 是公共汽车站。',
    'sport': 'I like sport. sport 是体育运动。',
    'walk': 'I walk to school. walk 是行走、散步。',
    'community': 'We live in a nice community. community 是社区。',
    'favourite': 'My favourite place is the library. favourite 是最喜欢的。',
    'place': 'This is a great place. place 是地方。',
    'photo': 'This is a photo of my family. photo 是照片。',
    'story': 'She tells us a story. story 是故事。',
    'buy': 'I want to buy a book. buy 是购买。',
    # Unit 4
    'firefighter': 'The firefighter is brave. firefighter 是消防员。',
    'why': 'Why is he a firefighter? why 问原因，为什么。',
    'driver': 'My uncle is a bus driver. driver 是司机。',
    'cleaner': 'The cleaner keeps our school clean. cleaner 是清洁工。',
    'delivery worker': 'delivery 递送 + worker 工人，delivery worker 是快递员。',
    'police officer': 'police 警察 + officer 官员，police officer 是警察、警员。',
    'now': "I'm busy now. now 是现在。",
    'old': 'My grandpa is old but strong. old 可指年纪大或旧的。',
    'tell': 'Tell me your name. tell 是告诉、讲述。',
    'everyone': 'Hello, everyone! everyone 是每人、大家。',
    'ms': 'Good morning, Ms Wang. Ms 用于女士姓氏前。',
    # Unit 5
    'speak': 'We speak English in class. speak 是说话。',
    'weather': "What's the weather like? weather 是天气。",
    'hot': "It's hot in summer. hot 是热的。",
    'bad': 'The weather is bad today. bad 是令人不快的、坏的。',
    'cold': "It's cold in winter. cold 是冷的。",
    'cool': "It's cool in autumn. cool 是凉爽的。",
    'warm': "It's warm in spring. warm 是温暖的。",
    'tomorrow': 'See you tomorrow. tomorrow 是明天。',
    'rain': 'It often rains in spring. rain 可作动词下雨或名词雨。',
    'closed': 'The shop is closed. closed 是关闭的。',
    'film': "Let's watch a film. film 是电影。",
    'idea': "That's a good idea! idea 是主意。",
    'fly': 'We fly kites in the park. fly 是放（风筝）、飞。',
    'fun': 'Flying kites is fun. fun 是乐趣。',
    'their': 'Their classroom is big. their 是他们的。',
    'swim': 'I can swim. swim 是游泳。',
    'sydney': 'Sydney is in Australia. Sydney 是悉尼。',
    # Unit 6
    'whose': 'Whose sweater is this? whose 问所属，谁的。',
    'sweater': 'I wear a sweater in autumn. sweater 是毛衣。',
    'sock': 'I need a pair of socks. sock 是短袜。',
    'mine': 'This book is mine. mine 是我的（东西）。',
    'wear': 'I wear a coat in winter. wear 是穿、戴。',
    'shirt': 'He wears a white shirt. shirt 是衬衫。',
    'dress': 'She wears a red dress. dress 是连衣裙。',
    'which': 'Which season do you like? which 问哪一个。',
    'season': 'There are four seasons. season 是季节。',
    'winter': "It's cold in winter. winter 是冬天。",
    'snow': 'It snows in winter. snow 可动词下雪或名词雪。',
    'spring': 'Spring is warm. spring 是春天。',
    'summer': 'Summer is hot. summer 是夏天。',
    'autumn': 'Autumn is cool. autumn 是秋天。',
    'fall': 'Leaves fall from the tree. fall 是落下。',
    'leaf': 'The leaf is yellow. leaf 是叶子。',
}


DEFINITION_OVERRIDES: dict[str, str] = {
    'PE': '体育（课）',
    'job': '工作；职业',
    'doctor': '医生',
    'farmer': '农场主；农民',
    'nurse': '护士',
    'office worker': '公司职员',
    'factory worker': '工厂工人',
    'busy': '忙碌的',
    'tired': '疲倦的',
    'chore': '家庭杂务',
    'cook': '烹饪；煮；厨师',
    'clean': '打扫；干净的',
    'room': '房间',
    'look after': '照顾',
    'sweep': '扫',
    'floor': '地板；地面',
    'together': '在一起；共同',
    'people': '人；人们',
    'child': '（复数children/ˈtʃɪldrən/）儿童；小孩',
    'his': '他的',
    'strong': '强壮的',
    'hair': '头发',
    'also': '也',
    'kind': '友好的',
    'quiet': '文静的',
    'best': '最好的',
    'read': '阅读',
    'Chinese': '中文；中国人；中国的',
    'play': '玩耍',
    'game': '游戏',
    'football': '足球运动',
    'basketball': '篮球运动',
    'always': '总是',
    'afternoon': '下午',
    'there': '（表示存在或发生）；在那里',
    'playground': '游乐场；操场',
    'park': '公园',
    'over': '在……的远端（或对面）',
    'hospital': '医院',
    'shop': '商店',
    'toilet': '厕所；卫生间',
    'bus stop': '公共汽车站',
    'library': '图书馆',
    'sport': '体育运动',
    'walk': '散步；行走',
    'community': '社区',
    'favourite': '最喜欢的',
    'place': '地方；场所',
    'photo': '照片',
    'story': '故事',
    'buy': '购买',
    'firefighter': '消防队员',
    'why': '为什么',
    'driver': '司机',
    'cleaner': '清洁工',
    'delivery worker': '快递员',
    'police officer': '警察；警员',
    'a lot of': '大量；许多',
    'now': '现在',
    'make the bed': '铺床',
    'old': '过去的；年纪大的；老的',
    'tell': '讲述；告诉',
    'everyone': '每人',
    'Ms': '（用于女子的姓氏或姓名前，不指明婚否）女士',
    'speak': '说话；发言',
    'weather': '天气',
    'sunny': '阳光充足的',
    'hot': '热的',
    'bad': '令人不快的；坏的',
    'cold': '冷的',
    'windy': '多风的',
    'cloudy': '多云的',
    'rainy': '阴雨的',
    'snowy': '多雪的',
    'cool': '凉爽的',
    'warm': '温暖的',
    'tomorrow': '在明天',
    'rain': '下雨；雨',
    'closed': '关闭的',
    'film': '电影',
    'idea': '想法；主意',
    'fly': '操纵（飞行器等）；飞',
    'kite': '风筝',
    'snowman': '雪人',
    'fun': '享乐；乐趣',
    'their': '他们的；她们的；它们的',
    'swim': '游泳',
    'Sydney': '悉尼',
    'whose': '谁的',
    'sweater': '毛衣',
    'sock': '短袜',
    'mine': '我的',
    'wear': '穿；戴',
    'shirt': '衬衫',
    'coat': '大衣；外套',
    'dress': '连衣裙',
    'which': '哪一个；哪一些',
    'season': '季节',
    'winter': '冬天',
    'snow': '下雪；雪',
    'get together': '聚会',
    'spring': '春天',
    'summer': '夏天',
    'autumn': '秋天',
    'T-shirt': 'T恤衫',
    'fall': '落下',
    'leaf': '（复数leaves/liːvz/）叶',
    'glove': '手套',
}

IPA_OVERRIDES: dict[str, str] = {
    'pe': '/ˌpiː ˈiː/',
    'job': '/dʒɒb/',
    'doctor': '/ˈdɒktə(r)/',
    'farmer': '/ˈfɑːmə(r)/',
    'nurse': '/nɜːs/',
    'office worker': '/ˈɒfɪs ˈwɜːkə(r)/',
    'factory worker': '/ˈfæktri ˈwɜːkə(r)/',
    'busy': '/ˈbɪzi/',
    'tired': '/ˈtaɪəd/',
    'chore': '/tʃɔː(r)/',
    'cook': '/kʊk/',
    'clean': '/kliːn/',
    'room': '/ruːm/',
    'look after': '/lʊk ˈɑːftə(r)/',
    'sweep': '/swiːp/',
    'floor': '/flɔː(r)/',
    'together': '/təˈɡeðə(r)/',
    'people': '/ˈpiːpl/',
    'child': '/tʃaɪld/',
    'his': '/hɪz/',
    'strong': '/strɒŋ/',
    'hair': '/heə(r)/',
    'also': '/ˈɔːlsəʊ/',
    'kind': '/kaɪnd/',
    'quiet': '/ˈkwaɪət/',
    'best': '/best/',
    'read': '/riːd/',
    'chinese': '/ˌtʃaɪˈniːz/',
    'play': '/pleɪ/',
    'game': '/ɡeɪm/',
    'football': '/ˈfʊtbɔːl/',
    'basketball': '/ˈbɑːskɪtbɔːl/',
    'always': '/ˈɔːlweɪz/',
    'afternoon': '/ˌɑːftəˈnuːn/',
    'there': '/ðeə(r)/',
    'playground': '/ˈpleɪɡraʊnd/',
    'park': '/pɑːk/',
    'over': '/ˈəʊvə(r)/',
    'hospital': '/ˈhɒspɪtl/',
    'shop': '/ʃɒp/',
    'toilet': '/ˈtɔɪlət/',
    'bus stop': '/bʌs stɒp/',
    'library': '/ˈlaɪbrəri/',
    'sport': '/spɔːt/',
    'walk': '/wɔːk/',
    'community': '/kəˈmjuːnəti/',
    'favourite': '/ˈfeɪvərɪt/',
    'place': '/pleɪs/',
    'photo': '/ˈfəʊtəʊ/',
    'story': '/ˈstɔːri/',
    'buy': '/baɪ/',
    'firefighter': '/ˈfaɪəfaɪtə(r)/',
    'why': '/waɪ/',
    'driver': '/ˈdraɪvə(r)/',
    'cleaner': '/ˈkliːnə(r)/',
    'delivery worker': '/dɪˈlɪvəri ˈwɜːkə(r)/',
    'police officer': '/pəˈliːs ˈɒfɪsə(r)/',
    'a lot of': '/ə lɒt əv/',
    'now': '/naʊ/',
    'make the bed': '/meɪk ðə bed/',
    'old': '/əʊld/',
    'tell': '/tel/',
    'everyone': '/ˈevriwʌn/',
    'ms': '/mɪz/',
    'speak': '/spiːk/',
    'weather': '/ˈweðə(r)/',
    'sunny': '/ˈsʌni/',
    'hot': '/hɒt/',
    'bad': '/bæd/',
    'cold': '/kəʊld/',
    'windy': '/ˈwɪndi/',
    'cloudy': '/ˈklaʊdi/',
    'rainy': '/ˈreɪni/',
    'snowy': '/ˈsnəʊi/',
    'cool': '/kuːl/',
    'warm': '/wɔːm/',
    'tomorrow': '/təˈmɒrəʊ/',
    'rain': '/reɪn/',
    'closed': '/kləʊzd/',
    'film': '/fɪlm/',
    'idea': '/aɪˈdɪə/',
    'fly': '/flaɪ/',
    'kite': '/kaɪt/',
    'snowman': '/ˈsnəʊmæn/',
    'fun': '/fʌn/',
    'their': '/ðeə(r)/',
    'swim': '/swɪm/',
    'sydney': '/ˈsɪdni/',
    'whose': '/huːz/',
    'sweater': '/ˈswetə(r)/',
    'sock': '/sɒk/',
    'mine': '/maɪn/',
    'wear': '/weə(r)/',
    'shirt': '/ʃɜːt/',
    'coat': '/kəʊt/',
    'dress': '/dres/',
    'which': '/wɪtʃ/',
    'season': '/ˈsiːzn/',
    'winter': '/ˈwɪntə(r)/',
    'snow': '/snəʊ/',
    'get together': '/ɡet təˈɡeðə(r)/',
    'spring': '/sprɪŋ/',
    'summer': '/ˈsʌmə(r)/',
    'autumn': '/ˈɔːtəm/',
    't-shirt': '/ˈtiːʃɜːt/',
    'fall': '/fɔːl/',
    'leaf': '/liːf/',
    'glove': '/ɡlʌv/',
}

POS_OVERRIDES: dict[str, str] = {
    'pe': 'n.',
    'chinese': 'n.',
    'ms': 'n.',
    'cook': 'v.',
    'clean': 'v.',
    'read': 'v.',
    'play': 'v.',
    'rain': 'v.',
    'fly': 'v.',
    'snow': 'v.',
    'fall': 'v.',
    'make the bed': 'v. phrase',
    'look after': 'v. phrase',
    'get together': 'v. phrase',
    'a lot of': 'adv. phrase',
    'office worker': 'n. phrase',
    'factory worker': 'n. phrase',
    'bus stop': 'n. phrase',
    'delivery worker': 'n. phrase',
    'police officer': 'n. phrase',
}

INFLECTION_NOTES: dict[str, str] = {
    # 名词复数
    'child': '复数 children',
    'best': 'good 的最高级；比较级 better',
    'person': '复数 people',
    'man': '复数 men（如 snowman → snowmen）',
    'woman': '复数 women',
    'leaf': '复数 leaves',
    'foot': '复数 feet',
    'tooth': '复数 teeth',
    'library': '复数 libraries',
    'story': '复数 stories',
    'photo': '复数 photos',
    'potato': '复数 potatoes',
    'hero': '复数 heroes',
    'community': '复数 communities',
    'family': '复数 families',
    'city': '复数 cities',
    'country': '复数 countries',
    'class': '复数 classes',
    'box': '复数 boxes',
    'dress': '复数 dresses（名词）',
    'glove': '复数 gloves',
    'sock': '复数 socks',
    'kite': '复数 kites',
    'snowman': '复数 snowmen',
    'chore': '复数 chores',
    'people': '已是复数，单数 person',
    'doctor': '复数 doctors',
    'farmer': '复数 farmers',
    'nurse': '复数 nurses',
    'driver': '复数 drivers',
    'cleaner': '复数 cleaners',
    'firefighter': '复数 firefighters',
    'shop': '复数 shops',
    'place': '复数 places',
    # 动词
    'cook': '第三人称单数 cooks；过去式 cooked',
    'clean': '第三人称单数 cleans；过去式 cleaned',
    'sweep': '第三人称单数 sweeps；过去式 swept',
    'read': '第三人称单数 reads /riːdz/；过去式 read /red/',
    'play': '第三人称单数 plays；过去式 played',
    'walk': '第三人称单数 walks；过去式 walked',
    'buy': '第三人称单数 buys；过去式 bought',
    'tell': '第三人称单数 tells；过去式 told',
    'speak': '第三人称单数 speaks；过去式 spoke',
    'rain': '第三人称单数 rains；过去式 rained',
    'fly': '第三人称单数 flies；过去式 flew',
    'swim': '第三人称单数 swims；过去式 swam',
    'wear': '第三人称单数 wears；过去式 wore',
    'fall': '第三人称单数 falls；过去式 fell',
    'snow': '第三人称单数 snows；过去式 snowed',
}


def _secondary_mnemonic(key: str, headword: str, definition_zh: str, *, kind: str) -> str | None:
    if key in ROOT_MNEMONICS:
        return f'拆词联想：{ROOT_MNEMONICS[key]}'
    if key in IMAGE_MNEMONICS:
        return f'形象联想：{IMAGE_MNEMONICS[key]}'
    if key in SEMANTIC_MNEMONICS:
        return f'语义联想：{SEMANTIC_MNEMONICS[key]}'

    short = definition_zh.split('；')[0].split('，')[0].strip()
    if kind == 'phrase':
        return f'语义联想：{headword} 表示「{short}」，在课文对话里反复出现。'
    return f'语义联想：{headword} 表示「{short}」，结合本课例句记忆。'


def mnemonic_for(headword: str, definition_zh: str, *, kind: str) -> str:
    key = headword.lower()
    parts: list[str] = []

    if key in SOUND_MNEMONICS:
        parts.append(f'谐音联想：{SOUND_MNEMONICS[key]}')

    secondary = _secondary_mnemonic(key, headword, definition_zh, kind=kind)
    if secondary:
        if parts:
            if secondary not in parts[0]:
                parts.append(secondary)
        else:
            parts.append(secondary)

    return parts[0] if len(parts) == 1 else '\n'.join(parts)
