"""Mnemonics and inflection notes for PEP Grade 5 English, Volume 1 (上册).

谐音规则与 en-grade3-v2-rj 一致：仅真实谐音，不硬凑；优先语义/形象/拆词联想。
"""

from __future__ import annotations

# 谐音联想：仅 headword 与中文读音确有相似处才写。
SOUND_MNEMONICS: dict[str, str] = {
    'tea': 'tea 就是「茶」，发音与中文「茶」相近。',
    'beef': 'beef 音近「比夫」，比夫常联想成牛肉。',
    'mrs': 'Mrs 音近「密斯」，对已婚女士的称呼。',
    'show': 'show 音近「秀」，TV show 就是电视节目。',
    'piano': 'piano 音近「皮阿诺」，钢琴的经典叫法。',
    'coconut': 'coconut 里 coco 音近「可可」，椰子可做成可可味饮品。',
    'star': 'star 音近「斯达」，明星 star 很「斯达」。',
    'team': 'team 音近「替姆」，同一 team 里大家互相替着上。',
}

ROOT_MNEMONICS: dict[str, str] = {
    'hard-working': 'hard 努力 + working 工作，hard-working 是勤奋的。',
    'weekend': 'week 周 + end 末，weekend 是周末。',
    'grandparent': 'grand 祖辈 + parent 父母，grandparent 是祖父母。',
    'ping-pong': 'ping pong 是球来回弹的声音，ping-pong 是乒乓球。',
    'ice cream': 'ice 冰 + cream 奶油，ice cream 是冰淇淋。',
    'raincoat': 'rain 雨 + coat 外套，raincoat 是雨衣。',
    'sometimes': 'some 有些 + times 次，sometimes 是有时候。',
    'usually': 'usual 通常 + ly，usually 是通常、平常。',
    'wonderful': 'wonder 惊奇 + ful，wonderful 是极好的、精彩的。',
    'different': 'differ 不同 + ent，different 是不同的。',
    'hamburger': 'ham 火腿 + burger 堡，hamburger 是汉堡包。',
    'umbrella': 'um 音 + brella 音，umbrella 是挡雨遮阳的伞。',
    'because': 'be 因为 + cause 原因，because 是因为。',
    'exercise': 'ex 向外 + ercise，exercise 是锻炼、运动。',
    'take care of': 'take 照管 + care 关心 + of，take care of 是照顾、爱护。',
    'go hiking': 'go 去 + hiking 徒步，go hiking 是徒步旅行。',
    'pull up': 'pull 拉 + up 起，pull up 是把……拔起。',
    'a little': 'a 一点 + little 少量，a little 是少许、一点。',
    'waterfall': 'water 水 + fall 落下，waterfall 是瀑布。',
    'before': 'be 在 + fore 前面，before 是在…之前。',
    'subject': 'sub 下 + ject 投，subject 是科目、学科。',
    'player': 'play 玩/打 + er 的人，player 是运动员、选手。',
    'parent': 'par 生 + ent，parent 是父母、家长。',
    'enough': 'en 使 + ough 足够，enough 是足够的。',
}

IMAGE_MNEMONICS: dict[str, str] = {
    'robot': '想象 robot 机器人会跳、会下棋。',
    'jump': '想象 jump 跳起来越过绳子。',
    'rope': '想象 rope 绳子用来跳绳。',
    'chess': '想象 chess 棋盘上的黑白棋子。',
    'australia': '想象 Australia 澳大利亚有袋鼠和考拉。',
    'night': '想象 night 夜晚天空挂着月亮和星星。',
    'phone': '想象 phone 手机拿在手里打电话。',
    'brush': '想象 brush 牙刷在 tooth 牙齿上刷。',
    'tooth': '想象 tooth 牙齿洁白整齐。',
    'seed': '想象 seed 种子埋进土里发芽。',
    'stem': '想象 stem 茎把花和叶子撑起来。',
    'root': '想象 root 根深深扎在地下吸水。',
    'lotus': '想象 lotus 荷花在 lake 湖里开放。',
    'lake': '想象 lake 湖面平静映着蓝天。',
    'river': '想象 river 河水从 mountain 山间流过。',
    'forest': '想象 forest 森林里树木高大茂密。',
    'mountain': '想象 mountain 高山直插云端。',
    'wind': '想象 wind 风吹动 umbrella 和 raincoat。',
    'hotel': '想象 hotel 旅馆里旅客休息过夜。',
    'fog': '想象 fog 大雾里看不清前面的路。',
    'flood': '想象 flood 洪水淹没了道路。',
    'fire': '想象 fire 火焰在 forest 里必须小心防范。',
    'science': '想象 science 科学课里做 robot 实验。',
    'waterfall': '想象 waterfall 瀑布从 mountain 上飞流直下。',
    'dumpling': '想象 dumpling 饺子在碗里热气腾腾。',
}

SEMANTIC_MNEMONICS: dict[str, str] = {
    # Unit 1
    'science': 'We have a science project. science 是科学。',
    'team': 'We are on the same team. team 是队、组、班。',
    'him': 'Give the ball to him. him 是他（宾格）。',
    'lovely': 'She has a lovely smile. lovely 是美丽的、可爱的。',
    'clever': 'My friend is very clever. clever 是聪明的。',
    'young': 'He is young but hard-working. young 是年轻的。',
    'front': 'Sit in the front row. front 是前面、正面。',
    'easy': 'This game is easy. easy 是容易的、简单的。',
    'wonderful': 'We had a wonderful time. wonderful 是极好的、精彩的。',
    # Unit 2
    'sad': "I'm sad today. sad 是难过的、悲哀的。",
    'monday': 'We have English on Monday. Monday 是星期一。',
    'angry': "Don't be angry. angry 是愤怒的、生气的。",
    'yours': 'Yours, Amy. yours 是您的、你们的（信末签名前）。',
    'matter': "What's the matter? matter 是问题、麻烦；要紧。",
    'project': 'We have a science project. project 是项目、方案。',
    'centre': 'Meet me at the sports centre. centre 是中心。',
    'agree': 'I agree with you. agree 是同意、赞成。',
    'finish': 'Please finish your homework. finish 是完成、结束。',
    'worried': "Don't be worried. worried 是担心的、发愁的。",
    'both': 'Both of my parents are teachers. both 是两个都、两者都。',
    'excited': 'We are excited about the trip. excited 是兴奋的、激动的。',
    'wrong': 'Your answer is wrong. wrong 是错误的、有毛病。',
    'afraid': "Don't be afraid. afraid 是害怕、担心。",
    'ask': 'Ask your teacher a question. ask 是问、询问。',
    'move': "Please don't move the desk. move 是移动、搬动。",
    # Unit 3
    'tuesday': 'We have English on Tuesday. Tuesday 是星期二。',
    'wednesday': 'We have maths on Wednesday. Wednesday 是星期三。',
    'friday': 'We have art on Friday. Friday 是星期五。',
    'thursday': 'We have PE on Thursday. Thursday 是星期四。',
    'sunday': 'I rest on Sunday. Sunday 是星期日。',
    'evening': 'I do homework in the evening. evening 是晚上、傍晚。',
    'saturday': 'I have piano on Saturday. Saturday 是星期六。',
    'lesson': 'We have an English lesson. lesson 是课、一节课。',
    'start': 'School starts at eight. start 是开始、着手。',
    'answer': 'Please answer the question. answer 是回答、答案。',
    'visit': 'I visit my grandparents. visit 是拜访、参观。',
    # Unit 4
    'stay': 'Stay at home and rest. stay 是停留、待。',
    'should': 'You should brush your teeth. should 是应该（提出建议）。',
    'flu': 'I have the flu. flu 是流行性感冒。',
    'exercise': 'Do exercise every day. exercise 是锻炼、运动。',
    'take care of': 'Take care of your teeth. take care of 是照顾、爱护。',
    'free': "I'm free this evening. free 是空闲的。",
    'else': 'What else do you do? else 是另外、其他。',
    'if': 'If you are tired, rest. if 是如果、假如。',
    'habit': 'Brushing teeth is a good habit. habit 是习惯。',
    'then': 'Brush your teeth, then go to bed. then 是然后、那么。',
    'rest': 'You need enough rest. rest 是休息、剩余。',
    'check': 'Check your homework. check 是检查、核对。',
    'less': 'Eat less candy. less 是更少、较少。',
    'twice': 'Brush teeth twice a day. twice 是两次、两遍。',
    'hour': 'Rest for one hour. hour 是小时。',
    # Unit 5
    'hungry': "I'm hungry. Let's eat. hungry 是饥饿的。",
    'a little': 'I want a little tea. a little 是少许、一点。',
    'dumpling': 'I like dumplings. dumpling 是饺子、汤圆。',
    'interesting': 'This book is interesting. interesting 是有趣的。',
    'pull up': 'Pull up the carrot. pull up 是把……拔起。',
    'round': 'The seed is round. round 是圆形的。',
    'pull': 'Pull the stem gently. pull 是拉、拽。',
    'world': 'Plants around the world. world 是世界。',
    'way': 'This is a good way to learn. way 是方法、道路。',
    # Unit 6
    'nature': 'I love nature. nature 是自然、自然界。',
    'waterfall': 'We see a waterfall on the trip. waterfall 是瀑布。',
    'go hiking': 'We go hiking on Sunday. go hiking 是徒步旅行。',
    'famous': 'This mountain is famous. famous 是著名的。',
    'trip': 'We are excited about the trip. trip 是旅行、出行。',
    'dangerous': 'Swimming here is dangerous. dangerous 是危险的。',
    'heavy': 'There will be heavy rain. heavy 是大的、严重的（程度）。',
    'close': 'Please close the door. close 是关闭、关上。',
    'worry': "Don't worry. worry 是担心、担忧。",
    'fine': "It's a fine day. fine 是晴朗的；也可表示「好的」。",
    'know': 'I know the way. know 是知道、了解。',
    'bring': 'Bring your raincoat. bring 是带来、拿来。',
}

INFLECTION_NOTES: dict[str, str] = {
    # 名词复数
    'team': '复数 teams',
    'player': '复数 players',
    'parent': '复数 parents',
    'grandparent': '复数 grandparents',
    'subject': '复数 subjects',
    'lesson': '复数 lessons',
    'habit': '复数 habits',
    'tooth': '复数 teeth',
    'hour': '复数 hours',
    'seed': '复数 seeds',
    'root': '复数 roots',
    'river': '复数 rivers',
    'mountain': '复数 mountains',
    'hotel': '复数 hotels',
    'umbrella': '复数 umbrellas',
    'raincoat': '复数 raincoats',
    'dumpling': '复数 dumplings',
    'waterfall': '复数 waterfalls',
    # 动词
    'jump': '第三人称单数 jumps；过去式 jumped',
    'finish': '第三人称单数 finishes；过去式 finished',
    'move': '第三人称单数 moves；过去式 moved',
    'start': '第三人称单数 starts；过去式 started',
    'visit': '第三人称单数 visits；过去式 visited',
    'stay': '第三人称单数 stays；过去式 stayed',
    'check': '第三人称单数 checks；过去式 checked',
    'brush': '第三人称单数 brushes；过去式 brushed',
    'pull': '第三人称单数 pulls；过去式 pulled',
    'worry': '第三人称单数 worries；过去式 worried',
    'know': '第三人称单数 knows；过去式 knew',
    'bring': '第三人称单数 brings；过去式 brought',
    'exercise': '第三人称单数 exercises；过去式 exercised',
    'close': '第三人称单数 closes；过去式 closed',
    'ask': '第三人称单数 asks；过去式 asked',
    'agree': '第三人称单数 agrees；过去式 agreed',
    'answer': '第三人称单数 answers；过去式 answered',
    'show': '第三人称单数 shows；过去式 showed',
    'phone': '第三人称单数 phones；过去式 phoned',
}

DEFINITION_OVERRIDES: dict[str, str] = {
    'team': '队；组；班',
    'lovely': '美丽的；可爱的',
    'jump': '跳；跃',
    'rope': '绳',
    'star': '明星',
    'australia': '澳大利亚',
    'project': '项目；方案',
    'subject': '科目；学科',
    'tuesday': '星期二',
    'monday': '星期一',
    'wednesday': '星期三',
    'thursday': '星期四',
    'friday': '星期五',
    'saturday': '星期六',
    'sunday': '星期日',
    'lesson': '课；一节课',
    'ping-pong': '乒乓球',
    'should': '应该（提出或征询建议）',
    'then': '然后；那么',
    'brush': '刷；刷亮',
    'tooth': '牙；齿',
    'twice': '两次；两遍',
    'beef': '牛肉',
    'mrs': '夫人；太太',
    'coconut': '椰子',
    'seed': '种子',
    'stem': '茎；梗',
    'lake': '湖；湖泊',
    'different': '不同的；有差异的',
    'river': '河；江',
    'mountain': '高山；山岳',
    'wind': '风；气流',
    'hotel': '旅馆；酒店',
    'close': '关闭；关上',
    'umbrella': '伞；雨伞',
    'worry': '担心；担忧',
    'fog': '雾',
    'flood': '洪水；水灾',
    'fire': '火；火灾',
    'show': '节目；（电视或广播）节目',
    'heavy': '大的；严重的（程度）',
    'fine': '晴朗的',
    'sad': '悲哀的；难过的',
    'angry': '愤怒的；生气的',
    'yours': '您的；你们的',
    'flu': '流行性感冒',
    'exercise': '锻炼；训练；操练',
    'free': '没有安排活动的；空闲的',
    'dumpling': '饺子；汤圆',
    'interesting': '有趣的；有吸引力的',
    'round': '环形的；球形的',
    'waterfall': '瀑布',
    'science': '科学',
    'evening': '晚上；傍晚',
    'a little': '少许；一点',
    'pull up': '把……拔起',
    'take care of': '爱护；照顾',
    'go hiking': '徒步旅行',
}

IPA_OVERRIDES: dict[str, str] = {
    'team': '/tiːm/',
    'player': '/ˈpleɪə(r)/',
    'him': '/hɪm/',
    'lovely': '/ˈlʌvli/',
    'clever': '/ˈklevə(r)/',
    'young': '/jʌŋ/',
    'hard-working': '/ˌhɑːd ˈwɜːkɪŋ/',
    'science': '/ˈsaɪəns/',
    'robot': '/ˈrəʊbɒt/',
    'jump': '/dʒʌmp/',
    'rope': '/rəʊp/',
    'piano': '/piˈænəʊ/',
    'chess': '/tʃes/',
    'front': '/frʌnt/',
    'easy': '/ˈiːzi/',
    'star': '/stɑː(r)/',
    'wonderful': '/ˈwʌndəfl/',
    'australia': '/ɒˈstreɪliə/',
    'sad': '/sæd/',
    'matter': '/ˈmætə(r)/',
    'project': '/ˈprɒdʒekt/',
    'centre': '/ˈsentə(r)/',
    'agree': '/əˈɡriː/',
    'finish': '/ˈfɪnɪʃ/',
    'monday': '/ˈmʌndeɪ/',
    'worried': '/ˈwʌrid/',
    'both': '/bəʊθ/',
    'excited': '/ɪkˈsaɪtɪd/',
    'wrong': '/rɒŋ/',
    'angry': '/ˈæŋɡri/',
    'afraid': '/əˈfreɪd/',
    'parent': '/ˈpeərənt/',
    'ask': '/ɑːsk/',
    'move': '/muːv/',
    'yours': '/jɔːz/',
    'wednesday': '/ˈwenzdeɪ/',
    'subject': '/ˈsʌbdʒekt/',
    'tuesday': '/ˈtjuːzdeɪ/',
    'friday': '/ˈfraɪdeɪ/',
    'because': '/bɪˈkɒz/',
    'thursday': '/ˈθɜːzdeɪ/',
    'start': '/stɑːt/',
    'usually': '/ˈjuːʒuəli/',
    'weekend': '/ˌwiːkˈend/',
    'sometimes': '/ˈsʌmtaɪmz/',
    'saturday': '/ˈsætədeɪ/',
    'sunday': '/ˈsʌndeɪ/',
    'lesson': '/ˈlesn/',
    'evening': '/ˈiːvnɪŋ/',
    'answer': '/ˈɑːnsə(r)/',
    'ping-pong': '/ˈpɪŋ pɒŋ/',
    'night': '/naɪt/',
    'visit': '/ˈvɪzɪt/',
    'grandparent': '/ˈɡrænpeərənt/',
    'stay': '/steɪ/',
    'should': '/ʃʊd/',
    'flu': '/fluː/',
    'else': '/els/',
    'exercise': '/ˈeksəsaɪz/',
    'enough': '/ɪˈnʌf/',
    'if': '/ɪf/',
    'habit': '/ˈhæbɪt/',
    'show': '/ʃəʊ/',
    'phone': '/fəʊn/',
    'then': '/ðen/',
    'rest': '/rest/',
    'take care of': '/teɪk keə əv/',
    'check': '/tʃek/',
    'less': '/les/',
    'brush': '/brʌʃ/',
    'tooth': '/tuːθ/',
    'twice': '/twaɪs/',
    'hour': '/ˈaʊə(r)/',
    'free': '/friː/',
    'hungry': '/ˈhʌŋɡri/',
    'beef': '/biːf/',
    'ice cream': '/ˌaɪs ˈkriːm/',
    'a little': '/ə ˈlɪtl/',
    'dumpling': '/ˈdʌmplɪŋ/',
    'tea': '/tiː/',
    'hamburger': '/ˈhæmbɜːɡə(r)/',
    'mrs': '/ˈmɪsɪz/',
    'coconut': '/ˈkəʊkənʌt/',
    'interesting': '/ˈɪntrəstɪŋ/',
    'seed': '/siːd/',
    'pull': '/pʊl/',
    'pull up': '/pʊl ʌp/',
    'stem': '/stem/',
    'root': '/ruːt/',
    'lotus': '/ˈləʊtəs/',
    'lake': '/leɪk/',
    'round': '/raʊnd/',
    'different': '/ˈdɪfrənt/',
    'way': '/weɪ/',
    'river': '/ˈrɪvə(r)/',
    'nature': '/ˈneɪtʃə(r)/',
    'waterfall': '/ˈwɔːtəfɔːl/',
    'forest': '/ˈfɒrɪst/',
    'famous': '/ˈfeɪməs/',
    'mountain': '/ˈmaʊntən/',
    'wind': '/wɪnd/',
    'trip': '/trɪp/',
    'dangerous': '/ˈdeɪndʒərəs/',
    'heavy': '/ˈhevi/',
    'hotel': '/həʊˈtel/',
    'close': '/kləʊz/',
    'umbrella': '/ʌmˈbrelə/',
    'raincoat': '/ˈreɪnkəʊt/',
    'worry': '/ˈwʌri/',
    'fine': '/faɪn/',
    'fog': '/fɒɡ/',
    'flood': '/flʌd/',
    'fire': '/ˈfaɪə(r)/',
    'know': '/nəʊ/',
    'before': '/bɪˈfɔː(r)/',
    'go hiking': '/ɡəʊ ˈhaɪkɪŋ/',
    'bring': '/brɪŋ/',
}

# PDF 词表与通用 pos 推断冲突时的修正
POS_OVERRIDES: dict[str, str] = {
    'show': 'n.',
    'close': 'v.',
    'take care of': 'v. phrase',
    'go hiking': 'v. phrase',
    'pull up': 'v. phrase',
    'a little': 'adv. phrase',
    'ice cream': 'n. phrase',
}


def _secondary_mnemonic(key: str, headword: str, definition_zh: str, *, kind: str) -> str | None:
    if key in ROOT_MNEMONICS:
        return f'拆词联想：{ROOT_MNEMONICS[key]}'
    if key in IMAGE_MNEMONICS:
        return f'形象联想：{IMAGE_MNEMONICS[key]}'
    if key in SEMANTIC_MNEMONICS:
        return f'语义联想：{SEMANTIC_MNEMONICS[key]}'

    short = definition_zh.split('；')[0].split('，')[0].strip()
    if kind == 'phrase':
        return f'语义联想：{headword} 表示「{short}」，在课文对话里反复出现。'
    return f'语义联想：{headword} 表示「{short}」，结合本课例句记忆。'


def mnemonic_for(headword: str, definition_zh: str, *, kind: str) -> str:
    key = headword.lower()
    parts: list[str] = []

    if key in SOUND_MNEMONICS:
        parts.append(f'谐音联想：{SOUND_MNEMONICS[key]}')

    secondary = _secondary_mnemonic(key, headword, definition_zh, kind=kind)
    if secondary:
        if parts:
            if secondary not in parts[0]:
                parts.append(secondary)
        else:
            parts.append(secondary)

    return parts[0] if len(parts) == 1 else '\n'.join(parts)
