"""Mnemonics and inflection notes for PEP Grade 5 English, Volume 2 (下册).

谐音规则与 en-grade3-v2-rj 一致：仅真实谐音，不硬凑；优先语义/形象/拆词联想。
"""

from __future__ import annotations

# 谐音联想：仅 headword 与中文读音确有相似处才写。
SOUND_MNEMONICS: dict[str, str] = {
    'spain': 'Spain 音近「西班」，Spain 就是西班牙。',
    'snow': 'snow 音近「斯诺」，下雪像铺了一层斯诺。',
    'pink': 'pink 音近「品克」，品克让人想到粉红色。',
    'may': 'May 音近「梅」，五月正是梅花开放的时节。',
    'letter': 'letter 音近「来特」，来信特别就是 letter。',
    'cave': 'cave 音近「开夫」，开夫在 cave 洞穴里探险。',
    'game': 'game 音近「盖姆」，盖姆就是游戏 game。',
    'fur': 'fur 音近「佛儿」，软 fur 像佛儿身上柔软的毛。',
    'by': 'by 音近「拜」，by Friday 是「拜五之前」。',
    'lovely': 'lovely 音近「拉夫利」，拉夫利的一天真 lovely。',
    'shop': 'shop 音近「商店」，去 shop 就是去商店买东西。',
    'picnic': 'picnic 音近「皮克尼克」，皮克尼克就是户外野餐。',
    'season': 'season 音近「西森」，一年西森四个 season 季节。',
    'which': 'which 音近「威奇」，威奇哪一个？which 就是哪一个。',
}

ROOT_MNEMONICS: dict[str, str] = {
    'dancing': 'dance 跳舞 + ing，dancing 是正在跳舞、舞蹈。',
    'usually': 'usual 通常 + ly，usually 是通常、平常。',
    'because': 'be 因为 + cause 原因，because 是因为。',
    'vacation': 'vac 空 + ation，vacation 是空下来休息的假期。',
    'island': 'is 是 + land 陆地，island 是岛屿、陆地。',
    'always': 'all 全部 + ways 方式，always 是总是、一直。',
    'jumping': 'jump 跳 + ing，jumping 是正在跳。',
    'drinking': 'drink 喝 + ing，drinking 是正在喝。',
    'sleeping': 'sleep 睡 + ing，sleeping 是正在睡觉。',
    'january': 'Janus 罗马门神，january 是一月、新的一年开始。',
    'february': 'febru 净化 + ary，february 是二月。',
    'march': 'march 本义行进，march 是三月。',
    'april': 'april 与春天开放有关，april 是四月。',
    'june': 'june 与 Juno 女神有关，june 是六月。',
    'july': 'July 来自 Julius Caesar，july 是七月。',
    'august': 'august 来自 Augustus，august 是八月。',
    'september': 'sept 七 + ember，september 是九月。',
    'october': 'oct 八 + ember，october 是十月。',
    'december': 'dec 十 + ember，december 是十二月。',
    'contest': 'con 共同 + test 比试，contest 是比赛、竞赛。',
    'labour': 'labour 即 labor 劳动，labour 是劳动；Labour Day 是劳动节。',
    'national': 'nation 国家 + al，national 是国家的。',
    'american': 'America 美国 + n，American 是美国的；美国人。',
    'thanksgiving': 'thanks 感谢 + giving 给予，Thanksgiving 是感恩节。',
    'christmas': 'Christ 基督 + mas 弥撒，Christmas 是圣诞节。',
    'festival': 'fest 节日 + ival，festival 是节日。',
    'special': 'spec 特别 + ial，special 是特别的。',
    'diary': 'di 日 + ary，diary 是日记、日记本。',
    'bamboo': 'bamboo 双音叠词像竹子节节生长，bamboo 是竹子。',
    'exercise': 'ex 向外 + ercise，exercise 是活动、运动、锻炼。',
    'november': 'novem 九 + ber，november 是十一月（古罗马历第九月）。',
    'autumn': 'autumn 与 harvest 相关，autumn 是秋天。',
    'winter': 'win 冷 + ter，winter 是冬天。',
    'spring': 'spring 本义跳跃、萌发，spring 是春天。',
    'summer': 'sum 顶 + mer，summer 是夏天。',
    'eating': 'eating 吃 + ing，eating 是正在吃。',
    'playing': 'play 玩 + ing，playing 是正在玩耍。',
    'climbing': 'climb 爬 + ing，climbing 是正在攀爬。',
    'having … class': 'having 正在 + class 课，having … class 是正在上课。',
    'eating lunch': 'eating 正在吃 + lunch 午餐，eating lunch 是正在吃午饭。',
    'reading a book': 'reading 正在读 + a book 书，reading a book 是正在看书。',
    'listening to music': 'listening 正在听 + music 音乐，listening to music 是正在听音乐。',
    # Unit 1 短语
    'eat breakfast': 'eat 吃 + breakfast 早餐，eat breakfast 是吃早饭。',
    'have … class': 'have 有/上 + class 课，have … class 是上……课。',
    'play sports': 'play 进行 + sports 运动，play sports 是做体育运动。',
    'do morning exercises': 'do 做 + morning exercises 早操，合起来是做早操。',
    'eat dinner': 'eat 吃 + dinner 晚餐，eat dinner 是吃晚饭。',
    'clean my room': 'clean 打扫 + my room 我的房间，clean my room 是打扫房间。',
    'go for a walk': 'go 去 + for a walk 散步，go for a walk 是散步。',
    'go shopping': 'go 去 + shopping 购物，go shopping 是去买东西。',
    'take a dancing class': 'take 上 + a dancing class 舞蹈课，take a dancing class 是上舞蹈课。',
    'go swimming': 'go 去 + swimming 游泳，go swimming 是去游泳。',
    # Unit 2 短语
    'go on a picnic': 'go 去 + on a picnic 野餐，go on a picnic 是去野餐。',
    'pick apples': 'pick 摘 + apples 苹果，pick apples 是摘苹果。',
    'make a snowman': 'make 制作 + a snowman 雪人，make a snowman 是堆雪人。',
    'good job': 'good 好 + job 工作/表现，good job 是做得好。',
    'sports meet': 'sports 运动 + meet 集会，sports meet 是运动会。',
    # Unit 3 短语
    'a few': 'a 一些 + few 少数，a few 是一些、几个。',
    'labour day': 'labour 劳动 + Day 日，Labour Day 是劳动节。',
    'the great wall': 'the Great Wall 专有名词，the Great Wall 是长城。',
    'national day': 'national 国家的 + Day 日，National Day 是国庆节。',
    'act out': 'act 表演 + out 出来，act out 是把……表演出来。',
    # Unit 4 序数
    'first (1st)': 'first 第一，(1st) 是 first 的缩写。',
    'second (2nd)': 'second 第二，(2nd) 是 second 的缩写。',
    'third (3rd)': 'third 第三，(3rd) 是 third 的缩写。',
    'fourth (4th)': 'fourth 第四，(4th) 是 fourth 的缩写。',
    'fifth (5th)': 'fifth 第五，(5th) 是 fifth 的缩写。',
    'twelfth (12th)': 'twelve 十二变 twelfth，(12th) 是第十二。',
    'twentieth (20th)': 'twenty 二十变 twentieth，(20th) 是第二十。',
    'twenty-first (21st)': 'twenty-one 二十一变 twenty-first，(21st) 是第二十一。',
    'twenty-third (23rd)': 'twenty-three 二十三变 twenty-third，(23rd) 是第二十三。',
    'thirtieth (30th)': 'thirty 三十变 thirtieth，(30th) 是第三十。',
    # Unit 5–6 短语
    'each other': 'each 每个 + other 其他，each other 是互相、彼此。',
    'doing morning exercises': 'do morning exercises 的 -ing 形式，正在做早操。',
    'keep to the right': 'keep 保持 + to the right 靠右，keep to the right 是靠右行走。',
    'keep your desk clean': 'keep 保持 + your desk clean 课桌干净，keep your desk clean 是保持课桌整洁。',
    'talk quietly': 'talk 说话 + quietly 小声地，talk quietly 是小声讲话。',
    'take turns': 'take 轮流 + turns 次/轮，take turns 是按顺序来、轮流。',
    'have a look': 'have 进行 + a look 看一看，have a look 是看一看。',
}

IMAGE_MNEMONICS: dict[str, str] = {
    'take': '想象 take a class 背着书包走进教室上课。',
    'when': '想象 when 钟表指针指向问「什么时候」。',
    'after': '想象 after 太阳落山后 after school 的活动。',
    'late': '想象 late 闹钟响晚了，匆匆忙忙赶上学。',
    'busy': '想象 busy 日程表上排满舞蹈课和作业。',
    'play': '想象 play 舞台上演员们排演一出戏剧。',
    'live': '想象 live 一家人住在海边的小岛上。',
    'cave': '想象 cave 黑暗的洞穴里点着火把。',
    'best': '想象 best 季节排行榜上秋天排在第一。',
    'snow': '想象 snow 白茫茫的雪地上堆雪人。',
    'leaf': '想象 leaf 一片红黄相间的叶子飘落。',
    'fall': '想象 fall 秋天 leaf 从树上 fall 落下。',
    'paint': '想象 paint 用颜料画出四季的风景。',
    'plant': '想象 plant 把小树苗种进春天的土里。',
    'trip': '想象 trip 同学们背着书包去春游。',
    'riddle': '想象 riddle 猜谜语时挠头想答案。',
    'kitten': '想象 kitten 一只毛茸茸的小猫在玩耍。',
    'show': '想象 show 美术馆里挂着一排排画作展览。',
    'noise': '想象 noise 节日里鞭炮和音乐混在一起。',
    'fur': '想象 fur 小猫身上柔软细密的毛。',
    'walk': '想象 walk 晚饭后在展览馆外散步。',
    'mine': '想象 mine 用手指指「这是我的」。',
    'bamboo': '想象 bamboo 熊猫抱着绿竹子大口咀嚼。',
    'spring': '想象 spring 春天里万物发芽、花儿开放。',
    'summer': '想象 summer 烈日下跳进泳池游泳。',
    'autumn': '想象 autumn 金黄的叶子从树上飘落。',
    'winter': '想象 winter 雪地里堆 snowman 雪人。',
    'season': '想象 season 春夏秋冬四个季节轮替。',
    'picnic': '想象 picnic 草地上铺餐布、分享食物。',
    'snowman': '想象 snowman 滚雪球堆成戴帽子的雪人。',
    'pick': '想象 pick 伸手从树上 pick apples 摘苹果。',
    'exercise': '想象 exercise 操场上整齐做早操。',
    'shop': '想象 shop 和妈妈一起推购物车购物。',
}

SEMANTIC_MNEMONICS: dict[str, str] = {
    # Unit 1
    'take': 'I take a dancing class. take 这里指学习、上（课）。',
    'dancing': 'My hobby is dancing. dancing 是跳舞、舞蹈。',
    'start': 'School starts at eight. start 是开始、着手。',
    'why': 'Why are you so busy? why 是为什么。',
    'work': 'I work hard at school. work 是工作、劳动；努力。',
    'last': 'I was busy last weekend. last 是上一个、刚过去的。',
    'sound': 'That sounds fun. sound 是听起来、好像。',
    'also': 'I like dancing, and I also like singing. also 是还、也。',
    'need': 'I need to take a class. need 是需要。',
    'letter': 'I write a letter to my pen pal. letter 是信；字母。',
    'island': 'They live on an island. island 是岛、岛屿。',
    'win': 'Our team won the game. win 是获胜、赢。',
    'exercise': 'We do exercise in the playground. exercise 是活动、运动。',
    'shop': 'I shop with my mum on Saturday. shop 是去买东西、购物。',
    'spain': 'My pen pal is from Spain. Spain 是西班牙。',
    'which': 'Which season do you like best? which 是哪一个。',
    'spring': 'Spring is warm and green. spring 是春天。',
    'summer': 'Summer is hot and sunny. summer 是夏天。',
    'autumn': 'Leaves turn yellow in autumn. autumn 是秋天。',
    'winter': 'We make a snowman in winter. winter 是冬天。',
    'season': 'There are four seasons in a year. season 是季节。',
    'picnic': 'We have a picnic in the park. picnic 是野餐。',
    'pick': 'We pick apples in autumn. pick 是摘、采集。',
    'snowman': 'We made a big snowman. snowman 是雪人。',
    'november': 'Thanksgiving is in November. November 是十一月。',
    'a.m.': 'a.m. = ante meridiem，拉丁语「午前」，a.m. 是上午。',
    'p.m.': 'p.m. = post meridiem，拉丁语「午后」，p.m. 是下午。',
    'rsvp': 'RSVP 来自法语 Répondez s\'il vous plaît，意为请赐复。',
    'eating': 'The panda is eating bamboo. eating 是正在吃。',
    'playing': 'The children are playing in the park. playing 是正在玩耍。',
    'climbing': 'The panda is climbing the tree. climbing 是正在攀爬。',
    'having … class': 'We are having an English class. having … class 是正在上课。',
    'eating lunch': 'They are eating lunch now. eating lunch 是正在吃午饭。',
    'reading a book': 'He is reading a book quietly. reading a book 是正在看书。',
    'listening to music': 'She is listening to music. listening to music 是正在听音乐。',
    # Unit 2
    'best': 'Which season do you like best? best 是最好的。',
    'vacation': 'We have a winter vacation. vacation 是假期。',
    'all': 'I like all the seasons. all 是全、全部。',
    'lovely': 'What lovely flowers! lovely 是美丽的、可爱的。',
    'because': 'I like winter because I can play in the snow. because 是因为。',
    # Unit 3
    'april': 'We have a school trip in April. April 是四月。',
    'may': 'May Day is on the first of May. May 是五月。',
    'few': 'There are a few things on my desk. few 是不多、少数。',
    'thing': 'Pack the things you need. thing 是东西、事情。',
    'meet': 'We will meet at the gate. meet 是集会、开会、见面。',
    'year': 'There are twelve months in a year. year 是年、年份。',
    'game': "Let's play a word game. game 是游戏、比赛。",
    'act': 'The children act out a story. act 是扮演、表演。',
    'march': 'We plant trees in March. March 是三月。',
    'june': "Children's Day is in June. June 是六月。",
    'july': 'Summer vacation starts in July. July 是七月。',
    'august': 'We travel in August. August 是八月。',
    'september': 'School starts again in September. September 是九月。',
    'october': 'National Day is in October. October 是十月。',
    'january': 'Winter vacation is in January. January 是一月。',
    'february': 'We go back to school in February. February 是二月。',
    'december': 'Christmas is in December. December 是十二月。',
    # Unit 4
    'other': 'Some festivals are special; other festivals are fun too. other 是其他。',
    'festival': 'The Spring Festival is my favourite festival. festival 是节日。',
    'diary': 'I write in my diary every day. diary 是日记。',
    'still': 'The museum is still open. still 是仍然、还；静止的。',
    'open': 'The show is open today. open 是开放的、营业的。',
    'special': 'Mid-Autumn Festival is a special day. special 是特别的。',
    # Unit 5
    'yours': 'Is this pen yours? yours 是你的。',
    'his': 'This is his book. his 是他的。',
    'hers': 'The pink coat is hers. hers 是她的。',
    'theirs': 'The big house is theirs. theirs 是他们的。',
    'ours': 'This classroom is ours. ours 是我们的。',
    'each': 'Each student has a book. each 是每个、各自。',
    # Unit 6
    'its': 'The panda is eating its bamboo. its 是它的。',
    'excited': 'We are excited about the trip. excited 是兴奋的、激动的。',
    'like': 'He looks like his father. like 这里表示像……那样。',
    'doing morning exercises': 'They are doing morning exercises. 正在做早操。',
    'keep': 'Keep quiet in the library. keep 是保持某种状态。',
    'turn': 'Wait your turn. turn 可指顺序、轮流。',
    'anything': 'Do you need anything else? anything 是任何事物。',
    'else': 'What else do you do? else 是另外、其他。',
    'exhibition': 'There is a photo exhibition. exhibition 是展览。',
    'say': 'Please say it again. say 是说、讲。',
    'sushi': 'I like sushi. sushi 是寿司。',
    'teach': 'My mother teaches English. teach 是教。',
    'sure': 'Sure, I can help you. sure 表示当然、好的。',
    'canadian': 'He has a Canadian friend. Canadian 是加拿大的。',
    'spanish': 'She speaks Spanish. Spanish 是西班牙的。',
}

INFLECTION_NOTES: dict[str, str] = {
    # 名词复数
    'leaf': '复数 leaves',
    'island': '复数 islands',
    'cave': '复数 caves',
    'thing': '复数 things',
    'diary': '复数 diaries',
    'festival': '复数 festivals',
    # 动词
    'take': '第三人称单数 takes；过去式 took',
    'start': '第三人称单数 starts；过去式 started',
    'work': '第三人称单数 works；过去式 worked',
    'need': '第三人称单数 needs；过去式 needed',
    'live': '第三人称单数 lives；过去式 lived',
    'win': '第三人称单数 wins；过去式 won',
    'snow': '第三人称单数 snows；过去式 snowed',
    'fall': '第三人称单数 falls；过去式 fell；fall 也可指【美】秋天',
    'paint': '第三人称单数 paints；过去式 painted',
    'meet': '第三人称单数 meets；过去式 met',
    'plant': '第三人称单数 plants；过去式 planted',
    'act': '第三人称单数 acts；过去式 acted',
    'walk': '第三人称单数 walks；过去式 walked',
    'open': '第三人称单数 opens；过去式 opened',
    # -ing 形式对应原形
    'dancing': '原形 dance；dancing 表示正在跳舞',
    'jumping': '原形 jump；jumping 表示正在跳',
    'drinking': '原形 drink；drinking 表示正在喝',
    'sleeping': '原形 sleep；sleeping 表示正在睡觉',
    'eating': '原形 eat；eating 表示正在吃',
    'playing': '原形 play；playing 表示正在玩耍',
    'climbing': '原形 climb；climbing 表示正在攀爬',
    'pick': '第三人称单数 picks；过去式 picked',
    'shop': '第三人称单数 shops；过去式 shopped',
    'exercise': '第三人称单数 exercises；过去式 exercised',
    'snowman': '复数 snowmen',
    'picnic': '复数 picnics',
    'teach': '第三人称单数 teaches；过去式 taught',
    'keep': '第三人称单数 keeps；过去式 kept',
    'say': '第三人称单数 says；过去式 said',
    'turn': '第三人称单数 turns；过去式 turned',
    'excited': '由 excite 变化而来；比较级 more excited',
    'doing morning exercises': '原形 do morning exercises',
    'first (1st)': '序数词；缩写 1st = first',
    'second (2nd)': '序数词；缩写 2nd = second',
    'third (3rd)': '序数词；缩写 3rd = third',
    'fourth (4th)': '序数词；缩写 4th = fourth',
    'fifth (5th)': '序数词；缩写 5th = fifth',
    'twelfth (12th)': '由 twelve 变来；缩写 12th',
    'twentieth (20th)': '由 twenty 变来；缩写 20th',
    'twenty-first (21st)': '由 twenty-one 变来；缩写 21st',
    'twenty-third (23rd)': '由 twenty-three 变来；缩写 23rd',
    'thirtieth (30th)': '由 thirty 变来；缩写 30th',
}

DEFINITION_OVERRIDES: dict[str, str] = {
    'take': '学习；上（课）',
    'play': '戏剧；剧本',
    'sound': '听起来；好像',
    'meet': '集会；开会',
    'show': '展览；给人看',
    'leaf': '叶子',
    'jumping': '（正在）跳',
    'drinking': '（正在）喝',
    'sleeping': '（正在）睡觉',
    'fall': '落下；【美】秋天',
    'spain': '西班牙',
    'dancing': '跳舞；舞蹈',
    'island': '岛；岛屿',
    'cave': '洞穴；山洞',
    'vacation': '假期',
    'labour': '劳动；Labour Day 劳动节',
    'national': '国家的',
    'american': '美国的；美国人',
    'thanksgiving': '感恩节',
    'christmas': '圣诞节',
    'contest': '比赛；竞赛',
    'festival': '节日',
    'kitten': '小猫',
    'diary': '日记；日记本',
    'bamboo': '竹子',
    'january': '一月',
    'february': '二月',
    'march': '三月',
    'april': '四月',
    'may': '五月',
    'june': '六月',
    'july': '七月',
    'august': '八月',
    'september': '九月',
    'october': '十月',
    'december': '十二月',
    'mine': '我的',
    'yours': '你的',
    'his': '他的',
    'hers': '她的',
    'theirs': '他们的',
    'ours': '我们的',
    'each': '每个；各自',
    'its': '它的',
    'exercise': '活动；运动',
    'shop': '去买东西；购物',
    'spring': '春天',
    'summer': '夏天',
    'autumn': '秋天',
    'winter': '冬天',
    'season': '季节',
    'picnic': '野餐',
    'pick': '摘；采集',
    'snowman': '雪人',
    'which': '哪一个',
    'november': '十一月',
    'rsvp': '请赐复',
    'eating': '（正在）吃',
    'playing': '（正在）玩耍',
    'eat breakfast': '吃早饭',
    'have … class': '上⋯⋯课',
    'play sports': '进行体育运动',
    'do morning exercises': '做早操',
    'eat dinner': '吃晚饭',
    'clean my room': '打扫我的房间',
    'go for a walk': '散步',
    'go shopping': '去买东西；购物',
    'take a dancing class': '上舞蹈课',
    'a.m.': '午前；上午',
    'p.m.': '午后；下午',
    'go swimming': '去游泳',
    'go on a picnic': '去野餐',
    'pick apples': '摘苹果',
    'make a snowman': '堆雪人',
    'good job': '做得好',
    'a few': '一些',
    'sports meet': '运动会',
    'labour day': '劳动节',
    'the great wall': '长城',
    'national day': '国庆日',
    'act out': '把……表演出来',
    'first (1st)': '第一（的）',
    'second (2nd)': '第二（的）',
    'third (3rd)': '第三（的）',
    'fourth (4th)': '第四（的）',
    'fifth (5th)': '第五（的）',
    'twelfth (12th)': '第十二（的）',
    'twentieth (20th)': '第二十（的）',
    'twenty-first (21st)': '第二十一（的）',
    'twenty-third (23rd)': '第二十三（的）',
    'thirtieth (30th)': '第三十（的）',
    'each other': '相互',
    'keep to the right': '靠右',
    'keep your desk clean': '保持你的课桌干净',
    'talk quietly': '小声讲话',
    'take turns': '按顺序来',
    'have a look': '看一看',
    'excited': '兴奋的；激动的',
    'like': '像……那样',
    'doing morning exercises': '（正在）做早操',
    'keep': '保持某种状态',
    'turn': '顺序；轮流',
    'anything': '任何事物',
    'else': '另外；其他',
    'exhibition': '展览',
    'say': '说；讲',
    'sushi': '寿司',
    'teach': '教',
    'sure': '（表示同意）当然',
    'canadian': '加拿大的',
    'spanish': '西班牙的',
    'climbing': '（正在）攀登；攀爬',
    'having … class': '（正在）上……课',
    'eating lunch': '（正在）吃午饭',
    'reading a book': '（正在）看书',
    'listening to music': '（正在）听音乐',
}

IPA_OVERRIDES: dict[str, str] = {
    'eat breakfast': '/iːt ˈbrekfəst/',
    'have … class': '/hæv klɑːs/',
    'play sports': '/pleɪ spɔːts/',
    'do morning exercises': '/duː ˈmɔːnɪŋ ˈeksəsaɪzɪz/',
    'eat dinner': '/iːt ˈdɪnə(r)/',
    'clean my room': '/kliːn maɪ ruːm/',
    'go for a walk': '/ɡəʊ fər ə wɔːk/',
    'go shopping': '/ɡəʊ ˈʃɒpɪŋ/',
    'take a dancing class': '/teɪk ə ˈdɑːnsɪŋ klɑːs/',
    'shop': '/ʃɒp/',
    'go swimming': '/ɡəʊ ˈswɪmɪŋ/',
    'go on a picnic': '/ɡəʊ ɒn ə ˈpɪknɪk/',
    'pick apples': '/pɪk ˈæplz/',
    'make a snowman': '/meɪk ə ˈsnəʊmæn/',
    'good job': '/ɡʊd dʒɒb/',
    'a few': '/ə fjuː/',
    'sports meet': '/spɔːts miːt/',
    'labour day': '/ˈleɪbə deɪ/',
    'the great wall': '/ðə ɡreɪt wɔːl/',
    'national day': '/ˈnæʃnəl deɪ/',
    'act out': '/ækt aʊt/',
    'each other': '/iːtʃ ˈʌðə(r)/',
    'doing morning exercises': '/ˈduːɪŋ ˈmɔːnɪŋ ˈeksəsaɪzɪz/',
    'having … class': '/ˈhævɪŋ klɑːs/',
    'eating lunch': '/ˈiːtɪŋ lʌntʃ/',
    'reading a book': '/ˈriːdɪŋ ə bʊk/',
    'listening to music': '/ˈlɪsnɪŋ tə ˈmjuːzɪk/',
    'keep to the right': '/kiːp tə ðə raɪt/',
    'keep your desk clean': '/kiːp jɔː(r) desk kliːn/',
    'talk quietly': '/tɔːk ˈkwaɪətli/',
    'take turns': '/teɪk tɜːnz/',
    'have a look': '/hæv ə lʊk/',
    'climbing': '/ˈklaɪmɪŋ/',
    'other': '/ˈʌðə(r)/',
    'theirs': '/ðeəz/',
    'ours': '/aʊəz/',
    'rsvp': '/ˌɑː es viː ˈpiː/',
}

# PDF 词表与通用 pos 推断冲突时的修正
POS_OVERRIDES: dict[str, str] = {
    'play': 'n.',
    'show': 'n.',
    'sound': 'v.',
    'take': 'v.',
    'open': 'adj.',
    'mine': 'pron.',
    'yours': 'pron.',
    'his': 'pron.',
    'hers': 'pron.',
    'theirs': 'pron.',
    'ours': 'pron.',
    'shop': 'v.',
    'pick': 'v.',
    'exercise': 'n.',
    'picnic': 'n.',
    'snowman': 'n.',
    'which': 'pron.',
    'season': 'n.',
    'spring': 'n.',
    'summer': 'n.',
    'autumn': 'n.',
    'winter': 'n.',
    'november': 'n.',
    'rsvp': 'abbr.',
    'eating': 'v.',
    'turn': 'v.',
    'teach': 'v.',
    'say': 'v.',
    'keep': 'v.',
    'like': 'prep.',
    'excited': 'adj.',
    'canadian': 'adj.',
    'spanish': 'adj.',
    'sure': 'adv.',
    'anything': 'pron.',
    'climbing': 'v.',
    'having … class': 'v. phrase',
    'eating lunch': 'v. phrase',
    'reading a book': 'v. phrase',
    'listening to music': 'v. phrase',
}


def _secondary_mnemonic(key: str, headword: str, definition_zh: str, *, kind: str) -> str | None:
    if key in ROOT_MNEMONICS:
        return f'拆词联想：{ROOT_MNEMONICS[key]}'
    if key in IMAGE_MNEMONICS:
        return f'形象联想：{IMAGE_MNEMONICS[key]}'
    if key in SEMANTIC_MNEMONICS:
        return f'语义联想：{SEMANTIC_MNEMONICS[key]}'

    short = definition_zh.split('；')[0].split('，')[0].strip()
    if kind == 'phrase':
        return f'语义联想：{headword} 表示「{short}」，在课文对话里反复出现。'
    return f'语义联想：{headword} 表示「{short}」，结合本课例句记忆。'


def mnemonic_for(headword: str, definition_zh: str, *, kind: str) -> str:
    key = headword.lower()
    parts: list[str] = []

    if key in SOUND_MNEMONICS:
        parts.append(f'谐音联想：{SOUND_MNEMONICS[key]}')

    secondary = _secondary_mnemonic(key, headword, definition_zh, kind=kind)
    if secondary:
        if parts:
            if secondary not in parts[0]:
                parts.append(secondary)
        else:
            parts.append(secondary)

    return parts[0] if len(parts) == 1 else '\n'.join(parts)
